/**
 * Hanzo Cloud API
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CloudApi.h
 *
 * 
 */

#ifndef HANZO_API_CloudApi_H_
#define HANZO_API_CloudApi_H_



#include "hanzo/ApiClient.h"

#include "hanzo/model/AccountFoldView.h"
#include "hanzo/model/CloudAccountsView.h"
#include "hanzo/model/ProvidersView.h"
#include "hanzo/model/UnlinkedView.h"
#include "hanzo/model/VenueLinkRequest.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace hanzo {
namespace api {

using namespace hanzo::model;



class  CloudApi 
{
public:

    explicit CloudApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~CloudApi();

    /// <summary>
    /// Forgets one linked cloud account: it detaches every fleet cluster THIS account folded (its own names, in its own shard — a neighbour&#39;s cluster of the same name is untouched), deletes the sealed credential, and drops the index row.
    /// </summary>
    /// <remarks>
    /// Forgets one linked cloud account: it detaches every fleet cluster THIS account folded (its own names, in its own shard — a neighbour&#39;s cluster of the same name is untouched), deletes the sealed credential, and drops the index row.  It is idempotent and deliberately not an existence oracle: an account this org does not hold answers exactly the same as one it just removed. A cluster that fails to detach is logged and the unlink continues, so a dead provider cannot strand a credential. Requires org admin.
    /// </remarks>
    /// <param name="provider">Provider is the cloud the account belongs to: digitalocean, aws, gcp or azure. An unknown provider is not found.</param>
    /// <param name="label">Label is the org-chosen name of the account within that provider. Empty means \&quot;default\&quot;; anything outside 1–64 of [A-Za-z0-9._-] is refused.</param>
    pplx::task<std::shared_ptr<UnlinkedView>> deleteCloudByProviderAccountsByLabel(
        utility::string_t provider,
        utility::string_t label
    ) const;
    /// <summary>
    /// Returns the clouds this deployment can link and what linking each one needs — the DigitalOcean token, the AWS role and external id, the GCP credential JSON, the Azure app — plus whether the provider can be linked without storing any long-lived secret.
    /// </summary>
    /// <remarks>
    /// Returns the clouds this deployment can link and what linking each one needs — the DigitalOcean token, the AWS role and external id, the GCP credential JSON, the Azure app — plus whether the provider can be linked without storing any long-lived secret. It is the catalog a \&quot;connect a cloud\&quot; screen renders; it reports no account and no credential.
    /// </remarks>
    pplx::task<std::shared_ptr<ProvidersView>> getCloud(
    ) const;
    /// <summary>
    /// Lists the caller org&#39;s linked cloud accounts across every provider: which account each one is at the provider, which fleet clusters it folded, and when it was last discovered.
    /// </summary>
    /// <remarks>
    /// Lists the caller org&#39;s linked cloud accounts across every provider: which account each one is at the provider, which fleet clusters it folded, and when it was last discovered. Metadata only — a sealed credential never appears in a response. Another org&#39;s accounts are not visible and not countable.
    /// </remarks>
    pplx::task<std::shared_ptr<CloudAccountsView>> getCloudAccounts(
    ) const;
    /// <summary>
    /// Links one of the caller org&#39;s cloud accounts and folds the Kubernetes clusters it finds there into the ONE Hanzo fleet, so they appear at /v1/clusters and can run work like any managed or bring-your-own cluster.
    /// </summary>
    /// <remarks>
    /// Links one of the caller org&#39;s cloud accounts and folds the Kubernetes clusters it finds there into the ONE Hanzo fleet, so they appear at /v1/clusters and can run work like any managed or bring-your-own cluster. Answers 201.  The credential is verified LIVE against the provider BEFORE anything is stored, so a bad one is refused and nothing is written; it is then sealed in the org&#39;s own KMS namespace and never appears in a response, the account index, or a log line. Discovery follows, and a cluster that fails to fold is reported as DATA in the clusters list rather than failing the link.  Re-linking a label that already exists re-seals its credential and re-folds it, so this is how a rotated token is replaced. Requires org admin.
    /// </remarks>
    /// <param name="provider">Provider is the cloud being linked, from the path: digitalocean, aws, gcp or azure.</param>
    /// <param name="venueLinkRequest"></param>
    pplx::task<std::shared_ptr<AccountFoldView>> postCloudByProviderAccounts(
        utility::string_t provider,
        std::shared_ptr<VenueLinkRequest> venueLinkRequest
    ) const;
    /// <summary>
    /// Re-discovers one already-linked cloud account and reconciles what it folded: kubeconfigs are refreshed, clusters that appeared since the last sync are folded, and clusters this account folded that the provider no longer returns are detached — only this account&#39;s own, in the fleet shard it was linked into.
    /// </summary>
    /// <remarks>
    /// Re-discovers one already-linked cloud account and reconciles what it folded: kubeconfigs are refreshed, clusters that appeared since the last sync are folded, and clusters this account folded that the provider no longer returns are detached — only this account&#39;s own, in the fleet shard it was linked into.  It is idempotent, it reads the credential already sealed at link time, and a discovery failure leaves the existing fold set alone rather than mass-detaching it. An account this org has not linked is not found. Requires org admin.
    /// </remarks>
    /// <param name="provider">Provider is the cloud the account belongs to: digitalocean, aws, gcp or azure. An unknown provider is not found.</param>
    /// <param name="label">Label is the org-chosen name of the account within that provider. Empty means \&quot;default\&quot;; anything outside 1–64 of [A-Za-z0-9._-] is refused.</param>
    pplx::task<std::shared_ptr<AccountFoldView>> postCloudByProviderAccountsByLabelSync(
        utility::string_t provider,
        utility::string_t label
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}

#endif /* HANZO_API_CloudApi_H_ */

