/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CollectApi.h
 *
 * 
 */

#ifndef HANZO_API_CollectApi_H_
#define HANZO_API_CollectApi_H_



#include "hanzo/ApiClient.h"

#include "hanzo/model/Analytics_SendPayload.h"
#include "hanzo/model/Analytics_batch_200_response.h"
#include "hanzo/model/Analytics_send_200_response.h"
#include <vector>
#include <boost/optional.hpp>

namespace hanzo {
namespace api {

using namespace hanzo::model;



class  CollectApi 
{
public:

    explicit CollectApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~CollectApi();

    /// <summary>
    /// Send a batch of events
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="analyticsSendPayload"></param>
    pplx::task<std::shared_ptr<Analytics_batch_200_response>> analyticsBatch(
        std::vector<std::shared_ptr<Analytics_SendPayload>> analyticsSendPayload
    ) const;
    /// <summary>
    /// Send a single event or identify payload
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="analyticsSendPayload"></param>
    pplx::task<std::shared_ptr<Analytics_send_200_response>> analyticsSend(
        std::shared_ptr<Analytics_SendPayload> analyticsSendPayload
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}

#endif /* HANZO_API_CollectApi_H_ */

