/**
 * Hanzo Cloud API
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * K8sApi.h
 *
 * 
 */

#ifndef HANZO_API_K8sApi_H_
#define HANZO_API_K8sApi_H_



#include "hanzo/ApiClient.h"

#include "hanzo/model/ClusterDetailView.h"
#include "hanzo/model/ClusterList.h"
#include "hanzo/model/ClusterView.h"
#include "hanzo/model/CreateClusterReq.h"
#include "hanzo/model/NodeList.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace hanzo {
namespace api {

using namespace hanzo::model;



class  K8sApi 
{
public:

    explicit K8sApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~K8sApi();

    /// <summary>
    /// Provisions a DOKS cluster for the caller&#39;s org and answers 201.
    /// </summary>
    /// <remarks>
    /// Provisions a DOKS cluster for the caller&#39;s org and answers 201. ADMIN-GATED — a SuperAdmin, or an OrgAdmin of the caller&#39;s own org — because provisioning spends real infrastructure on the house account. The request is validated at this boundary, then Visor owns provisioning and the hanzo-org ownership tag.
    /// </remarks>
    /// <param name="createClusterReq"></param>
    pplx::task<std::shared_ptr<ClusterView>> createKubernetesCluster(
        std::shared_ptr<CreateClusterReq> createClusterReq
    ) const;
    /// <summary>
    /// Destroys a DOKS cluster by id and answers 204.
    /// </summary>
    /// <remarks>
    /// Destroys a DOKS cluster by id and answers 204. ADMIN-GATED, like create. Visor scopes the delete to the org (refuses a foreign id), so this can only ever remove the caller org&#39;s own cluster.
    /// </remarks>
    /// <param name="id">ID is the provider&#39;s DOKS cluster id. Visor scopes the lookup to the caller&#39;s org, so another tenant&#39;s id resolves to not-found rather than their cluster.</param>
    pplx::task<void> deleteKubernetesCluster(
        utility::string_t id
    ) const;
    /// <summary>
    /// Returns one cluster&#39;s detail: node pools + worker nodes.
    /// </summary>
    /// <remarks>
    /// Returns one cluster&#39;s detail: node pools + worker nodes. Visor scopes the lookup to the org (a foreign or missing id resolves to not-found), so a tenant can never read another tenant&#39;s cluster by guessing an id.
    /// </remarks>
    /// <param name="id">ID is the provider&#39;s DOKS cluster id. Visor scopes the lookup to the caller&#39;s org, so another tenant&#39;s id resolves to not-found rather than their cluster.</param>
    pplx::task<std::shared_ptr<ClusterDetailView>> getKubernetesCluster(
        utility::string_t id
    ) const;
    /// <summary>
    /// Lists the org&#39;s DOKS clusters (Visor, house account) folded with the org&#39;s BYO clusters — ONE fleet cluster view under the unified k8s noun.
    /// </summary>
    /// <remarks>
    /// Lists the org&#39;s DOKS clusters (Visor, house account) folded with the org&#39;s BYO clusters — ONE fleet cluster view under the unified k8s noun. A Visor outage is logged and skipped so a down optional provider never hides the BYO list.
    /// </remarks>
    pplx::task<std::shared_ptr<ClusterList>> listKubernetesClusters(
    ) const;
    /// <summary>
    /// Returns every DOKS worker node in the org&#39;s clusters as a machine — the SAME set the fleet folds in (managedMachines), exposed directly under the k8s noun.
    /// </summary>
    /// <remarks>
    /// Returns every DOKS worker node in the org&#39;s clusters as a machine — the SAME set the fleet folds in (managedMachines), exposed directly under the k8s noun. House account (hanzo-org cluster tag) + BYOC, deduped by Visor.
    /// </remarks>
    pplx::task<std::shared_ptr<NodeList>> listKubernetesNodes(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}

#endif /* HANZO_API_K8sApi_H_ */

