/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "hanzo/model/Analytics_joinTeam_request.h"

namespace hanzo {
namespace model {

Analytics_joinTeam_request::Analytics_joinTeam_request()
{
    m_AccessCode = utility::conversions::to_string_t("");
    m_AccessCodeIsSet = false;
}

Analytics_joinTeam_request::~Analytics_joinTeam_request()
{
}

void Analytics_joinTeam_request::validate()
{
    // TODO: implement validation
}

web::json::value Analytics_joinTeam_request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_AccessCodeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("accessCode"))] = ModelBase::toJson(m_AccessCode);
    }

    return val;
}

bool Analytics_joinTeam_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("accessCode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("accessCode")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAccessCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAccessCode);
            setAccessCode(refVal_setAccessCode);
            
        }
    }
    return ok;
}

void Analytics_joinTeam_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_AccessCodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("accessCode")), m_AccessCode));
    }
}

bool Analytics_joinTeam_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("accessCode"))))
    {
        utility::string_t refVal_setAccessCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("accessCode"))), refVal_setAccessCode );
        setAccessCode(refVal_setAccessCode);
    }
    return ok;
}


utility::string_t Analytics_joinTeam_request::getAccessCode() const
{
    return m_AccessCode;
}


void Analytics_joinTeam_request::setAccessCode(const utility::string_t& value)
{
    m_AccessCode = value;
    m_AccessCodeIsSet = true;
}

bool Analytics_joinTeam_request::accessCodeIsSet() const
{
    return m_AccessCodeIsSet;
}

void Analytics_joinTeam_request::unsetAccessCode()
{
    m_AccessCodeIsSet = false;
}

}
}


