/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "hanzo/model/Analysis.h"

namespace hanzo {
namespace model {

Analysis::Analysis()
{
    m_Alpha = 0.0;
    m_AlphaIsSet = false;
    m_Experiment = utility::conversions::to_string_t("");
    m_ExperimentIsSet = false;
    m_ExposedTotal = 0;
    m_ExposedTotalIsSet = false;
    m_Metric = utility::conversions::to_string_t("");
    m_MetricIsSet = false;
    m_ResultsIsSet = false;
    m_Winner = utility::conversions::to_string_t("");
    m_WinnerIsSet = false;
}

Analysis::~Analysis()
{
}

void Analysis::validate()
{
    // TODO: implement validation
}

web::json::value Analysis::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_AlphaIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("alpha"))] = ModelBase::toJson(m_Alpha);
    }
    if(m_ExperimentIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("experiment"))] = ModelBase::toJson(m_Experiment);
    }
    if(m_ExposedTotalIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("exposedTotal"))] = ModelBase::toJson(m_ExposedTotal);
    }
    if(m_MetricIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("metric"))] = ModelBase::toJson(m_Metric);
    }
    if(m_ResultsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("results"))] = ModelBase::toJson(m_Results);
    }
    if(m_WinnerIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("winner"))] = ModelBase::toJson(m_Winner);
    }

    return val;
}

bool Analysis::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("alpha"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("alpha")));
        if(!fieldValue.is_null())
        {
            double refVal_setAlpha;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAlpha);
            setAlpha(refVal_setAlpha);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("experiment"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("experiment")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setExperiment;
            ok &= ModelBase::fromJson(fieldValue, refVal_setExperiment);
            setExperiment(refVal_setExperiment);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("exposedTotal"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("exposedTotal")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setExposedTotal;
            ok &= ModelBase::fromJson(fieldValue, refVal_setExposedTotal);
            setExposedTotal(refVal_setExposedTotal);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("metric"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("metric")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMetric;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMetric);
            setMetric(refVal_setMetric);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("results"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("results")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Outcome>> refVal_setResults;
            ok &= ModelBase::fromJson(fieldValue, refVal_setResults);
            setResults(refVal_setResults);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("winner"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("winner")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWinner;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWinner);
            setWinner(refVal_setWinner);
            
        }
    }
    return ok;
}

void Analysis::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_AlphaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("alpha")), m_Alpha));
    }
    if(m_ExperimentIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("experiment")), m_Experiment));
    }
    if(m_ExposedTotalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("exposedTotal")), m_ExposedTotal));
    }
    if(m_MetricIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("metric")), m_Metric));
    }
    if(m_ResultsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("results")), m_Results));
    }
    if(m_WinnerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("winner")), m_Winner));
    }
}

bool Analysis::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("alpha"))))
    {
        double refVal_setAlpha;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("alpha"))), refVal_setAlpha );
        setAlpha(refVal_setAlpha);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("experiment"))))
    {
        utility::string_t refVal_setExperiment;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("experiment"))), refVal_setExperiment );
        setExperiment(refVal_setExperiment);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("exposedTotal"))))
    {
        int32_t refVal_setExposedTotal;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("exposedTotal"))), refVal_setExposedTotal );
        setExposedTotal(refVal_setExposedTotal);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("metric"))))
    {
        utility::string_t refVal_setMetric;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("metric"))), refVal_setMetric );
        setMetric(refVal_setMetric);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("results"))))
    {
        std::vector<std::shared_ptr<Outcome>> refVal_setResults;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("results"))), refVal_setResults );
        setResults(refVal_setResults);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("winner"))))
    {
        utility::string_t refVal_setWinner;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("winner"))), refVal_setWinner );
        setWinner(refVal_setWinner);
    }
    return ok;
}


double Analysis::getAlpha() const
{
    return m_Alpha;
}


void Analysis::setAlpha(double value)
{
    m_Alpha = value;
    m_AlphaIsSet = true;
}

bool Analysis::alphaIsSet() const
{
    return m_AlphaIsSet;
}

void Analysis::unsetAlpha()
{
    m_AlphaIsSet = false;
}
utility::string_t Analysis::getExperiment() const
{
    return m_Experiment;
}


void Analysis::setExperiment(const utility::string_t& value)
{
    m_Experiment = value;
    m_ExperimentIsSet = true;
}

bool Analysis::experimentIsSet() const
{
    return m_ExperimentIsSet;
}

void Analysis::unsetExperiment()
{
    m_ExperimentIsSet = false;
}
int32_t Analysis::getExposedTotal() const
{
    return m_ExposedTotal;
}


void Analysis::setExposedTotal(int32_t value)
{
    m_ExposedTotal = value;
    m_ExposedTotalIsSet = true;
}

bool Analysis::exposedTotalIsSet() const
{
    return m_ExposedTotalIsSet;
}

void Analysis::unsetExposedTotal()
{
    m_ExposedTotalIsSet = false;
}
utility::string_t Analysis::getMetric() const
{
    return m_Metric;
}


void Analysis::setMetric(const utility::string_t& value)
{
    m_Metric = value;
    m_MetricIsSet = true;
}

bool Analysis::metricIsSet() const
{
    return m_MetricIsSet;
}

void Analysis::unsetMetric()
{
    m_MetricIsSet = false;
}
std::vector<std::shared_ptr<Outcome>> Analysis::getResults() const
{
    return m_Results;
}


void Analysis::setResults(const std::vector<std::shared_ptr<Outcome>>& value)
{
    m_Results = value;
    m_ResultsIsSet = true;
}

bool Analysis::resultsIsSet() const
{
    return m_ResultsIsSet;
}

void Analysis::unsetResults()
{
    m_ResultsIsSet = false;
}
utility::string_t Analysis::getWinner() const
{
    return m_Winner;
}


void Analysis::setWinner(const utility::string_t& value)
{
    m_Winner = value;
    m_WinnerIsSet = true;
}

bool Analysis::winnerIsSet() const
{
    return m_WinnerIsSet;
}

void Analysis::unsetWinner()
{
    m_WinnerIsSet = false;
}

}
}


