/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "hanzo/model/AskPostIn.h"

namespace hanzo {
namespace model {

AskPostIn::AskPostIn()
{
    m_Query = utility::conversions::to_string_t("");
    m_QueryIsSet = false;
    m_Repo = utility::conversions::to_string_t("");
    m_RepoIsSet = false;
}

AskPostIn::~AskPostIn()
{
}

void AskPostIn::validate()
{
    // TODO: implement validation
}

web::json::value AskPostIn::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_QueryIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("query"))] = ModelBase::toJson(m_Query);
    }
    if(m_RepoIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("repo"))] = ModelBase::toJson(m_Repo);
    }

    return val;
}

bool AskPostIn::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("query"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("query")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setQuery;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQuery);
            setQuery(refVal_setQuery);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("repo"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("repo")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRepo;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRepo);
            setRepo(refVal_setRepo);
            
        }
    }
    return ok;
}

void AskPostIn::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_QueryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("query")), m_Query));
    }
    if(m_RepoIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("repo")), m_Repo));
    }
}

bool AskPostIn::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("query"))))
    {
        utility::string_t refVal_setQuery;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("query"))), refVal_setQuery );
        setQuery(refVal_setQuery);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("repo"))))
    {
        utility::string_t refVal_setRepo;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("repo"))), refVal_setRepo );
        setRepo(refVal_setRepo);
    }
    return ok;
}


utility::string_t AskPostIn::getQuery() const
{
    return m_Query;
}


void AskPostIn::setQuery(const utility::string_t& value)
{
    m_Query = value;
    m_QueryIsSet = true;
}

bool AskPostIn::queryIsSet() const
{
    return m_QueryIsSet;
}

void AskPostIn::unsetQuery()
{
    m_QueryIsSet = false;
}
utility::string_t AskPostIn::getRepo() const
{
    return m_Repo;
}


void AskPostIn::setRepo(const utility::string_t& value)
{
    m_Repo = value;
    m_RepoIsSet = true;
}

bool AskPostIn::repoIsSet() const
{
    return m_RepoIsSet;
}

void AskPostIn::unsetRepo()
{
    m_RepoIsSet = false;
}

}
}


