/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "hanzo/model/Authors_AuthorDashboard.h"

namespace hanzo {
namespace model {

Authors_AuthorDashboard::Authors_AuthorDashboard()
{
    m_IsAuthor = false;
    m_IsAuthorIsSet = false;
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_StatusIsSet = false;
    m_GithubLogin = utility::conversions::to_string_t("");
    m_GithubLoginIsSet = false;
    m_Verified = false;
    m_VerifiedIsSet = false;
    m_VerifyCode = utility::conversions::to_string_t("");
    m_VerifyCodeIsSet = false;
    m_VerifyFile = utility::conversions::to_string_t("");
    m_VerifyFileIsSet = false;
    m_VerifySnippet = utility::conversions::to_string_t("");
    m_VerifySnippetIsSet = false;
    m_ShareBps = 0L;
    m_ShareBpsIsSet = false;
    m_BadgeBase = utility::conversions::to_string_t("");
    m_BadgeBaseIsSet = false;
    m_ReposIsSet = false;
    m_DeploysIsSet = false;
    m_AccruedCents = 0L;
    m_AccruedCentsIsSet = false;
    m_PendingCents = 0L;
    m_PendingCentsIsSet = false;
    m_PaidCents = 0L;
    m_PaidCentsIsSet = false;
    m_PayoutsIsSet = false;
}

Authors_AuthorDashboard::~Authors_AuthorDashboard()
{
}

void Authors_AuthorDashboard::validate()
{
    // TODO: implement validation
}

web::json::value Authors_AuthorDashboard::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IsAuthorIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("isAuthor"))] = ModelBase::toJson(m_IsAuthor);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_StatusIsSet)
    {
        
        utility::string_t refVal = fromStatusEnum(m_Status);
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(refVal);
        
    }
    if(m_GithubLoginIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("githubLogin"))] = ModelBase::toJson(m_GithubLogin);
    }
    if(m_VerifiedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("verified"))] = ModelBase::toJson(m_Verified);
    }
    if(m_VerifyCodeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("verifyCode"))] = ModelBase::toJson(m_VerifyCode);
    }
    if(m_VerifyFileIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("verifyFile"))] = ModelBase::toJson(m_VerifyFile);
    }
    if(m_VerifySnippetIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("verifySnippet"))] = ModelBase::toJson(m_VerifySnippet);
    }
    if(m_ShareBpsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("shareBps"))] = ModelBase::toJson(m_ShareBps);
    }
    if(m_BadgeBaseIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("badgeBase"))] = ModelBase::toJson(m_BadgeBase);
    }
    if(m_ReposIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("repos"))] = ModelBase::toJson(m_Repos);
    }
    if(m_DeploysIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("deploys"))] = ModelBase::toJson(m_Deploys);
    }
    if(m_AccruedCentsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("accruedCents"))] = ModelBase::toJson(m_AccruedCents);
    }
    if(m_PendingCentsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("pendingCents"))] = ModelBase::toJson(m_PendingCents);
    }
    if(m_PaidCentsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("paidCents"))] = ModelBase::toJson(m_PaidCents);
    }
    if(m_PayoutsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("payouts"))] = ModelBase::toJson(m_Payouts);
    }

    return val;
}

bool Authors_AuthorDashboard::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("isAuthor"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("isAuthor")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsAuthor;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsAuthor);
            setIsAuthor(refVal_setIsAuthor);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            
            setStatus(toStatusEnum(refVal_setStatus));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("githubLogin"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("githubLogin")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setGithubLogin;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGithubLogin);
            setGithubLogin(refVal_setGithubLogin);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("verified"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("verified")));
        if(!fieldValue.is_null())
        {
            bool refVal_setVerified;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVerified);
            setVerified(refVal_setVerified);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("verifyCode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("verifyCode")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setVerifyCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVerifyCode);
            setVerifyCode(refVal_setVerifyCode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("verifyFile"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("verifyFile")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setVerifyFile;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVerifyFile);
            setVerifyFile(refVal_setVerifyFile);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("verifySnippet"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("verifySnippet")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setVerifySnippet;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVerifySnippet);
            setVerifySnippet(refVal_setVerifySnippet);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("shareBps"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("shareBps")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setShareBps;
            ok &= ModelBase::fromJson(fieldValue, refVal_setShareBps);
            setShareBps(refVal_setShareBps);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("badgeBase"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("badgeBase")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBadgeBase;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBadgeBase);
            setBadgeBase(refVal_setBadgeBase);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("repos"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("repos")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Authors_RepoView>> refVal_setRepos;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRepos);
            setRepos(refVal_setRepos);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("deploys"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("deploys")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Authors_DeployView>> refVal_setDeploys;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDeploys);
            setDeploys(refVal_setDeploys);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("accruedCents"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("accruedCents")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setAccruedCents;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAccruedCents);
            setAccruedCents(refVal_setAccruedCents);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("pendingCents"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("pendingCents")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setPendingCents;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPendingCents);
            setPendingCents(refVal_setPendingCents);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("paidCents"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("paidCents")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setPaidCents;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPaidCents);
            setPaidCents(refVal_setPaidCents);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("payouts"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("payouts")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Authors_PayoutView>> refVal_setPayouts;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPayouts);
            setPayouts(refVal_setPayouts);
            
        }
    }
    return ok;
}

void Authors_AuthorDashboard::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IsAuthorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("isAuthor")), m_IsAuthor));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), fromStatusEnum(m_Status)));
    }
    if(m_GithubLoginIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("githubLogin")), m_GithubLogin));
    }
    if(m_VerifiedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("verified")), m_Verified));
    }
    if(m_VerifyCodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("verifyCode")), m_VerifyCode));
    }
    if(m_VerifyFileIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("verifyFile")), m_VerifyFile));
    }
    if(m_VerifySnippetIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("verifySnippet")), m_VerifySnippet));
    }
    if(m_ShareBpsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("shareBps")), m_ShareBps));
    }
    if(m_BadgeBaseIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("badgeBase")), m_BadgeBase));
    }
    if(m_ReposIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("repos")), m_Repos));
    }
    if(m_DeploysIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("deploys")), m_Deploys));
    }
    if(m_AccruedCentsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("accruedCents")), m_AccruedCents));
    }
    if(m_PendingCentsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("pendingCents")), m_PendingCents));
    }
    if(m_PaidCentsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("paidCents")), m_PaidCents));
    }
    if(m_PayoutsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("payouts")), m_Payouts));
    }
}

bool Authors_AuthorDashboard::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("isAuthor"))))
    {
        bool refVal_setIsAuthor;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("isAuthor"))), refVal_setIsAuthor );
        setIsAuthor(refVal_setIsAuthor);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(toStatusEnum(refVal_setStatus));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("githubLogin"))))
    {
        utility::string_t refVal_setGithubLogin;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("githubLogin"))), refVal_setGithubLogin );
        setGithubLogin(refVal_setGithubLogin);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("verified"))))
    {
        bool refVal_setVerified;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("verified"))), refVal_setVerified );
        setVerified(refVal_setVerified);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("verifyCode"))))
    {
        utility::string_t refVal_setVerifyCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("verifyCode"))), refVal_setVerifyCode );
        setVerifyCode(refVal_setVerifyCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("verifyFile"))))
    {
        utility::string_t refVal_setVerifyFile;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("verifyFile"))), refVal_setVerifyFile );
        setVerifyFile(refVal_setVerifyFile);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("verifySnippet"))))
    {
        utility::string_t refVal_setVerifySnippet;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("verifySnippet"))), refVal_setVerifySnippet );
        setVerifySnippet(refVal_setVerifySnippet);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("shareBps"))))
    {
        int64_t refVal_setShareBps;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("shareBps"))), refVal_setShareBps );
        setShareBps(refVal_setShareBps);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("badgeBase"))))
    {
        utility::string_t refVal_setBadgeBase;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("badgeBase"))), refVal_setBadgeBase );
        setBadgeBase(refVal_setBadgeBase);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("repos"))))
    {
        std::vector<std::shared_ptr<Authors_RepoView>> refVal_setRepos;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("repos"))), refVal_setRepos );
        setRepos(refVal_setRepos);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("deploys"))))
    {
        std::vector<std::shared_ptr<Authors_DeployView>> refVal_setDeploys;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("deploys"))), refVal_setDeploys );
        setDeploys(refVal_setDeploys);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("accruedCents"))))
    {
        int64_t refVal_setAccruedCents;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("accruedCents"))), refVal_setAccruedCents );
        setAccruedCents(refVal_setAccruedCents);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("pendingCents"))))
    {
        int64_t refVal_setPendingCents;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("pendingCents"))), refVal_setPendingCents );
        setPendingCents(refVal_setPendingCents);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("paidCents"))))
    {
        int64_t refVal_setPaidCents;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("paidCents"))), refVal_setPaidCents );
        setPaidCents(refVal_setPaidCents);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("payouts"))))
    {
        std::vector<std::shared_ptr<Authors_PayoutView>> refVal_setPayouts;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("payouts"))), refVal_setPayouts );
        setPayouts(refVal_setPayouts);
    }
    return ok;
}

Authors_AuthorDashboard::StatusEnum Authors_AuthorDashboard::toStatusEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("connected")) {
        return StatusEnum::CONNECTED;
    }
    
    if (value == utility::conversions::to_string_t("approved")) {
        return StatusEnum::APPROVED;
    }
    
    if (value == utility::conversions::to_string_t("suspended")) {
        return StatusEnum::SUSPENDED;
    }
    
    throw std::invalid_argument("Invalid value for conversion to StatusEnum");
}


const utility::string_t Authors_AuthorDashboard::fromStatusEnum(const StatusEnum value) const
{
    switch(value)
    {
        
        case StatusEnum::CONNECTED: return utility::conversions::to_string_t("connected");
        
        case StatusEnum::APPROVED: return utility::conversions::to_string_t("approved");
        
        case StatusEnum::SUSPENDED: return utility::conversions::to_string_t("suspended");
        
    }
}


bool Authors_AuthorDashboard::isIsAuthor() const
{
    return m_IsAuthor;
}


void Authors_AuthorDashboard::setIsAuthor(bool value)
{
    m_IsAuthor = value;
    m_IsAuthorIsSet = true;
}

bool Authors_AuthorDashboard::isAuthorIsSet() const
{
    return m_IsAuthorIsSet;
}

void Authors_AuthorDashboard::unsetIsAuthor()
{
    m_IsAuthorIsSet = false;
}
utility::string_t Authors_AuthorDashboard::getId() const
{
    return m_Id;
}


void Authors_AuthorDashboard::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Authors_AuthorDashboard::idIsSet() const
{
    return m_IdIsSet;
}

void Authors_AuthorDashboard::unsetId()
{
    m_IdIsSet = false;
}
Authors_AuthorDashboard::StatusEnum Authors_AuthorDashboard::getStatus() const
{
    return m_Status;
}


void Authors_AuthorDashboard::setStatus(const StatusEnum value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool Authors_AuthorDashboard::statusIsSet() const
{
    return m_StatusIsSet;
}

void Authors_AuthorDashboard::unsetStatus()
{
    m_StatusIsSet = false;
}
utility::string_t Authors_AuthorDashboard::getGithubLogin() const
{
    return m_GithubLogin;
}


void Authors_AuthorDashboard::setGithubLogin(const utility::string_t& value)
{
    m_GithubLogin = value;
    m_GithubLoginIsSet = true;
}

bool Authors_AuthorDashboard::githubLoginIsSet() const
{
    return m_GithubLoginIsSet;
}

void Authors_AuthorDashboard::unsetGithubLogin()
{
    m_GithubLoginIsSet = false;
}
bool Authors_AuthorDashboard::isVerified() const
{
    return m_Verified;
}


void Authors_AuthorDashboard::setVerified(bool value)
{
    m_Verified = value;
    m_VerifiedIsSet = true;
}

bool Authors_AuthorDashboard::verifiedIsSet() const
{
    return m_VerifiedIsSet;
}

void Authors_AuthorDashboard::unsetVerified()
{
    m_VerifiedIsSet = false;
}
utility::string_t Authors_AuthorDashboard::getVerifyCode() const
{
    return m_VerifyCode;
}


void Authors_AuthorDashboard::setVerifyCode(const utility::string_t& value)
{
    m_VerifyCode = value;
    m_VerifyCodeIsSet = true;
}

bool Authors_AuthorDashboard::verifyCodeIsSet() const
{
    return m_VerifyCodeIsSet;
}

void Authors_AuthorDashboard::unsetVerifyCode()
{
    m_VerifyCodeIsSet = false;
}
utility::string_t Authors_AuthorDashboard::getVerifyFile() const
{
    return m_VerifyFile;
}


void Authors_AuthorDashboard::setVerifyFile(const utility::string_t& value)
{
    m_VerifyFile = value;
    m_VerifyFileIsSet = true;
}

bool Authors_AuthorDashboard::verifyFileIsSet() const
{
    return m_VerifyFileIsSet;
}

void Authors_AuthorDashboard::unsetVerifyFile()
{
    m_VerifyFileIsSet = false;
}
utility::string_t Authors_AuthorDashboard::getVerifySnippet() const
{
    return m_VerifySnippet;
}


void Authors_AuthorDashboard::setVerifySnippet(const utility::string_t& value)
{
    m_VerifySnippet = value;
    m_VerifySnippetIsSet = true;
}

bool Authors_AuthorDashboard::verifySnippetIsSet() const
{
    return m_VerifySnippetIsSet;
}

void Authors_AuthorDashboard::unsetVerifySnippet()
{
    m_VerifySnippetIsSet = false;
}
int64_t Authors_AuthorDashboard::getShareBps() const
{
    return m_ShareBps;
}


void Authors_AuthorDashboard::setShareBps(int64_t value)
{
    m_ShareBps = value;
    m_ShareBpsIsSet = true;
}

bool Authors_AuthorDashboard::shareBpsIsSet() const
{
    return m_ShareBpsIsSet;
}

void Authors_AuthorDashboard::unsetShareBps()
{
    m_ShareBpsIsSet = false;
}
utility::string_t Authors_AuthorDashboard::getBadgeBase() const
{
    return m_BadgeBase;
}


void Authors_AuthorDashboard::setBadgeBase(const utility::string_t& value)
{
    m_BadgeBase = value;
    m_BadgeBaseIsSet = true;
}

bool Authors_AuthorDashboard::badgeBaseIsSet() const
{
    return m_BadgeBaseIsSet;
}

void Authors_AuthorDashboard::unsetBadgeBase()
{
    m_BadgeBaseIsSet = false;
}
std::vector<std::shared_ptr<Authors_RepoView>> Authors_AuthorDashboard::getRepos() const
{
    return m_Repos;
}


void Authors_AuthorDashboard::setRepos(const std::vector<std::shared_ptr<Authors_RepoView>>& value)
{
    m_Repos = value;
    m_ReposIsSet = true;
}

bool Authors_AuthorDashboard::reposIsSet() const
{
    return m_ReposIsSet;
}

void Authors_AuthorDashboard::unsetRepos()
{
    m_ReposIsSet = false;
}
std::vector<std::shared_ptr<Authors_DeployView>> Authors_AuthorDashboard::getDeploys() const
{
    return m_Deploys;
}


void Authors_AuthorDashboard::setDeploys(const std::vector<std::shared_ptr<Authors_DeployView>>& value)
{
    m_Deploys = value;
    m_DeploysIsSet = true;
}

bool Authors_AuthorDashboard::deploysIsSet() const
{
    return m_DeploysIsSet;
}

void Authors_AuthorDashboard::unsetDeploys()
{
    m_DeploysIsSet = false;
}
int64_t Authors_AuthorDashboard::getAccruedCents() const
{
    return m_AccruedCents;
}


void Authors_AuthorDashboard::setAccruedCents(int64_t value)
{
    m_AccruedCents = value;
    m_AccruedCentsIsSet = true;
}

bool Authors_AuthorDashboard::accruedCentsIsSet() const
{
    return m_AccruedCentsIsSet;
}

void Authors_AuthorDashboard::unsetAccruedCents()
{
    m_AccruedCentsIsSet = false;
}
int64_t Authors_AuthorDashboard::getPendingCents() const
{
    return m_PendingCents;
}


void Authors_AuthorDashboard::setPendingCents(int64_t value)
{
    m_PendingCents = value;
    m_PendingCentsIsSet = true;
}

bool Authors_AuthorDashboard::pendingCentsIsSet() const
{
    return m_PendingCentsIsSet;
}

void Authors_AuthorDashboard::unsetPendingCents()
{
    m_PendingCentsIsSet = false;
}
int64_t Authors_AuthorDashboard::getPaidCents() const
{
    return m_PaidCents;
}


void Authors_AuthorDashboard::setPaidCents(int64_t value)
{
    m_PaidCents = value;
    m_PaidCentsIsSet = true;
}

bool Authors_AuthorDashboard::paidCentsIsSet() const
{
    return m_PaidCentsIsSet;
}

void Authors_AuthorDashboard::unsetPaidCents()
{
    m_PaidCentsIsSet = false;
}
std::vector<std::shared_ptr<Authors_PayoutView>> Authors_AuthorDashboard::getPayouts() const
{
    return m_Payouts;
}


void Authors_AuthorDashboard::setPayouts(const std::vector<std::shared_ptr<Authors_PayoutView>>& value)
{
    m_Payouts = value;
    m_PayoutsIsSet = true;
}

bool Authors_AuthorDashboard::payoutsIsSet() const
{
    return m_PayoutsIsSet;
}

void Authors_AuthorDashboard::unsetPayouts()
{
    m_PayoutsIsSet = false;
}

}
}


