/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "hanzo/model/BillingInvoice.h"

namespace hanzo {
namespace model {

BillingInvoice::BillingInvoice()
{
    m_AmountDue = 0;
    m_AmountDueIsSet = false;
    m_AmountPaid = 0;
    m_AmountPaidIsSet = false;
    m_AttemptCount = 0;
    m_AttemptCountIsSet = false;
    m_CreatedAt = utility::conversions::to_string_t("");
    m_CreatedAtIsSet = false;
    m_CreditApplied = 0;
    m_CreditAppliedIsSet = false;
    m_Currency = utility::conversions::to_string_t("");
    m_CurrencyIsSet = false;
    m_CustomerEmail = utility::conversions::to_string_t("");
    m_CustomerEmailIsSet = false;
    m_Discount = 0;
    m_DiscountIsSet = false;
    m_DueDate = utility::conversions::to_string_t("");
    m_DueDateIsSet = false;
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_LineItemsIsSet = false;
    m_number = 0;
    m_numberIsSet = false;
    m_NumberStr = utility::conversions::to_string_t("");
    m_NumberStrIsSet = false;
    m_PaidAt = utility::conversions::to_string_t("");
    m_PaidAtIsSet = false;
    m_PaymentMethod = utility::conversions::to_string_t("");
    m_PaymentMethodIsSet = false;
    m_PaymentRef = utility::conversions::to_string_t("");
    m_PaymentRefIsSet = false;
    m_PeriodEnd = utility::conversions::to_string_t("");
    m_PeriodEndIsSet = false;
    m_PeriodStart = utility::conversions::to_string_t("");
    m_PeriodStartIsSet = false;
    m_Status = utility::conversions::to_string_t("");
    m_StatusIsSet = false;
    m_SubscriptionId = utility::conversions::to_string_t("");
    m_SubscriptionIdIsSet = false;
    m_Subtotal = 0;
    m_SubtotalIsSet = false;
    m_Tax = 0;
    m_TaxIsSet = false;
    m_UpdatedAt = utility::conversions::to_string_t("");
    m_UpdatedAtIsSet = false;
    m_UserId = utility::conversions::to_string_t("");
    m_UserIdIsSet = false;
    m_VoidedAt = utility::conversions::to_string_t("");
    m_VoidedAtIsSet = false;
}

BillingInvoice::~BillingInvoice()
{
}

void BillingInvoice::validate()
{
    // TODO: implement validation
}

web::json::value BillingInvoice::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_AmountDueIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("amountDue"))] = ModelBase::toJson(m_AmountDue);
    }
    if(m_AmountPaidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("amountPaid"))] = ModelBase::toJson(m_AmountPaid);
    }
    if(m_AttemptCountIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("attemptCount"))] = ModelBase::toJson(m_AttemptCount);
    }
    if(m_CreatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdAt"))] = ModelBase::toJson(m_CreatedAt);
    }
    if(m_CreditAppliedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("creditApplied"))] = ModelBase::toJson(m_CreditApplied);
    }
    if(m_CurrencyIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("currency"))] = ModelBase::toJson(m_Currency);
    }
    if(m_CustomerEmailIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("customerEmail"))] = ModelBase::toJson(m_CustomerEmail);
    }
    if(m_DiscountIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("discount"))] = ModelBase::toJson(m_Discount);
    }
    if(m_DueDateIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("dueDate"))] = ModelBase::toJson(m_DueDate);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_LineItemsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("lineItems"))] = ModelBase::toJson(m_LineItems);
    }
    if(m_numberIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("number"))] = ModelBase::toJson(m_number);
    }
    if(m_NumberStrIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("numberStr"))] = ModelBase::toJson(m_NumberStr);
    }
    if(m_PaidAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("paidAt"))] = ModelBase::toJson(m_PaidAt);
    }
    if(m_PaymentMethodIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("paymentMethod"))] = ModelBase::toJson(m_PaymentMethod);
    }
    if(m_PaymentRefIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("paymentRef"))] = ModelBase::toJson(m_PaymentRef);
    }
    if(m_PeriodEndIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("periodEnd"))] = ModelBase::toJson(m_PeriodEnd);
    }
    if(m_PeriodStartIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("periodStart"))] = ModelBase::toJson(m_PeriodStart);
    }
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_SubscriptionIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("subscriptionId"))] = ModelBase::toJson(m_SubscriptionId);
    }
    if(m_SubtotalIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("subtotal"))] = ModelBase::toJson(m_Subtotal);
    }
    if(m_TaxIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tax"))] = ModelBase::toJson(m_Tax);
    }
    if(m_UpdatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updatedAt"))] = ModelBase::toJson(m_UpdatedAt);
    }
    if(m_UserIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("userId"))] = ModelBase::toJson(m_UserId);
    }
    if(m_VoidedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("voidedAt"))] = ModelBase::toJson(m_VoidedAt);
    }

    return val;
}

bool BillingInvoice::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("amountDue"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("amountDue")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setAmountDue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAmountDue);
            setAmountDue(refVal_setAmountDue);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("amountPaid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("amountPaid")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setAmountPaid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAmountPaid);
            setAmountPaid(refVal_setAmountPaid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("attemptCount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("attemptCount")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setAttemptCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAttemptCount);
            setAttemptCount(refVal_setAttemptCount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("creditApplied"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("creditApplied")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setCreditApplied;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreditApplied);
            setCreditApplied(refVal_setCreditApplied);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("currency"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("currency")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCurrency;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCurrency);
            setCurrency(refVal_setCurrency);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("customerEmail"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("customerEmail")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCustomerEmail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCustomerEmail);
            setCustomerEmail(refVal_setCustomerEmail);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("discount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("discount")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setDiscount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDiscount);
            setDiscount(refVal_setDiscount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("dueDate"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("dueDate")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDueDate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDueDate);
            setDueDate(refVal_setDueDate);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("lineItems"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("lineItems")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<InvoiceLineItem>> refVal_setLineItems;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLineItems);
            setLineItems(refVal_setLineItems);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("number"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("number")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setNumber;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNumber);
            setNumber(refVal_setNumber);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("numberStr"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("numberStr")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setNumberStr;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNumberStr);
            setNumberStr(refVal_setNumberStr);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("paidAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("paidAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPaidAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPaidAt);
            setPaidAt(refVal_setPaidAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("paymentMethod"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("paymentMethod")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPaymentMethod;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPaymentMethod);
            setPaymentMethod(refVal_setPaymentMethod);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("paymentRef"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("paymentRef")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPaymentRef;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPaymentRef);
            setPaymentRef(refVal_setPaymentRef);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("periodEnd"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("periodEnd")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPeriodEnd;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPeriodEnd);
            setPeriodEnd(refVal_setPeriodEnd);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("periodStart"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("periodStart")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPeriodStart;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPeriodStart);
            setPeriodStart(refVal_setPeriodStart);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subscriptionId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subscriptionId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSubscriptionId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubscriptionId);
            setSubscriptionId(refVal_setSubscriptionId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subtotal"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subtotal")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setSubtotal;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubtotal);
            setSubtotal(refVal_setSubtotal);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tax"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tax")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTax;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTax);
            setTax(refVal_setTax);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updatedAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("userId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("userId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUserId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUserId);
            setUserId(refVal_setUserId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("voidedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("voidedAt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setVoidedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVoidedAt);
            setVoidedAt(refVal_setVoidedAt);
            
        }
    }
    return ok;
}

void BillingInvoice::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_AmountDueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("amountDue")), m_AmountDue));
    }
    if(m_AmountPaidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("amountPaid")), m_AmountPaid));
    }
    if(m_AttemptCountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("attemptCount")), m_AttemptCount));
    }
    if(m_CreatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdAt")), m_CreatedAt));
    }
    if(m_CreditAppliedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("creditApplied")), m_CreditApplied));
    }
    if(m_CurrencyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("currency")), m_Currency));
    }
    if(m_CustomerEmailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("customerEmail")), m_CustomerEmail));
    }
    if(m_DiscountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("discount")), m_Discount));
    }
    if(m_DueDateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("dueDate")), m_DueDate));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_LineItemsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("lineItems")), m_LineItems));
    }
    if(m_numberIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("number")), m_number));
    }
    if(m_NumberStrIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("numberStr")), m_NumberStr));
    }
    if(m_PaidAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("paidAt")), m_PaidAt));
    }
    if(m_PaymentMethodIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("paymentMethod")), m_PaymentMethod));
    }
    if(m_PaymentRefIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("paymentRef")), m_PaymentRef));
    }
    if(m_PeriodEndIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("periodEnd")), m_PeriodEnd));
    }
    if(m_PeriodStartIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("periodStart")), m_PeriodStart));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_SubscriptionIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subscriptionId")), m_SubscriptionId));
    }
    if(m_SubtotalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subtotal")), m_Subtotal));
    }
    if(m_TaxIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tax")), m_Tax));
    }
    if(m_UpdatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updatedAt")), m_UpdatedAt));
    }
    if(m_UserIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("userId")), m_UserId));
    }
    if(m_VoidedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("voidedAt")), m_VoidedAt));
    }
}

bool BillingInvoice::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("amountDue"))))
    {
        int32_t refVal_setAmountDue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("amountDue"))), refVal_setAmountDue );
        setAmountDue(refVal_setAmountDue);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("amountPaid"))))
    {
        int32_t refVal_setAmountPaid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("amountPaid"))), refVal_setAmountPaid );
        setAmountPaid(refVal_setAmountPaid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("attemptCount"))))
    {
        int32_t refVal_setAttemptCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("attemptCount"))), refVal_setAttemptCount );
        setAttemptCount(refVal_setAttemptCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        utility::string_t refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("creditApplied"))))
    {
        int32_t refVal_setCreditApplied;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("creditApplied"))), refVal_setCreditApplied );
        setCreditApplied(refVal_setCreditApplied);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("currency"))))
    {
        utility::string_t refVal_setCurrency;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("currency"))), refVal_setCurrency );
        setCurrency(refVal_setCurrency);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("customerEmail"))))
    {
        utility::string_t refVal_setCustomerEmail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("customerEmail"))), refVal_setCustomerEmail );
        setCustomerEmail(refVal_setCustomerEmail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("discount"))))
    {
        int32_t refVal_setDiscount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("discount"))), refVal_setDiscount );
        setDiscount(refVal_setDiscount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("dueDate"))))
    {
        utility::string_t refVal_setDueDate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("dueDate"))), refVal_setDueDate );
        setDueDate(refVal_setDueDate);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("lineItems"))))
    {
        std::vector<std::shared_ptr<InvoiceLineItem>> refVal_setLineItems;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("lineItems"))), refVal_setLineItems );
        setLineItems(refVal_setLineItems);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("number"))))
    {
        int32_t refVal_setNumber;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("number"))), refVal_setNumber );
        setNumber(refVal_setNumber);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("numberStr"))))
    {
        utility::string_t refVal_setNumberStr;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("numberStr"))), refVal_setNumberStr );
        setNumberStr(refVal_setNumberStr);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("paidAt"))))
    {
        utility::string_t refVal_setPaidAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("paidAt"))), refVal_setPaidAt );
        setPaidAt(refVal_setPaidAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("paymentMethod"))))
    {
        utility::string_t refVal_setPaymentMethod;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("paymentMethod"))), refVal_setPaymentMethod );
        setPaymentMethod(refVal_setPaymentMethod);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("paymentRef"))))
    {
        utility::string_t refVal_setPaymentRef;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("paymentRef"))), refVal_setPaymentRef );
        setPaymentRef(refVal_setPaymentRef);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("periodEnd"))))
    {
        utility::string_t refVal_setPeriodEnd;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("periodEnd"))), refVal_setPeriodEnd );
        setPeriodEnd(refVal_setPeriodEnd);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("periodStart"))))
    {
        utility::string_t refVal_setPeriodStart;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("periodStart"))), refVal_setPeriodStart );
        setPeriodStart(refVal_setPeriodStart);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subscriptionId"))))
    {
        utility::string_t refVal_setSubscriptionId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subscriptionId"))), refVal_setSubscriptionId );
        setSubscriptionId(refVal_setSubscriptionId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subtotal"))))
    {
        int32_t refVal_setSubtotal;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subtotal"))), refVal_setSubtotal );
        setSubtotal(refVal_setSubtotal);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tax"))))
    {
        int32_t refVal_setTax;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tax"))), refVal_setTax );
        setTax(refVal_setTax);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        utility::string_t refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("userId"))))
    {
        utility::string_t refVal_setUserId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("userId"))), refVal_setUserId );
        setUserId(refVal_setUserId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("voidedAt"))))
    {
        utility::string_t refVal_setVoidedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("voidedAt"))), refVal_setVoidedAt );
        setVoidedAt(refVal_setVoidedAt);
    }
    return ok;
}


int32_t BillingInvoice::getAmountDue() const
{
    return m_AmountDue;
}


void BillingInvoice::setAmountDue(int32_t value)
{
    m_AmountDue = value;
    m_AmountDueIsSet = true;
}

bool BillingInvoice::amountDueIsSet() const
{
    return m_AmountDueIsSet;
}

void BillingInvoice::unsetAmountDue()
{
    m_AmountDueIsSet = false;
}
int32_t BillingInvoice::getAmountPaid() const
{
    return m_AmountPaid;
}


void BillingInvoice::setAmountPaid(int32_t value)
{
    m_AmountPaid = value;
    m_AmountPaidIsSet = true;
}

bool BillingInvoice::amountPaidIsSet() const
{
    return m_AmountPaidIsSet;
}

void BillingInvoice::unsetAmountPaid()
{
    m_AmountPaidIsSet = false;
}
int32_t BillingInvoice::getAttemptCount() const
{
    return m_AttemptCount;
}


void BillingInvoice::setAttemptCount(int32_t value)
{
    m_AttemptCount = value;
    m_AttemptCountIsSet = true;
}

bool BillingInvoice::attemptCountIsSet() const
{
    return m_AttemptCountIsSet;
}

void BillingInvoice::unsetAttemptCount()
{
    m_AttemptCountIsSet = false;
}
utility::string_t BillingInvoice::getCreatedAt() const
{
    return m_CreatedAt;
}


void BillingInvoice::setCreatedAt(const utility::string_t& value)
{
    m_CreatedAt = value;
    m_CreatedAtIsSet = true;
}

bool BillingInvoice::createdAtIsSet() const
{
    return m_CreatedAtIsSet;
}

void BillingInvoice::unsetCreatedAt()
{
    m_CreatedAtIsSet = false;
}
int32_t BillingInvoice::getCreditApplied() const
{
    return m_CreditApplied;
}


void BillingInvoice::setCreditApplied(int32_t value)
{
    m_CreditApplied = value;
    m_CreditAppliedIsSet = true;
}

bool BillingInvoice::creditAppliedIsSet() const
{
    return m_CreditAppliedIsSet;
}

void BillingInvoice::unsetCreditApplied()
{
    m_CreditAppliedIsSet = false;
}
utility::string_t BillingInvoice::getCurrency() const
{
    return m_Currency;
}


void BillingInvoice::setCurrency(const utility::string_t& value)
{
    m_Currency = value;
    m_CurrencyIsSet = true;
}

bool BillingInvoice::currencyIsSet() const
{
    return m_CurrencyIsSet;
}

void BillingInvoice::unsetCurrency()
{
    m_CurrencyIsSet = false;
}
utility::string_t BillingInvoice::getCustomerEmail() const
{
    return m_CustomerEmail;
}


void BillingInvoice::setCustomerEmail(const utility::string_t& value)
{
    m_CustomerEmail = value;
    m_CustomerEmailIsSet = true;
}

bool BillingInvoice::customerEmailIsSet() const
{
    return m_CustomerEmailIsSet;
}

void BillingInvoice::unsetCustomerEmail()
{
    m_CustomerEmailIsSet = false;
}
int32_t BillingInvoice::getDiscount() const
{
    return m_Discount;
}


void BillingInvoice::setDiscount(int32_t value)
{
    m_Discount = value;
    m_DiscountIsSet = true;
}

bool BillingInvoice::discountIsSet() const
{
    return m_DiscountIsSet;
}

void BillingInvoice::unsetDiscount()
{
    m_DiscountIsSet = false;
}
utility::string_t BillingInvoice::getDueDate() const
{
    return m_DueDate;
}


void BillingInvoice::setDueDate(const utility::string_t& value)
{
    m_DueDate = value;
    m_DueDateIsSet = true;
}

bool BillingInvoice::dueDateIsSet() const
{
    return m_DueDateIsSet;
}

void BillingInvoice::unsetDueDate()
{
    m_DueDateIsSet = false;
}
utility::string_t BillingInvoice::getId() const
{
    return m_Id;
}


void BillingInvoice::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool BillingInvoice::idIsSet() const
{
    return m_IdIsSet;
}

void BillingInvoice::unsetId()
{
    m_IdIsSet = false;
}
std::vector<std::shared_ptr<InvoiceLineItem>> BillingInvoice::getLineItems() const
{
    return m_LineItems;
}


void BillingInvoice::setLineItems(const std::vector<std::shared_ptr<InvoiceLineItem>>& value)
{
    m_LineItems = value;
    m_LineItemsIsSet = true;
}

bool BillingInvoice::lineItemsIsSet() const
{
    return m_LineItemsIsSet;
}

void BillingInvoice::unsetLineItems()
{
    m_LineItemsIsSet = false;
}
int32_t BillingInvoice::getNumber() const
{
    return m_number;
}


void BillingInvoice::setNumber(int32_t value)
{
    m_number = value;
    m_numberIsSet = true;
}

bool BillingInvoice::numberIsSet() const
{
    return m_numberIsSet;
}

void BillingInvoice::unsetnumber()
{
    m_numberIsSet = false;
}
utility::string_t BillingInvoice::getNumberStr() const
{
    return m_NumberStr;
}


void BillingInvoice::setNumberStr(const utility::string_t& value)
{
    m_NumberStr = value;
    m_NumberStrIsSet = true;
}

bool BillingInvoice::numberStrIsSet() const
{
    return m_NumberStrIsSet;
}

void BillingInvoice::unsetNumberStr()
{
    m_NumberStrIsSet = false;
}
utility::string_t BillingInvoice::getPaidAt() const
{
    return m_PaidAt;
}


void BillingInvoice::setPaidAt(const utility::string_t& value)
{
    m_PaidAt = value;
    m_PaidAtIsSet = true;
}

bool BillingInvoice::paidAtIsSet() const
{
    return m_PaidAtIsSet;
}

void BillingInvoice::unsetPaidAt()
{
    m_PaidAtIsSet = false;
}
utility::string_t BillingInvoice::getPaymentMethod() const
{
    return m_PaymentMethod;
}


void BillingInvoice::setPaymentMethod(const utility::string_t& value)
{
    m_PaymentMethod = value;
    m_PaymentMethodIsSet = true;
}

bool BillingInvoice::paymentMethodIsSet() const
{
    return m_PaymentMethodIsSet;
}

void BillingInvoice::unsetPaymentMethod()
{
    m_PaymentMethodIsSet = false;
}
utility::string_t BillingInvoice::getPaymentRef() const
{
    return m_PaymentRef;
}


void BillingInvoice::setPaymentRef(const utility::string_t& value)
{
    m_PaymentRef = value;
    m_PaymentRefIsSet = true;
}

bool BillingInvoice::paymentRefIsSet() const
{
    return m_PaymentRefIsSet;
}

void BillingInvoice::unsetPaymentRef()
{
    m_PaymentRefIsSet = false;
}
utility::string_t BillingInvoice::getPeriodEnd() const
{
    return m_PeriodEnd;
}


void BillingInvoice::setPeriodEnd(const utility::string_t& value)
{
    m_PeriodEnd = value;
    m_PeriodEndIsSet = true;
}

bool BillingInvoice::periodEndIsSet() const
{
    return m_PeriodEndIsSet;
}

void BillingInvoice::unsetPeriodEnd()
{
    m_PeriodEndIsSet = false;
}
utility::string_t BillingInvoice::getPeriodStart() const
{
    return m_PeriodStart;
}


void BillingInvoice::setPeriodStart(const utility::string_t& value)
{
    m_PeriodStart = value;
    m_PeriodStartIsSet = true;
}

bool BillingInvoice::periodStartIsSet() const
{
    return m_PeriodStartIsSet;
}

void BillingInvoice::unsetPeriodStart()
{
    m_PeriodStartIsSet = false;
}
utility::string_t BillingInvoice::getStatus() const
{
    return m_Status;
}


void BillingInvoice::setStatus(const utility::string_t& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool BillingInvoice::statusIsSet() const
{
    return m_StatusIsSet;
}

void BillingInvoice::unsetStatus()
{
    m_StatusIsSet = false;
}
utility::string_t BillingInvoice::getSubscriptionId() const
{
    return m_SubscriptionId;
}


void BillingInvoice::setSubscriptionId(const utility::string_t& value)
{
    m_SubscriptionId = value;
    m_SubscriptionIdIsSet = true;
}

bool BillingInvoice::subscriptionIdIsSet() const
{
    return m_SubscriptionIdIsSet;
}

void BillingInvoice::unsetSubscriptionId()
{
    m_SubscriptionIdIsSet = false;
}
int32_t BillingInvoice::getSubtotal() const
{
    return m_Subtotal;
}


void BillingInvoice::setSubtotal(int32_t value)
{
    m_Subtotal = value;
    m_SubtotalIsSet = true;
}

bool BillingInvoice::subtotalIsSet() const
{
    return m_SubtotalIsSet;
}

void BillingInvoice::unsetSubtotal()
{
    m_SubtotalIsSet = false;
}
int32_t BillingInvoice::getTax() const
{
    return m_Tax;
}


void BillingInvoice::setTax(int32_t value)
{
    m_Tax = value;
    m_TaxIsSet = true;
}

bool BillingInvoice::taxIsSet() const
{
    return m_TaxIsSet;
}

void BillingInvoice::unsetTax()
{
    m_TaxIsSet = false;
}
utility::string_t BillingInvoice::getUpdatedAt() const
{
    return m_UpdatedAt;
}


void BillingInvoice::setUpdatedAt(const utility::string_t& value)
{
    m_UpdatedAt = value;
    m_UpdatedAtIsSet = true;
}

bool BillingInvoice::updatedAtIsSet() const
{
    return m_UpdatedAtIsSet;
}

void BillingInvoice::unsetUpdatedAt()
{
    m_UpdatedAtIsSet = false;
}
utility::string_t BillingInvoice::getUserId() const
{
    return m_UserId;
}


void BillingInvoice::setUserId(const utility::string_t& value)
{
    m_UserId = value;
    m_UserIdIsSet = true;
}

bool BillingInvoice::userIdIsSet() const
{
    return m_UserIdIsSet;
}

void BillingInvoice::unsetUserId()
{
    m_UserIdIsSet = false;
}
utility::string_t BillingInvoice::getVoidedAt() const
{
    return m_VoidedAt;
}


void BillingInvoice::setVoidedAt(const utility::string_t& value)
{
    m_VoidedAt = value;
    m_VoidedAtIsSet = true;
}

bool BillingInvoice::voidedAtIsSet() const
{
    return m_VoidedAtIsSet;
}

void BillingInvoice::unsetVoidedAt()
{
    m_VoidedAtIsSet = false;
}

}
}


