/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "hanzo/model/Category.h"

namespace hanzo {
namespace model {

Category::Category()
{
    m_BrandsIsSet = false;
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Label = utility::conversions::to_string_t("");
    m_LabelIsSet = false;
    m_Order = 0;
    m_OrderIsSet = false;
    m_Owner = utility::conversions::to_string_t("");
    m_OwnerIsSet = false;
    m_Summary = utility::conversions::to_string_t("");
    m_SummaryIsSet = false;
    m_TaxaIsSet = false;
}

Category::~Category()
{
}

void Category::validate()
{
    // TODO: implement validation
}

web::json::value Category::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_BrandsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("brands"))] = ModelBase::toJson(m_Brands);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_LabelIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("label"))] = ModelBase::toJson(m_Label);
    }
    if(m_OrderIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("order"))] = ModelBase::toJson(m_Order);
    }
    if(m_OwnerIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("owner"))] = ModelBase::toJson(m_Owner);
    }
    if(m_SummaryIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("summary"))] = ModelBase::toJson(m_Summary);
    }
    if(m_TaxaIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("taxa"))] = ModelBase::toJson(m_Taxa);
    }

    return val;
}

bool Category::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("brands"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("brands")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setBrands;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBrands);
            setBrands(refVal_setBrands);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("label"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("label")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLabel;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLabel);
            setLabel(refVal_setLabel);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("order"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("order")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setOrder;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOrder);
            setOrder(refVal_setOrder);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("owner"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("owner")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOwner;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOwner);
            setOwner(refVal_setOwner);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("summary"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("summary")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSummary;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSummary);
            setSummary(refVal_setSummary);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("taxa"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("taxa")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Taxon>> refVal_setTaxa;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTaxa);
            setTaxa(refVal_setTaxa);
            
        }
    }
    return ok;
}

void Category::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_BrandsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("brands")), m_Brands));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_LabelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("label")), m_Label));
    }
    if(m_OrderIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("order")), m_Order));
    }
    if(m_OwnerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("owner")), m_Owner));
    }
    if(m_SummaryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("summary")), m_Summary));
    }
    if(m_TaxaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("taxa")), m_Taxa));
    }
}

bool Category::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("brands"))))
    {
        std::vector<utility::string_t> refVal_setBrands;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("brands"))), refVal_setBrands );
        setBrands(refVal_setBrands);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("label"))))
    {
        utility::string_t refVal_setLabel;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("label"))), refVal_setLabel );
        setLabel(refVal_setLabel);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("order"))))
    {
        int32_t refVal_setOrder;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("order"))), refVal_setOrder );
        setOrder(refVal_setOrder);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("owner"))))
    {
        utility::string_t refVal_setOwner;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("owner"))), refVal_setOwner );
        setOwner(refVal_setOwner);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("summary"))))
    {
        utility::string_t refVal_setSummary;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("summary"))), refVal_setSummary );
        setSummary(refVal_setSummary);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("taxa"))))
    {
        std::vector<std::shared_ptr<Taxon>> refVal_setTaxa;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("taxa"))), refVal_setTaxa );
        setTaxa(refVal_setTaxa);
    }
    return ok;
}


std::vector<utility::string_t> Category::getBrands() const
{
    return m_Brands;
}


void Category::setBrands(const std::vector<utility::string_t>& value)
{
    m_Brands = value;
    m_BrandsIsSet = true;
}

bool Category::brandsIsSet() const
{
    return m_BrandsIsSet;
}

void Category::unsetBrands()
{
    m_BrandsIsSet = false;
}
utility::string_t Category::getId() const
{
    return m_Id;
}


void Category::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Category::idIsSet() const
{
    return m_IdIsSet;
}

void Category::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t Category::getLabel() const
{
    return m_Label;
}


void Category::setLabel(const utility::string_t& value)
{
    m_Label = value;
    m_LabelIsSet = true;
}

bool Category::labelIsSet() const
{
    return m_LabelIsSet;
}

void Category::unsetLabel()
{
    m_LabelIsSet = false;
}
int32_t Category::getOrder() const
{
    return m_Order;
}


void Category::setOrder(int32_t value)
{
    m_Order = value;
    m_OrderIsSet = true;
}

bool Category::orderIsSet() const
{
    return m_OrderIsSet;
}

void Category::unsetOrder()
{
    m_OrderIsSet = false;
}
utility::string_t Category::getOwner() const
{
    return m_Owner;
}


void Category::setOwner(const utility::string_t& value)
{
    m_Owner = value;
    m_OwnerIsSet = true;
}

bool Category::ownerIsSet() const
{
    return m_OwnerIsSet;
}

void Category::unsetOwner()
{
    m_OwnerIsSet = false;
}
utility::string_t Category::getSummary() const
{
    return m_Summary;
}


void Category::setSummary(const utility::string_t& value)
{
    m_Summary = value;
    m_SummaryIsSet = true;
}

bool Category::summaryIsSet() const
{
    return m_SummaryIsSet;
}

void Category::unsetSummary()
{
    m_SummaryIsSet = false;
}
std::vector<std::shared_ptr<Taxon>> Category::getTaxa() const
{
    return m_Taxa;
}


void Category::setTaxa(const std::vector<std::shared_ptr<Taxon>>& value)
{
    m_Taxa = value;
    m_TaxaIsSet = true;
}

bool Category::taxaIsSet() const
{
    return m_TaxaIsSet;
}

void Category::unsetTaxa()
{
    m_TaxaIsSet = false;
}

}
}


