/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "hanzo/model/Cloud_DestinationField.h"

namespace hanzo {
namespace model {

Cloud_DestinationField::Cloud_DestinationField()
{
    m_Example = utility::conversions::to_string_t("");
    m_ExampleIsSet = false;
    m_Key = utility::conversions::to_string_t("");
    m_KeyIsSet = false;
    m_Label = utility::conversions::to_string_t("");
    m_LabelIsSet = false;
    m_Required = false;
    m_RequiredIsSet = false;
}

Cloud_DestinationField::~Cloud_DestinationField()
{
}

void Cloud_DestinationField::validate()
{
    // TODO: implement validation
}

web::json::value Cloud_DestinationField::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ExampleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("example"))] = ModelBase::toJson(m_Example);
    }
    if(m_KeyIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("key"))] = ModelBase::toJson(m_Key);
    }
    if(m_LabelIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("label"))] = ModelBase::toJson(m_Label);
    }
    if(m_RequiredIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("required"))] = ModelBase::toJson(m_Required);
    }

    return val;
}

bool Cloud_DestinationField::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("example"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("example")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setExample;
            ok &= ModelBase::fromJson(fieldValue, refVal_setExample);
            setExample(refVal_setExample);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("key"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("key")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setKey;
            ok &= ModelBase::fromJson(fieldValue, refVal_setKey);
            setKey(refVal_setKey);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("label"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("label")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLabel;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLabel);
            setLabel(refVal_setLabel);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("required"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("required")));
        if(!fieldValue.is_null())
        {
            bool refVal_setRequired;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRequired);
            setRequired(refVal_setRequired);
            
        }
    }
    return ok;
}

void Cloud_DestinationField::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ExampleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("example")), m_Example));
    }
    if(m_KeyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("key")), m_Key));
    }
    if(m_LabelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("label")), m_Label));
    }
    if(m_RequiredIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("required")), m_Required));
    }
}

bool Cloud_DestinationField::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("example"))))
    {
        utility::string_t refVal_setExample;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("example"))), refVal_setExample );
        setExample(refVal_setExample);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("key"))))
    {
        utility::string_t refVal_setKey;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("key"))), refVal_setKey );
        setKey(refVal_setKey);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("label"))))
    {
        utility::string_t refVal_setLabel;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("label"))), refVal_setLabel );
        setLabel(refVal_setLabel);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("required"))))
    {
        bool refVal_setRequired;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("required"))), refVal_setRequired );
        setRequired(refVal_setRequired);
    }
    return ok;
}


utility::string_t Cloud_DestinationField::getExample() const
{
    return m_Example;
}


void Cloud_DestinationField::setExample(const utility::string_t& value)
{
    m_Example = value;
    m_ExampleIsSet = true;
}

bool Cloud_DestinationField::exampleIsSet() const
{
    return m_ExampleIsSet;
}

void Cloud_DestinationField::unsetExample()
{
    m_ExampleIsSet = false;
}
utility::string_t Cloud_DestinationField::getKey() const
{
    return m_Key;
}


void Cloud_DestinationField::setKey(const utility::string_t& value)
{
    m_Key = value;
    m_KeyIsSet = true;
}

bool Cloud_DestinationField::keyIsSet() const
{
    return m_KeyIsSet;
}

void Cloud_DestinationField::unsetKey()
{
    m_KeyIsSet = false;
}
utility::string_t Cloud_DestinationField::getLabel() const
{
    return m_Label;
}


void Cloud_DestinationField::setLabel(const utility::string_t& value)
{
    m_Label = value;
    m_LabelIsSet = true;
}

bool Cloud_DestinationField::labelIsSet() const
{
    return m_LabelIsSet;
}

void Cloud_DestinationField::unsetLabel()
{
    m_LabelIsSet = false;
}
bool Cloud_DestinationField::isRequired() const
{
    return m_Required;
}


void Cloud_DestinationField::setRequired(bool value)
{
    m_Required = value;
    m_RequiredIsSet = true;
}

bool Cloud_DestinationField::requiredIsSet() const
{
    return m_RequiredIsSet;
}

void Cloud_DestinationField::unsetRequired()
{
    m_RequiredIsSet = false;
}

}
}


