/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "hanzo/model/Cloud_pushEvent_repository.h"

namespace hanzo {
namespace model {

Cloud_pushEvent_repository::Cloud_pushEvent_repository()
{
    m_Clone_url = utility::conversions::to_string_t("");
    m_Clone_urlIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_OwnerIsSet = false;
}

Cloud_pushEvent_repository::~Cloud_pushEvent_repository()
{
}

void Cloud_pushEvent_repository::validate()
{
    // TODO: implement validation
}

web::json::value Cloud_pushEvent_repository::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Clone_urlIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("clone_url"))] = ModelBase::toJson(m_Clone_url);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_OwnerIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("owner"))] = ModelBase::toJson(m_Owner);
    }

    return val;
}

bool Cloud_pushEvent_repository::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("clone_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("clone_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCloneUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCloneUrl);
            setCloneUrl(refVal_setCloneUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("owner"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("owner")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Cloud_pushEvent_pusher> refVal_setOwner;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOwner);
            setOwner(refVal_setOwner);
            
        }
    }
    return ok;
}

void Cloud_pushEvent_repository::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Clone_urlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("clone_url")), m_Clone_url));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_OwnerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("owner")), m_Owner));
    }
}

bool Cloud_pushEvent_repository::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("clone_url"))))
    {
        utility::string_t refVal_setCloneUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("clone_url"))), refVal_setCloneUrl );
        setCloneUrl(refVal_setCloneUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("owner"))))
    {
        std::shared_ptr<Cloud_pushEvent_pusher> refVal_setOwner;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("owner"))), refVal_setOwner );
        setOwner(refVal_setOwner);
    }
    return ok;
}


utility::string_t Cloud_pushEvent_repository::getCloneUrl() const
{
    return m_Clone_url;
}


void Cloud_pushEvent_repository::setCloneUrl(const utility::string_t& value)
{
    m_Clone_url = value;
    m_Clone_urlIsSet = true;
}

bool Cloud_pushEvent_repository::cloneUrlIsSet() const
{
    return m_Clone_urlIsSet;
}

void Cloud_pushEvent_repository::unsetClone_url()
{
    m_Clone_urlIsSet = false;
}
utility::string_t Cloud_pushEvent_repository::getName() const
{
    return m_Name;
}


void Cloud_pushEvent_repository::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool Cloud_pushEvent_repository::nameIsSet() const
{
    return m_NameIsSet;
}

void Cloud_pushEvent_repository::unsetName()
{
    m_NameIsSet = false;
}
std::shared_ptr<Cloud_pushEvent_pusher> Cloud_pushEvent_repository::getOwner() const
{
    return m_Owner;
}


void Cloud_pushEvent_repository::setOwner(const std::shared_ptr<Cloud_pushEvent_pusher>& value)
{
    m_Owner = value;
    m_OwnerIsSet = true;
}

bool Cloud_pushEvent_repository::ownerIsSet() const
{
    return m_OwnerIsSet;
}

void Cloud_pushEvent_repository::unsetOwner()
{
    m_OwnerIsSet = false;
}

}
}


