/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "hanzo/model/Cloud_fleetUnit.h"

namespace hanzo {
namespace model {

Cloud_fleetUnit::Cloud_fleetUnit()
{
    m_Host = utility::conversions::to_string_t("");
    m_HostIsSet = false;
    m_Kind = utility::conversions::to_string_t("");
    m_KindIsSet = false;
    m_Label = utility::conversions::to_string_t("");
    m_LabelIsSet = false;
    m_MetricsIsSet = false;
    m_Queued = 0;
    m_QueuedIsSet = false;
    m_Running = 0;
    m_RunningIsSet = false;
    m_Sessions = 0;
    m_SessionsIsSet = false;
    m_Source = utility::conversions::to_string_t("");
    m_SourceIsSet = false;
    m_SpecIsSet = false;
    m_Status = utility::conversions::to_string_t("");
    m_StatusIsSet = false;
    m_Unit = utility::conversions::to_string_t("");
    m_UnitIsSet = false;
}

Cloud_fleetUnit::~Cloud_fleetUnit()
{
}

void Cloud_fleetUnit::validate()
{
    // TODO: implement validation
}

web::json::value Cloud_fleetUnit::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_HostIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("host"))] = ModelBase::toJson(m_Host);
    }
    if(m_KindIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("kind"))] = ModelBase::toJson(m_Kind);
    }
    if(m_LabelIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("label"))] = ModelBase::toJson(m_Label);
    }
    if(m_MetricsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("metrics"))] = ModelBase::toJson(m_Metrics);
    }
    if(m_QueuedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("queued"))] = ModelBase::toJson(m_Queued);
    }
    if(m_RunningIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("running"))] = ModelBase::toJson(m_Running);
    }
    if(m_SessionsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("sessions"))] = ModelBase::toJson(m_Sessions);
    }
    if(m_SourceIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("source"))] = ModelBase::toJson(m_Source);
    }
    if(m_SpecIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("spec"))] = ModelBase::toJson(m_Spec);
    }
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_UnitIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("unit"))] = ModelBase::toJson(m_Unit);
    }

    return val;
}

bool Cloud_fleetUnit::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("host"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("host")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setHost;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHost);
            setHost(refVal_setHost);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("kind"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("kind")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setKind;
            ok &= ModelBase::fromJson(fieldValue, refVal_setKind);
            setKind(refVal_setKind);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("label"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("label")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLabel;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLabel);
            setLabel(refVal_setLabel);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("metrics"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("metrics")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Cloud_fleetMetrics> refVal_setMetrics;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMetrics);
            setMetrics(refVal_setMetrics);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("queued"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("queued")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setQueued;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQueued);
            setQueued(refVal_setQueued);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("running"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("running")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setRunning;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRunning);
            setRunning(refVal_setRunning);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("sessions"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("sessions")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setSessions;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSessions);
            setSessions(refVal_setSessions);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("source"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("source")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSource;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSource);
            setSource(refVal_setSource);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("spec"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("spec")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Cloud_fleetSpec> refVal_setSpec;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSpec);
            setSpec(refVal_setSpec);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("unit"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("unit")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUnit;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUnit);
            setUnit(refVal_setUnit);
            
        }
    }
    return ok;
}

void Cloud_fleetUnit::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_HostIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("host")), m_Host));
    }
    if(m_KindIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("kind")), m_Kind));
    }
    if(m_LabelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("label")), m_Label));
    }
    if(m_MetricsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("metrics")), m_Metrics));
    }
    if(m_QueuedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("queued")), m_Queued));
    }
    if(m_RunningIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("running")), m_Running));
    }
    if(m_SessionsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("sessions")), m_Sessions));
    }
    if(m_SourceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("source")), m_Source));
    }
    if(m_SpecIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("spec")), m_Spec));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_UnitIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("unit")), m_Unit));
    }
}

bool Cloud_fleetUnit::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("host"))))
    {
        utility::string_t refVal_setHost;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("host"))), refVal_setHost );
        setHost(refVal_setHost);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("kind"))))
    {
        utility::string_t refVal_setKind;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("kind"))), refVal_setKind );
        setKind(refVal_setKind);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("label"))))
    {
        utility::string_t refVal_setLabel;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("label"))), refVal_setLabel );
        setLabel(refVal_setLabel);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("metrics"))))
    {
        std::shared_ptr<Cloud_fleetMetrics> refVal_setMetrics;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("metrics"))), refVal_setMetrics );
        setMetrics(refVal_setMetrics);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("queued"))))
    {
        int32_t refVal_setQueued;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("queued"))), refVal_setQueued );
        setQueued(refVal_setQueued);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("running"))))
    {
        int32_t refVal_setRunning;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("running"))), refVal_setRunning );
        setRunning(refVal_setRunning);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("sessions"))))
    {
        int32_t refVal_setSessions;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("sessions"))), refVal_setSessions );
        setSessions(refVal_setSessions);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("source"))))
    {
        utility::string_t refVal_setSource;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("source"))), refVal_setSource );
        setSource(refVal_setSource);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("spec"))))
    {
        std::shared_ptr<Cloud_fleetSpec> refVal_setSpec;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("spec"))), refVal_setSpec );
        setSpec(refVal_setSpec);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("unit"))))
    {
        utility::string_t refVal_setUnit;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("unit"))), refVal_setUnit );
        setUnit(refVal_setUnit);
    }
    return ok;
}


utility::string_t Cloud_fleetUnit::getHost() const
{
    return m_Host;
}


void Cloud_fleetUnit::setHost(const utility::string_t& value)
{
    m_Host = value;
    m_HostIsSet = true;
}

bool Cloud_fleetUnit::hostIsSet() const
{
    return m_HostIsSet;
}

void Cloud_fleetUnit::unsetHost()
{
    m_HostIsSet = false;
}
utility::string_t Cloud_fleetUnit::getKind() const
{
    return m_Kind;
}


void Cloud_fleetUnit::setKind(const utility::string_t& value)
{
    m_Kind = value;
    m_KindIsSet = true;
}

bool Cloud_fleetUnit::kindIsSet() const
{
    return m_KindIsSet;
}

void Cloud_fleetUnit::unsetKind()
{
    m_KindIsSet = false;
}
utility::string_t Cloud_fleetUnit::getLabel() const
{
    return m_Label;
}


void Cloud_fleetUnit::setLabel(const utility::string_t& value)
{
    m_Label = value;
    m_LabelIsSet = true;
}

bool Cloud_fleetUnit::labelIsSet() const
{
    return m_LabelIsSet;
}

void Cloud_fleetUnit::unsetLabel()
{
    m_LabelIsSet = false;
}
std::shared_ptr<Cloud_fleetMetrics> Cloud_fleetUnit::getMetrics() const
{
    return m_Metrics;
}


void Cloud_fleetUnit::setMetrics(const std::shared_ptr<Cloud_fleetMetrics>& value)
{
    m_Metrics = value;
    m_MetricsIsSet = true;
}

bool Cloud_fleetUnit::metricsIsSet() const
{
    return m_MetricsIsSet;
}

void Cloud_fleetUnit::unsetMetrics()
{
    m_MetricsIsSet = false;
}
int32_t Cloud_fleetUnit::getQueued() const
{
    return m_Queued;
}


void Cloud_fleetUnit::setQueued(int32_t value)
{
    m_Queued = value;
    m_QueuedIsSet = true;
}

bool Cloud_fleetUnit::queuedIsSet() const
{
    return m_QueuedIsSet;
}

void Cloud_fleetUnit::unsetQueued()
{
    m_QueuedIsSet = false;
}
int32_t Cloud_fleetUnit::getRunning() const
{
    return m_Running;
}


void Cloud_fleetUnit::setRunning(int32_t value)
{
    m_Running = value;
    m_RunningIsSet = true;
}

bool Cloud_fleetUnit::runningIsSet() const
{
    return m_RunningIsSet;
}

void Cloud_fleetUnit::unsetRunning()
{
    m_RunningIsSet = false;
}
int32_t Cloud_fleetUnit::getSessions() const
{
    return m_Sessions;
}


void Cloud_fleetUnit::setSessions(int32_t value)
{
    m_Sessions = value;
    m_SessionsIsSet = true;
}

bool Cloud_fleetUnit::sessionsIsSet() const
{
    return m_SessionsIsSet;
}

void Cloud_fleetUnit::unsetSessions()
{
    m_SessionsIsSet = false;
}
utility::string_t Cloud_fleetUnit::getSource() const
{
    return m_Source;
}


void Cloud_fleetUnit::setSource(const utility::string_t& value)
{
    m_Source = value;
    m_SourceIsSet = true;
}

bool Cloud_fleetUnit::sourceIsSet() const
{
    return m_SourceIsSet;
}

void Cloud_fleetUnit::unsetSource()
{
    m_SourceIsSet = false;
}
std::shared_ptr<Cloud_fleetSpec> Cloud_fleetUnit::getSpec() const
{
    return m_Spec;
}


void Cloud_fleetUnit::setSpec(const std::shared_ptr<Cloud_fleetSpec>& value)
{
    m_Spec = value;
    m_SpecIsSet = true;
}

bool Cloud_fleetUnit::specIsSet() const
{
    return m_SpecIsSet;
}

void Cloud_fleetUnit::unsetSpec()
{
    m_SpecIsSet = false;
}
utility::string_t Cloud_fleetUnit::getStatus() const
{
    return m_Status;
}


void Cloud_fleetUnit::setStatus(const utility::string_t& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool Cloud_fleetUnit::statusIsSet() const
{
    return m_StatusIsSet;
}

void Cloud_fleetUnit::unsetStatus()
{
    m_StatusIsSet = false;
}
utility::string_t Cloud_fleetUnit::getUnit() const
{
    return m_Unit;
}


void Cloud_fleetUnit::setUnit(const utility::string_t& value)
{
    m_Unit = value;
    m_UnitIsSet = true;
}

bool Cloud_fleetUnit::unitIsSet() const
{
    return m_UnitIsSet;
}

void Cloud_fleetUnit::unsetUnit()
{
    m_UnitIsSet = false;
}

}
}


