/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "hanzo/model/Cloud_get_v1_functions_200_response.h"

namespace hanzo {
namespace model {

Cloud_get_v1_functions_200_response::Cloud_get_v1_functions_200_response()
{
    m_FunctionsIsSet = false;
}

Cloud_get_v1_functions_200_response::~Cloud_get_v1_functions_200_response()
{
}

void Cloud_get_v1_functions_200_response::validate()
{
    // TODO: implement validation
}

web::json::value Cloud_get_v1_functions_200_response::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_FunctionsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("functions"))] = ModelBase::toJson(m_Functions);
    }

    return val;
}

bool Cloud_get_v1_functions_200_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("functions"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("functions")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Functions_Function>> refVal_setFunctions;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFunctions);
            setFunctions(refVal_setFunctions);
            
        }
    }
    return ok;
}

void Cloud_get_v1_functions_200_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_FunctionsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("functions")), m_Functions));
    }
}

bool Cloud_get_v1_functions_200_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("functions"))))
    {
        std::vector<std::shared_ptr<Functions_Function>> refVal_setFunctions;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("functions"))), refVal_setFunctions );
        setFunctions(refVal_setFunctions);
    }
    return ok;
}


std::vector<std::shared_ptr<Functions_Function>> Cloud_get_v1_functions_200_response::getFunctions() const
{
    return m_Functions;
}


void Cloud_get_v1_functions_200_response::setFunctions(const std::vector<std::shared_ptr<Functions_Function>>& value)
{
    m_Functions = value;
    m_FunctionsIsSet = true;
}

bool Cloud_get_v1_functions_200_response::functionsIsSet() const
{
    return m_FunctionsIsSet;
}

void Cloud_get_v1_functions_200_response::unsetFunctions()
{
    m_FunctionsIsSet = false;
}

}
}


