/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "hanzo/model/Cloud_Top.h"

namespace hanzo {
namespace model {

Cloud_Top::Cloud_Top()
{
    m_End = utility::conversions::to_string_t("");
    m_EndIsSet = false;
    m_ModelsIsSet = false;
    m_ProductsIsSet = false;
    m_Range = utility::conversions::to_string_t("");
    m_RangeIsSet = false;
    m_ScopeIsSet = false;
    m_Start = utility::conversions::to_string_t("");
    m_StartIsSet = false;
    m_TopPagesIsSet = false;
    m_TopReferrersIsSet = false;
    m_TopSourcesIsSet = false;
}

Cloud_Top::~Cloud_Top()
{
}

void Cloud_Top::validate()
{
    // TODO: implement validation
}

web::json::value Cloud_Top::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_EndIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("end"))] = ModelBase::toJson(m_End);
    }
    if(m_ModelsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("models"))] = ModelBase::toJson(m_Models);
    }
    if(m_ProductsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("products"))] = ModelBase::toJson(m_Products);
    }
    if(m_RangeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("range"))] = ModelBase::toJson(m_Range);
    }
    if(m_ScopeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("scope"))] = ModelBase::toJson(m_Scope);
    }
    if(m_StartIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("start"))] = ModelBase::toJson(m_Start);
    }
    if(m_TopPagesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("topPages"))] = ModelBase::toJson(m_TopPages);
    }
    if(m_TopReferrersIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("topReferrers"))] = ModelBase::toJson(m_TopReferrers);
    }
    if(m_TopSourcesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("topSources"))] = ModelBase::toJson(m_TopSources);
    }

    return val;
}

bool Cloud_Top::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("end"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("end")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEnd;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEnd);
            setEnd(refVal_setEnd);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("models"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("models")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Cloud_TopModels> refVal_setModels;
            ok &= ModelBase::fromJson(fieldValue, refVal_setModels);
            setModels(refVal_setModels);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("products"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("products")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Cloud_TopProducts> refVal_setProducts;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProducts);
            setProducts(refVal_setProducts);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("range"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("range")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRange;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRange);
            setRange(refVal_setRange);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("scope"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("scope")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Cloud_Scope> refVal_setScope;
            ok &= ModelBase::fromJson(fieldValue, refVal_setScope);
            setScope(refVal_setScope);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("start"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("start")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStart;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStart);
            setStart(refVal_setStart);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("topPages"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("topPages")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Cloud_Breakdown> refVal_setTopPages;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTopPages);
            setTopPages(refVal_setTopPages);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("topReferrers"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("topReferrers")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Cloud_Breakdown> refVal_setTopReferrers;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTopReferrers);
            setTopReferrers(refVal_setTopReferrers);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("topSources"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("topSources")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Cloud_Breakdown> refVal_setTopSources;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTopSources);
            setTopSources(refVal_setTopSources);
            
        }
    }
    return ok;
}

void Cloud_Top::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_EndIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("end")), m_End));
    }
    if(m_ModelsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("models")), m_Models));
    }
    if(m_ProductsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("products")), m_Products));
    }
    if(m_RangeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("range")), m_Range));
    }
    if(m_ScopeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("scope")), m_Scope));
    }
    if(m_StartIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("start")), m_Start));
    }
    if(m_TopPagesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("topPages")), m_TopPages));
    }
    if(m_TopReferrersIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("topReferrers")), m_TopReferrers));
    }
    if(m_TopSourcesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("topSources")), m_TopSources));
    }
}

bool Cloud_Top::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("end"))))
    {
        utility::string_t refVal_setEnd;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("end"))), refVal_setEnd );
        setEnd(refVal_setEnd);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("models"))))
    {
        std::shared_ptr<Cloud_TopModels> refVal_setModels;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("models"))), refVal_setModels );
        setModels(refVal_setModels);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("products"))))
    {
        std::shared_ptr<Cloud_TopProducts> refVal_setProducts;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("products"))), refVal_setProducts );
        setProducts(refVal_setProducts);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("range"))))
    {
        utility::string_t refVal_setRange;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("range"))), refVal_setRange );
        setRange(refVal_setRange);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("scope"))))
    {
        std::shared_ptr<Cloud_Scope> refVal_setScope;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("scope"))), refVal_setScope );
        setScope(refVal_setScope);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("start"))))
    {
        utility::string_t refVal_setStart;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("start"))), refVal_setStart );
        setStart(refVal_setStart);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("topPages"))))
    {
        std::shared_ptr<Cloud_Breakdown> refVal_setTopPages;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("topPages"))), refVal_setTopPages );
        setTopPages(refVal_setTopPages);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("topReferrers"))))
    {
        std::shared_ptr<Cloud_Breakdown> refVal_setTopReferrers;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("topReferrers"))), refVal_setTopReferrers );
        setTopReferrers(refVal_setTopReferrers);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("topSources"))))
    {
        std::shared_ptr<Cloud_Breakdown> refVal_setTopSources;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("topSources"))), refVal_setTopSources );
        setTopSources(refVal_setTopSources);
    }
    return ok;
}


utility::string_t Cloud_Top::getEnd() const
{
    return m_End;
}


void Cloud_Top::setEnd(const utility::string_t& value)
{
    m_End = value;
    m_EndIsSet = true;
}

bool Cloud_Top::endIsSet() const
{
    return m_EndIsSet;
}

void Cloud_Top::unsetEnd()
{
    m_EndIsSet = false;
}
std::shared_ptr<Cloud_TopModels> Cloud_Top::getModels() const
{
    return m_Models;
}


void Cloud_Top::setModels(const std::shared_ptr<Cloud_TopModels>& value)
{
    m_Models = value;
    m_ModelsIsSet = true;
}

bool Cloud_Top::modelsIsSet() const
{
    return m_ModelsIsSet;
}

void Cloud_Top::unsetModels()
{
    m_ModelsIsSet = false;
}
std::shared_ptr<Cloud_TopProducts> Cloud_Top::getProducts() const
{
    return m_Products;
}


void Cloud_Top::setProducts(const std::shared_ptr<Cloud_TopProducts>& value)
{
    m_Products = value;
    m_ProductsIsSet = true;
}

bool Cloud_Top::productsIsSet() const
{
    return m_ProductsIsSet;
}

void Cloud_Top::unsetProducts()
{
    m_ProductsIsSet = false;
}
utility::string_t Cloud_Top::getRange() const
{
    return m_Range;
}


void Cloud_Top::setRange(const utility::string_t& value)
{
    m_Range = value;
    m_RangeIsSet = true;
}

bool Cloud_Top::rangeIsSet() const
{
    return m_RangeIsSet;
}

void Cloud_Top::unsetRange()
{
    m_RangeIsSet = false;
}
std::shared_ptr<Cloud_Scope> Cloud_Top::getScope() const
{
    return m_Scope;
}


void Cloud_Top::setScope(const std::shared_ptr<Cloud_Scope>& value)
{
    m_Scope = value;
    m_ScopeIsSet = true;
}

bool Cloud_Top::scopeIsSet() const
{
    return m_ScopeIsSet;
}

void Cloud_Top::unsetScope()
{
    m_ScopeIsSet = false;
}
utility::string_t Cloud_Top::getStart() const
{
    return m_Start;
}


void Cloud_Top::setStart(const utility::string_t& value)
{
    m_Start = value;
    m_StartIsSet = true;
}

bool Cloud_Top::startIsSet() const
{
    return m_StartIsSet;
}

void Cloud_Top::unsetStart()
{
    m_StartIsSet = false;
}
std::shared_ptr<Cloud_Breakdown> Cloud_Top::getTopPages() const
{
    return m_TopPages;
}


void Cloud_Top::setTopPages(const std::shared_ptr<Cloud_Breakdown>& value)
{
    m_TopPages = value;
    m_TopPagesIsSet = true;
}

bool Cloud_Top::topPagesIsSet() const
{
    return m_TopPagesIsSet;
}

void Cloud_Top::unsetTopPages()
{
    m_TopPagesIsSet = false;
}
std::shared_ptr<Cloud_Breakdown> Cloud_Top::getTopReferrers() const
{
    return m_TopReferrers;
}


void Cloud_Top::setTopReferrers(const std::shared_ptr<Cloud_Breakdown>& value)
{
    m_TopReferrers = value;
    m_TopReferrersIsSet = true;
}

bool Cloud_Top::topReferrersIsSet() const
{
    return m_TopReferrersIsSet;
}

void Cloud_Top::unsetTopReferrers()
{
    m_TopReferrersIsSet = false;
}
std::shared_ptr<Cloud_Breakdown> Cloud_Top::getTopSources() const
{
    return m_TopSources;
}


void Cloud_Top::setTopSources(const std::shared_ptr<Cloud_Breakdown>& value)
{
    m_TopSources = value;
    m_TopSourcesIsSet = true;
}

bool Cloud_Top::topSourcesIsSet() const
{
    return m_TopSourcesIsSet;
}

void Cloud_Top::unsetTopSources()
{
    m_TopSourcesIsSet = false;
}

}
}


