/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "hanzo/model/Cloud_apiKeyList.h"

namespace hanzo {
namespace model {

Cloud_apiKeyList::Cloud_apiKeyList()
{
    m_KeysIsSet = false;
}

Cloud_apiKeyList::~Cloud_apiKeyList()
{
}

void Cloud_apiKeyList::validate()
{
    // TODO: implement validation
}

web::json::value Cloud_apiKeyList::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_KeysIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("keys"))] = ModelBase::toJson(m_Keys);
    }

    return val;
}

bool Cloud_apiKeyList::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("keys"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("keys")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Cloud_apiKey>> refVal_setKeys;
            ok &= ModelBase::fromJson(fieldValue, refVal_setKeys);
            setKeys(refVal_setKeys);
            
        }
    }
    return ok;
}

void Cloud_apiKeyList::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_KeysIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("keys")), m_Keys));
    }
}

bool Cloud_apiKeyList::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("keys"))))
    {
        std::vector<std::shared_ptr<Cloud_apiKey>> refVal_setKeys;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("keys"))), refVal_setKeys );
        setKeys(refVal_setKeys);
    }
    return ok;
}


std::vector<std::shared_ptr<Cloud_apiKey>> Cloud_apiKeyList::getKeys() const
{
    return m_Keys;
}


void Cloud_apiKeyList::setKeys(const std::vector<std::shared_ptr<Cloud_apiKey>>& value)
{
    m_Keys = value;
    m_KeysIsSet = true;
}

bool Cloud_apiKeyList::keysIsSet() const
{
    return m_KeysIsSet;
}

void Cloud_apiKeyList::unsetKeys()
{
    m_KeysIsSet = false;
}

}
}


