/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "hanzo/model/Cloud_populatedFlow.h"

namespace hanzo {
namespace model {

Cloud_populatedFlow::Cloud_populatedFlow()
{
    m_Created = 0;
    m_CreatedIsSet = false;
    m_ExternalId = utility::conversions::to_string_t("");
    m_ExternalIdIsSet = false;
    m_FolderId = utility::conversions::to_string_t("");
    m_FolderIdIsSet = false;
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_ProjectId = utility::conversions::to_string_t("");
    m_ProjectIdIsSet = false;
    m_PublishedVersionId = utility::conversions::to_string_t("");
    m_PublishedVersionIdIsSet = false;
    m_Status = utility::conversions::to_string_t("");
    m_StatusIsSet = false;
    m_Updated = 0;
    m_UpdatedIsSet = false;
    m_VersionIsSet = false;
}

Cloud_populatedFlow::~Cloud_populatedFlow()
{
}

void Cloud_populatedFlow::validate()
{
    // TODO: implement validation
}

web::json::value Cloud_populatedFlow::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_CreatedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("created"))] = ModelBase::toJson(m_Created);
    }
    if(m_ExternalIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("externalId"))] = ModelBase::toJson(m_ExternalId);
    }
    if(m_FolderIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("folderId"))] = ModelBase::toJson(m_FolderId);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_Metadata.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("metadata"))] = ModelBase::toJson(m_Metadata.get());
    }
    if(m_ProjectIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("projectId"))] = ModelBase::toJson(m_ProjectId);
    }
    if(m_PublishedVersionIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("publishedVersionId"))] = ModelBase::toJson(m_PublishedVersionId);
    }
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_UpdatedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updated"))] = ModelBase::toJson(m_Updated);
    }
    if(m_VersionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("version"))] = ModelBase::toJson(m_Version);
    }

    return val;
}

bool Cloud_populatedFlow::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("created"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("created")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setCreated;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreated);
            setCreated(refVal_setCreated);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("externalId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("externalId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setExternalId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setExternalId);
            setExternalId(refVal_setExternalId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("folderId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("folderId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFolderId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFolderId);
            setFolderId(refVal_setFolderId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("metadata"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("metadata")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AnyType> refVal_setMetadata;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMetadata);
            setMetadata(refVal_setMetadata);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("projectId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("projectId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProjectId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProjectId);
            setProjectId(refVal_setProjectId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("publishedVersionId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("publishedVersionId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPublishedVersionId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPublishedVersionId);
            setPublishedVersionId(refVal_setPublishedVersionId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updated"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updated")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setUpdated;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdated);
            setUpdated(refVal_setUpdated);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("version"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("version")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Cloud_FlowVersion> refVal_setVersion;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVersion);
            setVersion(refVal_setVersion);
            
        }
    }
    return ok;
}

void Cloud_populatedFlow::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_CreatedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("created")), m_Created));
    }
    if(m_ExternalIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("externalId")), m_ExternalId));
    }
    if(m_FolderIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("folderId")), m_FolderId));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_Metadata.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("metadata")), m_Metadata.get()));
    }
    if(m_ProjectIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("projectId")), m_ProjectId));
    }
    if(m_PublishedVersionIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("publishedVersionId")), m_PublishedVersionId));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_UpdatedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updated")), m_Updated));
    }
    if(m_VersionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("version")), m_Version));
    }
}

bool Cloud_populatedFlow::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("created"))))
    {
        int32_t refVal_setCreated;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("created"))), refVal_setCreated );
        setCreated(refVal_setCreated);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("externalId"))))
    {
        utility::string_t refVal_setExternalId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("externalId"))), refVal_setExternalId );
        setExternalId(refVal_setExternalId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("folderId"))))
    {
        utility::string_t refVal_setFolderId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("folderId"))), refVal_setFolderId );
        setFolderId(refVal_setFolderId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("metadata"))))
    {
        std::shared_ptr<AnyType> refVal_setMetadata;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("metadata"))), refVal_setMetadata );
        setMetadata(refVal_setMetadata);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("projectId"))))
    {
        utility::string_t refVal_setProjectId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("projectId"))), refVal_setProjectId );
        setProjectId(refVal_setProjectId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("publishedVersionId"))))
    {
        utility::string_t refVal_setPublishedVersionId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("publishedVersionId"))), refVal_setPublishedVersionId );
        setPublishedVersionId(refVal_setPublishedVersionId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updated"))))
    {
        int32_t refVal_setUpdated;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updated"))), refVal_setUpdated );
        setUpdated(refVal_setUpdated);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("version"))))
    {
        std::shared_ptr<Cloud_FlowVersion> refVal_setVersion;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("version"))), refVal_setVersion );
        setVersion(refVal_setVersion);
    }
    return ok;
}


int32_t Cloud_populatedFlow::getCreated() const
{
    return m_Created;
}


void Cloud_populatedFlow::setCreated(int32_t value)
{
    m_Created = value;
    m_CreatedIsSet = true;
}

bool Cloud_populatedFlow::createdIsSet() const
{
    return m_CreatedIsSet;
}

void Cloud_populatedFlow::unsetCreated()
{
    m_CreatedIsSet = false;
}
utility::string_t Cloud_populatedFlow::getExternalId() const
{
    return m_ExternalId;
}


void Cloud_populatedFlow::setExternalId(const utility::string_t& value)
{
    m_ExternalId = value;
    m_ExternalIdIsSet = true;
}

bool Cloud_populatedFlow::externalIdIsSet() const
{
    return m_ExternalIdIsSet;
}

void Cloud_populatedFlow::unsetExternalId()
{
    m_ExternalIdIsSet = false;
}
utility::string_t Cloud_populatedFlow::getFolderId() const
{
    return m_FolderId;
}


void Cloud_populatedFlow::setFolderId(const utility::string_t& value)
{
    m_FolderId = value;
    m_FolderIdIsSet = true;
}

bool Cloud_populatedFlow::folderIdIsSet() const
{
    return m_FolderIdIsSet;
}

void Cloud_populatedFlow::unsetFolderId()
{
    m_FolderIdIsSet = false;
}
utility::string_t Cloud_populatedFlow::getId() const
{
    return m_Id;
}


void Cloud_populatedFlow::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Cloud_populatedFlow::idIsSet() const
{
    return m_IdIsSet;
}

void Cloud_populatedFlow::unsetId()
{
    m_IdIsSet = false;
}
std::shared_ptr<AnyType> Cloud_populatedFlow::getMetadata() const
{
    return m_Metadata.get();
}


void Cloud_populatedFlow::setMetadata(const std::shared_ptr<AnyType>& value)
{
    m_Metadata = value;
}

bool Cloud_populatedFlow::metadataIsSet() const
{
    return m_Metadata.has_value();
}

void Cloud_populatedFlow::unsetMetadata()
{
    m_Metadata.reset();
}
utility::string_t Cloud_populatedFlow::getProjectId() const
{
    return m_ProjectId;
}


void Cloud_populatedFlow::setProjectId(const utility::string_t& value)
{
    m_ProjectId = value;
    m_ProjectIdIsSet = true;
}

bool Cloud_populatedFlow::projectIdIsSet() const
{
    return m_ProjectIdIsSet;
}

void Cloud_populatedFlow::unsetProjectId()
{
    m_ProjectIdIsSet = false;
}
utility::string_t Cloud_populatedFlow::getPublishedVersionId() const
{
    return m_PublishedVersionId;
}


void Cloud_populatedFlow::setPublishedVersionId(const utility::string_t& value)
{
    m_PublishedVersionId = value;
    m_PublishedVersionIdIsSet = true;
}

bool Cloud_populatedFlow::publishedVersionIdIsSet() const
{
    return m_PublishedVersionIdIsSet;
}

void Cloud_populatedFlow::unsetPublishedVersionId()
{
    m_PublishedVersionIdIsSet = false;
}
utility::string_t Cloud_populatedFlow::getStatus() const
{
    return m_Status;
}


void Cloud_populatedFlow::setStatus(const utility::string_t& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool Cloud_populatedFlow::statusIsSet() const
{
    return m_StatusIsSet;
}

void Cloud_populatedFlow::unsetStatus()
{
    m_StatusIsSet = false;
}
int32_t Cloud_populatedFlow::getUpdated() const
{
    return m_Updated;
}


void Cloud_populatedFlow::setUpdated(int32_t value)
{
    m_Updated = value;
    m_UpdatedIsSet = true;
}

bool Cloud_populatedFlow::updatedIsSet() const
{
    return m_UpdatedIsSet;
}

void Cloud_populatedFlow::unsetUpdated()
{
    m_UpdatedIsSet = false;
}
std::shared_ptr<Cloud_FlowVersion> Cloud_populatedFlow::getVersion() const
{
    return m_Version;
}


void Cloud_populatedFlow::setVersion(const std::shared_ptr<Cloud_FlowVersion>& value)
{
    m_Version = value;
    m_VersionIsSet = true;
}

bool Cloud_populatedFlow::versionIsSet() const
{
    return m_VersionIsSet;
}

void Cloud_populatedFlow::unsetVersion()
{
    m_VersionIsSet = false;
}

}
}


