/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "hanzo/model/CredentialIn.h"

namespace hanzo {
namespace model {

CredentialIn::CredentialIn()
{
    m_AccountId = utility::conversions::to_string_t("");
    m_AccountIdIsSet = false;
    m_Label = utility::conversions::to_string_t("");
    m_LabelIsSet = false;
    m_OauthIsSet = false;
    m_Provider = utility::conversions::to_string_t("");
    m_ProviderIsSet = false;
    m_Token = utility::conversions::to_string_t("");
    m_TokenIsSet = false;
}

CredentialIn::~CredentialIn()
{
}

void CredentialIn::validate()
{
    // TODO: implement validation
}

web::json::value CredentialIn::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_AccountIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("accountId"))] = ModelBase::toJson(m_AccountId);
    }
    if(m_LabelIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("label"))] = ModelBase::toJson(m_Label);
    }
    if(m_OauthIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("oauth"))] = ModelBase::toJson(m_Oauth);
    }
    if(m_ProviderIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("provider"))] = ModelBase::toJson(m_Provider);
    }
    if(m_TokenIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("token"))] = ModelBase::toJson(m_Token);
    }

    return val;
}

bool CredentialIn::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("accountId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("accountId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAccountId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAccountId);
            setAccountId(refVal_setAccountId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("label"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("label")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLabel;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLabel);
            setLabel(refVal_setLabel);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("oauth"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("oauth")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<OauthBundleIn> refVal_setOauth;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOauth);
            setOauth(refVal_setOauth);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("provider"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("provider")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProvider;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProvider);
            setProvider(refVal_setProvider);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("token"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("token")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setToken;
            ok &= ModelBase::fromJson(fieldValue, refVal_setToken);
            setToken(refVal_setToken);
            
        }
    }
    return ok;
}

void CredentialIn::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_AccountIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("accountId")), m_AccountId));
    }
    if(m_LabelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("label")), m_Label));
    }
    if(m_OauthIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("oauth")), m_Oauth));
    }
    if(m_ProviderIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("provider")), m_Provider));
    }
    if(m_TokenIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("token")), m_Token));
    }
}

bool CredentialIn::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("accountId"))))
    {
        utility::string_t refVal_setAccountId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("accountId"))), refVal_setAccountId );
        setAccountId(refVal_setAccountId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("label"))))
    {
        utility::string_t refVal_setLabel;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("label"))), refVal_setLabel );
        setLabel(refVal_setLabel);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("oauth"))))
    {
        std::shared_ptr<OauthBundleIn> refVal_setOauth;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("oauth"))), refVal_setOauth );
        setOauth(refVal_setOauth);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("provider"))))
    {
        utility::string_t refVal_setProvider;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("provider"))), refVal_setProvider );
        setProvider(refVal_setProvider);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("token"))))
    {
        utility::string_t refVal_setToken;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("token"))), refVal_setToken );
        setToken(refVal_setToken);
    }
    return ok;
}


utility::string_t CredentialIn::getAccountId() const
{
    return m_AccountId;
}


void CredentialIn::setAccountId(const utility::string_t& value)
{
    m_AccountId = value;
    m_AccountIdIsSet = true;
}

bool CredentialIn::accountIdIsSet() const
{
    return m_AccountIdIsSet;
}

void CredentialIn::unsetAccountId()
{
    m_AccountIdIsSet = false;
}
utility::string_t CredentialIn::getLabel() const
{
    return m_Label;
}


void CredentialIn::setLabel(const utility::string_t& value)
{
    m_Label = value;
    m_LabelIsSet = true;
}

bool CredentialIn::labelIsSet() const
{
    return m_LabelIsSet;
}

void CredentialIn::unsetLabel()
{
    m_LabelIsSet = false;
}
std::shared_ptr<OauthBundleIn> CredentialIn::getOauth() const
{
    return m_Oauth;
}


void CredentialIn::setOauth(const std::shared_ptr<OauthBundleIn>& value)
{
    m_Oauth = value;
    m_OauthIsSet = true;
}

bool CredentialIn::oauthIsSet() const
{
    return m_OauthIsSet;
}

void CredentialIn::unsetOauth()
{
    m_OauthIsSet = false;
}
utility::string_t CredentialIn::getProvider() const
{
    return m_Provider;
}


void CredentialIn::setProvider(const utility::string_t& value)
{
    m_Provider = value;
    m_ProviderIsSet = true;
}

bool CredentialIn::providerIsSet() const
{
    return m_ProviderIsSet;
}

void CredentialIn::unsetProvider()
{
    m_ProviderIsSet = false;
}
utility::string_t CredentialIn::getToken() const
{
    return m_Token;
}


void CredentialIn::setToken(const utility::string_t& value)
{
    m_Token = value;
    m_TokenIsSet = true;
}

bool CredentialIn::tokenIsSet() const
{
    return m_TokenIsSet;
}

void CredentialIn::unsetToken()
{
    m_TokenIsSet = false;
}

}
}


