/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "hanzo/model/Iam_ThemeData.h"

namespace hanzo {
namespace model {

Iam_ThemeData::Iam_ThemeData()
{
    m_BorderRadius = 0;
    m_BorderRadiusIsSet = false;
    m_ColorPrimary = utility::conversions::to_string_t("");
    m_ColorPrimaryIsSet = false;
    m_IsCompact = false;
    m_IsCompactIsSet = false;
    m_IsEnabled = false;
    m_IsEnabledIsSet = false;
    m_ThemeType = utility::conversions::to_string_t("");
    m_ThemeTypeIsSet = false;
}

Iam_ThemeData::~Iam_ThemeData()
{
}

void Iam_ThemeData::validate()
{
    // TODO: implement validation
}

web::json::value Iam_ThemeData::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_BorderRadiusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("borderRadius"))] = ModelBase::toJson(m_BorderRadius);
    }
    if(m_ColorPrimaryIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("colorPrimary"))] = ModelBase::toJson(m_ColorPrimary);
    }
    if(m_IsCompactIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("isCompact"))] = ModelBase::toJson(m_IsCompact);
    }
    if(m_IsEnabledIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("isEnabled"))] = ModelBase::toJson(m_IsEnabled);
    }
    if(m_ThemeTypeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("themeType"))] = ModelBase::toJson(m_ThemeType);
    }

    return val;
}

bool Iam_ThemeData::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("borderRadius"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("borderRadius")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setBorderRadius;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBorderRadius);
            setBorderRadius(refVal_setBorderRadius);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("colorPrimary"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("colorPrimary")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setColorPrimary;
            ok &= ModelBase::fromJson(fieldValue, refVal_setColorPrimary);
            setColorPrimary(refVal_setColorPrimary);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("isCompact"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("isCompact")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsCompact;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsCompact);
            setIsCompact(refVal_setIsCompact);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("isEnabled"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("isEnabled")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsEnabled;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsEnabled);
            setIsEnabled(refVal_setIsEnabled);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("themeType"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("themeType")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setThemeType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setThemeType);
            setThemeType(refVal_setThemeType);
            
        }
    }
    return ok;
}

void Iam_ThemeData::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_BorderRadiusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("borderRadius")), m_BorderRadius));
    }
    if(m_ColorPrimaryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("colorPrimary")), m_ColorPrimary));
    }
    if(m_IsCompactIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("isCompact")), m_IsCompact));
    }
    if(m_IsEnabledIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("isEnabled")), m_IsEnabled));
    }
    if(m_ThemeTypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("themeType")), m_ThemeType));
    }
}

bool Iam_ThemeData::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("borderRadius"))))
    {
        int32_t refVal_setBorderRadius;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("borderRadius"))), refVal_setBorderRadius );
        setBorderRadius(refVal_setBorderRadius);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("colorPrimary"))))
    {
        utility::string_t refVal_setColorPrimary;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("colorPrimary"))), refVal_setColorPrimary );
        setColorPrimary(refVal_setColorPrimary);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("isCompact"))))
    {
        bool refVal_setIsCompact;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("isCompact"))), refVal_setIsCompact );
        setIsCompact(refVal_setIsCompact);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("isEnabled"))))
    {
        bool refVal_setIsEnabled;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("isEnabled"))), refVal_setIsEnabled );
        setIsEnabled(refVal_setIsEnabled);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("themeType"))))
    {
        utility::string_t refVal_setThemeType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("themeType"))), refVal_setThemeType );
        setThemeType(refVal_setThemeType);
    }
    return ok;
}


int32_t Iam_ThemeData::getBorderRadius() const
{
    return m_BorderRadius;
}


void Iam_ThemeData::setBorderRadius(int32_t value)
{
    m_BorderRadius = value;
    m_BorderRadiusIsSet = true;
}

bool Iam_ThemeData::borderRadiusIsSet() const
{
    return m_BorderRadiusIsSet;
}

void Iam_ThemeData::unsetBorderRadius()
{
    m_BorderRadiusIsSet = false;
}
utility::string_t Iam_ThemeData::getColorPrimary() const
{
    return m_ColorPrimary;
}


void Iam_ThemeData::setColorPrimary(const utility::string_t& value)
{
    m_ColorPrimary = value;
    m_ColorPrimaryIsSet = true;
}

bool Iam_ThemeData::colorPrimaryIsSet() const
{
    return m_ColorPrimaryIsSet;
}

void Iam_ThemeData::unsetColorPrimary()
{
    m_ColorPrimaryIsSet = false;
}
bool Iam_ThemeData::isIsCompact() const
{
    return m_IsCompact;
}


void Iam_ThemeData::setIsCompact(bool value)
{
    m_IsCompact = value;
    m_IsCompactIsSet = true;
}

bool Iam_ThemeData::isCompactIsSet() const
{
    return m_IsCompactIsSet;
}

void Iam_ThemeData::unsetIsCompact()
{
    m_IsCompactIsSet = false;
}
bool Iam_ThemeData::isIsEnabled() const
{
    return m_IsEnabled;
}


void Iam_ThemeData::setIsEnabled(bool value)
{
    m_IsEnabled = value;
    m_IsEnabledIsSet = true;
}

bool Iam_ThemeData::isEnabledIsSet() const
{
    return m_IsEnabledIsSet;
}

void Iam_ThemeData::unsetIsEnabled()
{
    m_IsEnabledIsSet = false;
}
utility::string_t Iam_ThemeData::getThemeType() const
{
    return m_ThemeType;
}


void Iam_ThemeData::setThemeType(const utility::string_t& value)
{
    m_ThemeType = value;
    m_ThemeTypeIsSet = true;
}

bool Iam_ThemeData::themeTypeIsSet() const
{
    return m_ThemeTypeIsSet;
}

void Iam_ThemeData::unsetThemeType()
{
    m_ThemeTypeIsSet = false;
}

}
}


