/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "hanzo/model/Iam_object_AccountItem.h"

namespace hanzo {
namespace model {

Iam_object_AccountItem::Iam_object_AccountItem()
{
    m_ModifyRule = utility::conversions::to_string_t("");
    m_ModifyRuleIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Regex = utility::conversions::to_string_t("");
    m_RegexIsSet = false;
    m_Tab = utility::conversions::to_string_t("");
    m_TabIsSet = false;
    m_ViewRule = utility::conversions::to_string_t("");
    m_ViewRuleIsSet = false;
    m_Visible = false;
    m_VisibleIsSet = false;
}

Iam_object_AccountItem::~Iam_object_AccountItem()
{
}

void Iam_object_AccountItem::validate()
{
    // TODO: implement validation
}

web::json::value Iam_object_AccountItem::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ModifyRuleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("modifyRule"))] = ModelBase::toJson(m_ModifyRule);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_RegexIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("regex"))] = ModelBase::toJson(m_Regex);
    }
    if(m_TabIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tab"))] = ModelBase::toJson(m_Tab);
    }
    if(m_ViewRuleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("viewRule"))] = ModelBase::toJson(m_ViewRule);
    }
    if(m_VisibleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("visible"))] = ModelBase::toJson(m_Visible);
    }

    return val;
}

bool Iam_object_AccountItem::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("modifyRule"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("modifyRule")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setModifyRule;
            ok &= ModelBase::fromJson(fieldValue, refVal_setModifyRule);
            setModifyRule(refVal_setModifyRule);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("regex"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("regex")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRegex;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRegex);
            setRegex(refVal_setRegex);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tab"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tab")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTab;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTab);
            setTab(refVal_setTab);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("viewRule"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("viewRule")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setViewRule;
            ok &= ModelBase::fromJson(fieldValue, refVal_setViewRule);
            setViewRule(refVal_setViewRule);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("visible"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("visible")));
        if(!fieldValue.is_null())
        {
            bool refVal_setVisible;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVisible);
            setVisible(refVal_setVisible);
            
        }
    }
    return ok;
}

void Iam_object_AccountItem::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ModifyRuleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("modifyRule")), m_ModifyRule));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_RegexIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("regex")), m_Regex));
    }
    if(m_TabIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tab")), m_Tab));
    }
    if(m_ViewRuleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("viewRule")), m_ViewRule));
    }
    if(m_VisibleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("visible")), m_Visible));
    }
}

bool Iam_object_AccountItem::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("modifyRule"))))
    {
        utility::string_t refVal_setModifyRule;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("modifyRule"))), refVal_setModifyRule );
        setModifyRule(refVal_setModifyRule);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("regex"))))
    {
        utility::string_t refVal_setRegex;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("regex"))), refVal_setRegex );
        setRegex(refVal_setRegex);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tab"))))
    {
        utility::string_t refVal_setTab;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tab"))), refVal_setTab );
        setTab(refVal_setTab);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("viewRule"))))
    {
        utility::string_t refVal_setViewRule;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("viewRule"))), refVal_setViewRule );
        setViewRule(refVal_setViewRule);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("visible"))))
    {
        bool refVal_setVisible;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("visible"))), refVal_setVisible );
        setVisible(refVal_setVisible);
    }
    return ok;
}


utility::string_t Iam_object_AccountItem::getModifyRule() const
{
    return m_ModifyRule;
}


void Iam_object_AccountItem::setModifyRule(const utility::string_t& value)
{
    m_ModifyRule = value;
    m_ModifyRuleIsSet = true;
}

bool Iam_object_AccountItem::modifyRuleIsSet() const
{
    return m_ModifyRuleIsSet;
}

void Iam_object_AccountItem::unsetModifyRule()
{
    m_ModifyRuleIsSet = false;
}
utility::string_t Iam_object_AccountItem::getName() const
{
    return m_Name;
}


void Iam_object_AccountItem::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool Iam_object_AccountItem::nameIsSet() const
{
    return m_NameIsSet;
}

void Iam_object_AccountItem::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t Iam_object_AccountItem::getRegex() const
{
    return m_Regex;
}


void Iam_object_AccountItem::setRegex(const utility::string_t& value)
{
    m_Regex = value;
    m_RegexIsSet = true;
}

bool Iam_object_AccountItem::regexIsSet() const
{
    return m_RegexIsSet;
}

void Iam_object_AccountItem::unsetRegex()
{
    m_RegexIsSet = false;
}
utility::string_t Iam_object_AccountItem::getTab() const
{
    return m_Tab;
}


void Iam_object_AccountItem::setTab(const utility::string_t& value)
{
    m_Tab = value;
    m_TabIsSet = true;
}

bool Iam_object_AccountItem::tabIsSet() const
{
    return m_TabIsSet;
}

void Iam_object_AccountItem::unsetTab()
{
    m_TabIsSet = false;
}
utility::string_t Iam_object_AccountItem::getViewRule() const
{
    return m_ViewRule;
}


void Iam_object_AccountItem::setViewRule(const utility::string_t& value)
{
    m_ViewRule = value;
    m_ViewRuleIsSet = true;
}

bool Iam_object_AccountItem::viewRuleIsSet() const
{
    return m_ViewRuleIsSet;
}

void Iam_object_AccountItem::unsetViewRule()
{
    m_ViewRuleIsSet = false;
}
bool Iam_object_AccountItem::isVisible() const
{
    return m_Visible;
}


void Iam_object_AccountItem::setVisible(bool value)
{
    m_Visible = value;
    m_VisibleIsSet = true;
}

bool Iam_object_AccountItem::visibleIsSet() const
{
    return m_VisibleIsSet;
}

void Iam_object_AccountItem::unsetVisible()
{
    m_VisibleIsSet = false;
}

}
}


