/**
 * Hanzo Cloud API
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "hanzo/model/InvokeReq.h"

namespace hanzo {
namespace model {

InvokeReq::InvokeReq()
{
    m_Input = utility::conversions::to_string_t("");
    m_InputIsSet = false;
}

InvokeReq::~InvokeReq()
{
}

void InvokeReq::validate()
{
    // TODO: implement validation
}

web::json::value InvokeReq::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_InputIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("input"))] = ModelBase::toJson(m_Input);
    }

    return val;
}

bool InvokeReq::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("input"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("input")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setInput;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInput);
            setInput(refVal_setInput);
            
        }
    }
    return ok;
}

void InvokeReq::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_InputIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("input")), m_Input));
    }
}

bool InvokeReq::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("input"))))
    {
        utility::string_t refVal_setInput;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("input"))), refVal_setInput );
        setInput(refVal_setInput);
    }
    return ok;
}


utility::string_t InvokeReq::getInput() const
{
    return m_Input;
}


void InvokeReq::setInput(const utility::string_t& value)
{
    m_Input = value;
    m_InputIsSet = true;
}

bool InvokeReq::inputIsSet() const
{
    return m_InputIsSet;
}

void InvokeReq::unsetInput()
{
    m_InputIsSet = false;
}

}
}


