/**
 * Hanzo Cloud API
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "hanzo/model/O11y_RocketchatConfig.h"

namespace hanzo {
namespace model {

O11y_RocketchatConfig::O11y_RocketchatConfig()
{
    m_NotifierConfigIsSet = false;
    m_ActionsIsSet = false;
    m_Channel = utility::conversions::to_string_t("");
    m_ChannelIsSet = false;
    m_Color = utility::conversions::to_string_t("");
    m_ColorIsSet = false;
    m_Emoji = utility::conversions::to_string_t("");
    m_EmojiIsSet = false;
    m_FieldsIsSet = false;
    m_Http_configIsSet = false;
    m_Icon_url = utility::conversions::to_string_t("");
    m_Icon_urlIsSet = false;
    m_Image_url = utility::conversions::to_string_t("");
    m_Image_urlIsSet = false;
    m_Link_names = false;
    m_Link_namesIsSet = false;
    m_Short_fields = false;
    m_Short_fieldsIsSet = false;
    m_Text = utility::conversions::to_string_t("");
    m_TextIsSet = false;
    m_Thumb_url = utility::conversions::to_string_t("");
    m_Thumb_urlIsSet = false;
    m_Title = utility::conversions::to_string_t("");
    m_TitleIsSet = false;
    m_Title_link = utility::conversions::to_string_t("");
    m_Title_linkIsSet = false;
    m_Token_file = utility::conversions::to_string_t("");
    m_Token_fileIsSet = false;
    m_Token_id_file = utility::conversions::to_string_t("");
    m_Token_id_fileIsSet = false;
}

O11y_RocketchatConfig::~O11y_RocketchatConfig()
{
}

void O11y_RocketchatConfig::validate()
{
    // TODO: implement validation
}

web::json::value O11y_RocketchatConfig::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_NotifierConfigIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("NotifierConfig"))] = ModelBase::toJson(m_NotifierConfig);
    }
    if(m_ActionsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("actions"))] = ModelBase::toJson(m_Actions);
    }
    if(m_Api_url.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("api_url"))] = ModelBase::toJson(m_Api_url.get());
    }
    if(m_ChannelIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("channel"))] = ModelBase::toJson(m_Channel);
    }
    if(m_ColorIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("color"))] = ModelBase::toJson(m_Color);
    }
    if(m_EmojiIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("emoji"))] = ModelBase::toJson(m_Emoji);
    }
    if(m_FieldsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("fields"))] = ModelBase::toJson(m_Fields);
    }
    if(m_Http_configIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("http_config"))] = ModelBase::toJson(m_Http_config);
    }
    if(m_Icon_urlIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("icon_url"))] = ModelBase::toJson(m_Icon_url);
    }
    if(m_Image_urlIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("image_url"))] = ModelBase::toJson(m_Image_url);
    }
    if(m_Link_namesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("link_names"))] = ModelBase::toJson(m_Link_names);
    }
    if(m_Short_fieldsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("short_fields"))] = ModelBase::toJson(m_Short_fields);
    }
    if(m_TextIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("text"))] = ModelBase::toJson(m_Text);
    }
    if(m_Thumb_urlIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("thumb_url"))] = ModelBase::toJson(m_Thumb_url);
    }
    if(m_TitleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("title"))] = ModelBase::toJson(m_Title);
    }
    if(m_Title_linkIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("title_link"))] = ModelBase::toJson(m_Title_link);
    }
    if(m_Token.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("token"))] = ModelBase::toJson(m_Token.get());
    }
    if(m_Token_fileIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("token_file"))] = ModelBase::toJson(m_Token_file);
    }
    if(m_Token_id.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("token_id"))] = ModelBase::toJson(m_Token_id.get());
    }
    if(m_Token_id_fileIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("token_id_file"))] = ModelBase::toJson(m_Token_id_file);
    }

    return val;
}

bool O11y_RocketchatConfig::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("NotifierConfig"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("NotifierConfig")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<O11y_NotifierConfig> refVal_setNotifierConfig;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNotifierConfig);
            setNotifierConfig(refVal_setNotifierConfig);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("actions"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("actions")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<O11y_RocketchatAttachmentAction>> refVal_setActions;
            ok &= ModelBase::fromJson(fieldValue, refVal_setActions);
            setActions(refVal_setActions);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("api_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("api_url")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AnyType> refVal_setApiUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setApiUrl);
            setApiUrl(refVal_setApiUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("channel"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("channel")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setChannel;
            ok &= ModelBase::fromJson(fieldValue, refVal_setChannel);
            setChannel(refVal_setChannel);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("color"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("color")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setColor;
            ok &= ModelBase::fromJson(fieldValue, refVal_setColor);
            setColor(refVal_setColor);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("emoji"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("emoji")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmoji;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmoji);
            setEmoji(refVal_setEmoji);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("fields"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("fields")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<O11y_RocketchatAttachmentField>> refVal_setFields;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFields);
            setFields(refVal_setFields);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("http_config"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("http_config")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<O11y_HTTPClientConfig> refVal_setHttpConfig;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHttpConfig);
            setHttpConfig(refVal_setHttpConfig);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("icon_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("icon_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setIconUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIconUrl);
            setIconUrl(refVal_setIconUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("image_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("image_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setImageUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setImageUrl);
            setImageUrl(refVal_setImageUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("link_names"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("link_names")));
        if(!fieldValue.is_null())
        {
            bool refVal_setLinkNames;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLinkNames);
            setLinkNames(refVal_setLinkNames);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("short_fields"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("short_fields")));
        if(!fieldValue.is_null())
        {
            bool refVal_setShortFields;
            ok &= ModelBase::fromJson(fieldValue, refVal_setShortFields);
            setShortFields(refVal_setShortFields);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("text"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("text")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setText;
            ok &= ModelBase::fromJson(fieldValue, refVal_setText);
            setText(refVal_setText);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("thumb_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("thumb_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setThumbUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setThumbUrl);
            setThumbUrl(refVal_setThumbUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("title")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTitle);
            setTitle(refVal_setTitle);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("title_link"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("title_link")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTitleLink;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTitleLink);
            setTitleLink(refVal_setTitleLink);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("token"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("token")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AnyType> refVal_setToken;
            ok &= ModelBase::fromJson(fieldValue, refVal_setToken);
            setToken(refVal_setToken);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("token_file"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("token_file")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTokenFile;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTokenFile);
            setTokenFile(refVal_setTokenFile);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("token_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("token_id")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AnyType> refVal_setTokenId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTokenId);
            setTokenId(refVal_setTokenId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("token_id_file"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("token_id_file")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTokenIdFile;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTokenIdFile);
            setTokenIdFile(refVal_setTokenIdFile);
            
        }
    }
    return ok;
}

void O11y_RocketchatConfig::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_NotifierConfigIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("NotifierConfig")), m_NotifierConfig));
    }
    if(m_ActionsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("actions")), m_Actions));
    }
    if(m_Api_url.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("api_url")), m_Api_url.get()));
    }
    if(m_ChannelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("channel")), m_Channel));
    }
    if(m_ColorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("color")), m_Color));
    }
    if(m_EmojiIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("emoji")), m_Emoji));
    }
    if(m_FieldsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("fields")), m_Fields));
    }
    if(m_Http_configIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("http_config")), m_Http_config));
    }
    if(m_Icon_urlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("icon_url")), m_Icon_url));
    }
    if(m_Image_urlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("image_url")), m_Image_url));
    }
    if(m_Link_namesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("link_names")), m_Link_names));
    }
    if(m_Short_fieldsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("short_fields")), m_Short_fields));
    }
    if(m_TextIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("text")), m_Text));
    }
    if(m_Thumb_urlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("thumb_url")), m_Thumb_url));
    }
    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("title")), m_Title));
    }
    if(m_Title_linkIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("title_link")), m_Title_link));
    }
    if(m_Token.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("token")), m_Token.get()));
    }
    if(m_Token_fileIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("token_file")), m_Token_file));
    }
    if(m_Token_id.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("token_id")), m_Token_id.get()));
    }
    if(m_Token_id_fileIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("token_id_file")), m_Token_id_file));
    }
}

bool O11y_RocketchatConfig::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("NotifierConfig"))))
    {
        std::shared_ptr<O11y_NotifierConfig> refVal_setNotifierConfig;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("NotifierConfig"))), refVal_setNotifierConfig );
        setNotifierConfig(refVal_setNotifierConfig);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("actions"))))
    {
        std::vector<std::shared_ptr<O11y_RocketchatAttachmentAction>> refVal_setActions;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("actions"))), refVal_setActions );
        setActions(refVal_setActions);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("api_url"))))
    {
        std::shared_ptr<AnyType> refVal_setApiUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("api_url"))), refVal_setApiUrl );
        setApiUrl(refVal_setApiUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("channel"))))
    {
        utility::string_t refVal_setChannel;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("channel"))), refVal_setChannel );
        setChannel(refVal_setChannel);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("color"))))
    {
        utility::string_t refVal_setColor;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("color"))), refVal_setColor );
        setColor(refVal_setColor);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("emoji"))))
    {
        utility::string_t refVal_setEmoji;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("emoji"))), refVal_setEmoji );
        setEmoji(refVal_setEmoji);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("fields"))))
    {
        std::vector<std::shared_ptr<O11y_RocketchatAttachmentField>> refVal_setFields;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("fields"))), refVal_setFields );
        setFields(refVal_setFields);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("http_config"))))
    {
        std::shared_ptr<O11y_HTTPClientConfig> refVal_setHttpConfig;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("http_config"))), refVal_setHttpConfig );
        setHttpConfig(refVal_setHttpConfig);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("icon_url"))))
    {
        utility::string_t refVal_setIconUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("icon_url"))), refVal_setIconUrl );
        setIconUrl(refVal_setIconUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("image_url"))))
    {
        utility::string_t refVal_setImageUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("image_url"))), refVal_setImageUrl );
        setImageUrl(refVal_setImageUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("link_names"))))
    {
        bool refVal_setLinkNames;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("link_names"))), refVal_setLinkNames );
        setLinkNames(refVal_setLinkNames);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("short_fields"))))
    {
        bool refVal_setShortFields;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("short_fields"))), refVal_setShortFields );
        setShortFields(refVal_setShortFields);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("text"))))
    {
        utility::string_t refVal_setText;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("text"))), refVal_setText );
        setText(refVal_setText);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("thumb_url"))))
    {
        utility::string_t refVal_setThumbUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("thumb_url"))), refVal_setThumbUrl );
        setThumbUrl(refVal_setThumbUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        utility::string_t refVal_setTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("title"))), refVal_setTitle );
        setTitle(refVal_setTitle);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("title_link"))))
    {
        utility::string_t refVal_setTitleLink;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("title_link"))), refVal_setTitleLink );
        setTitleLink(refVal_setTitleLink);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("token"))))
    {
        std::shared_ptr<AnyType> refVal_setToken;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("token"))), refVal_setToken );
        setToken(refVal_setToken);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("token_file"))))
    {
        utility::string_t refVal_setTokenFile;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("token_file"))), refVal_setTokenFile );
        setTokenFile(refVal_setTokenFile);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("token_id"))))
    {
        std::shared_ptr<AnyType> refVal_setTokenId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("token_id"))), refVal_setTokenId );
        setTokenId(refVal_setTokenId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("token_id_file"))))
    {
        utility::string_t refVal_setTokenIdFile;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("token_id_file"))), refVal_setTokenIdFile );
        setTokenIdFile(refVal_setTokenIdFile);
    }
    return ok;
}


std::shared_ptr<O11y_NotifierConfig> O11y_RocketchatConfig::getNotifierConfig() const
{
    return m_NotifierConfig;
}


void O11y_RocketchatConfig::setNotifierConfig(const std::shared_ptr<O11y_NotifierConfig>& value)
{
    m_NotifierConfig = value;
    m_NotifierConfigIsSet = true;
}

bool O11y_RocketchatConfig::notifierConfigIsSet() const
{
    return m_NotifierConfigIsSet;
}

void O11y_RocketchatConfig::unsetNotifierConfig()
{
    m_NotifierConfigIsSet = false;
}
std::vector<std::shared_ptr<O11y_RocketchatAttachmentAction>> O11y_RocketchatConfig::getActions() const
{
    return m_Actions;
}


void O11y_RocketchatConfig::setActions(const std::vector<std::shared_ptr<O11y_RocketchatAttachmentAction>>& value)
{
    m_Actions = value;
    m_ActionsIsSet = true;
}

bool O11y_RocketchatConfig::actionsIsSet() const
{
    return m_ActionsIsSet;
}

void O11y_RocketchatConfig::unsetActions()
{
    m_ActionsIsSet = false;
}
std::shared_ptr<AnyType> O11y_RocketchatConfig::getApiUrl() const
{
    return m_Api_url.get();
}


void O11y_RocketchatConfig::setApiUrl(const std::shared_ptr<AnyType>& value)
{
    m_Api_url = value;
}

bool O11y_RocketchatConfig::apiUrlIsSet() const
{
    return m_Api_url.has_value();
}

void O11y_RocketchatConfig::unsetApi_url()
{
    m_Api_url.reset();
}
utility::string_t O11y_RocketchatConfig::getChannel() const
{
    return m_Channel;
}


void O11y_RocketchatConfig::setChannel(const utility::string_t& value)
{
    m_Channel = value;
    m_ChannelIsSet = true;
}

bool O11y_RocketchatConfig::channelIsSet() const
{
    return m_ChannelIsSet;
}

void O11y_RocketchatConfig::unsetChannel()
{
    m_ChannelIsSet = false;
}
utility::string_t O11y_RocketchatConfig::getColor() const
{
    return m_Color;
}


void O11y_RocketchatConfig::setColor(const utility::string_t& value)
{
    m_Color = value;
    m_ColorIsSet = true;
}

bool O11y_RocketchatConfig::colorIsSet() const
{
    return m_ColorIsSet;
}

void O11y_RocketchatConfig::unsetColor()
{
    m_ColorIsSet = false;
}
utility::string_t O11y_RocketchatConfig::getEmoji() const
{
    return m_Emoji;
}


void O11y_RocketchatConfig::setEmoji(const utility::string_t& value)
{
    m_Emoji = value;
    m_EmojiIsSet = true;
}

bool O11y_RocketchatConfig::emojiIsSet() const
{
    return m_EmojiIsSet;
}

void O11y_RocketchatConfig::unsetEmoji()
{
    m_EmojiIsSet = false;
}
std::vector<std::shared_ptr<O11y_RocketchatAttachmentField>> O11y_RocketchatConfig::getFields() const
{
    return m_Fields;
}


void O11y_RocketchatConfig::setFields(const std::vector<std::shared_ptr<O11y_RocketchatAttachmentField>>& value)
{
    m_Fields = value;
    m_FieldsIsSet = true;
}

bool O11y_RocketchatConfig::fieldsIsSet() const
{
    return m_FieldsIsSet;
}

void O11y_RocketchatConfig::unsetFields()
{
    m_FieldsIsSet = false;
}
std::shared_ptr<O11y_HTTPClientConfig> O11y_RocketchatConfig::getHttpConfig() const
{
    return m_Http_config;
}


void O11y_RocketchatConfig::setHttpConfig(const std::shared_ptr<O11y_HTTPClientConfig>& value)
{
    m_Http_config = value;
    m_Http_configIsSet = true;
}

bool O11y_RocketchatConfig::httpConfigIsSet() const
{
    return m_Http_configIsSet;
}

void O11y_RocketchatConfig::unsetHttp_config()
{
    m_Http_configIsSet = false;
}
utility::string_t O11y_RocketchatConfig::getIconUrl() const
{
    return m_Icon_url;
}


void O11y_RocketchatConfig::setIconUrl(const utility::string_t& value)
{
    m_Icon_url = value;
    m_Icon_urlIsSet = true;
}

bool O11y_RocketchatConfig::iconUrlIsSet() const
{
    return m_Icon_urlIsSet;
}

void O11y_RocketchatConfig::unsetIcon_url()
{
    m_Icon_urlIsSet = false;
}
utility::string_t O11y_RocketchatConfig::getImageUrl() const
{
    return m_Image_url;
}


void O11y_RocketchatConfig::setImageUrl(const utility::string_t& value)
{
    m_Image_url = value;
    m_Image_urlIsSet = true;
}

bool O11y_RocketchatConfig::imageUrlIsSet() const
{
    return m_Image_urlIsSet;
}

void O11y_RocketchatConfig::unsetImage_url()
{
    m_Image_urlIsSet = false;
}
bool O11y_RocketchatConfig::isLinkNames() const
{
    return m_Link_names;
}


void O11y_RocketchatConfig::setLinkNames(bool value)
{
    m_Link_names = value;
    m_Link_namesIsSet = true;
}

bool O11y_RocketchatConfig::linkNamesIsSet() const
{
    return m_Link_namesIsSet;
}

void O11y_RocketchatConfig::unsetLink_names()
{
    m_Link_namesIsSet = false;
}
bool O11y_RocketchatConfig::isShortFields() const
{
    return m_Short_fields;
}


void O11y_RocketchatConfig::setShortFields(bool value)
{
    m_Short_fields = value;
    m_Short_fieldsIsSet = true;
}

bool O11y_RocketchatConfig::shortFieldsIsSet() const
{
    return m_Short_fieldsIsSet;
}

void O11y_RocketchatConfig::unsetShort_fields()
{
    m_Short_fieldsIsSet = false;
}
utility::string_t O11y_RocketchatConfig::getText() const
{
    return m_Text;
}


void O11y_RocketchatConfig::setText(const utility::string_t& value)
{
    m_Text = value;
    m_TextIsSet = true;
}

bool O11y_RocketchatConfig::textIsSet() const
{
    return m_TextIsSet;
}

void O11y_RocketchatConfig::unsetText()
{
    m_TextIsSet = false;
}
utility::string_t O11y_RocketchatConfig::getThumbUrl() const
{
    return m_Thumb_url;
}


void O11y_RocketchatConfig::setThumbUrl(const utility::string_t& value)
{
    m_Thumb_url = value;
    m_Thumb_urlIsSet = true;
}

bool O11y_RocketchatConfig::thumbUrlIsSet() const
{
    return m_Thumb_urlIsSet;
}

void O11y_RocketchatConfig::unsetThumb_url()
{
    m_Thumb_urlIsSet = false;
}
utility::string_t O11y_RocketchatConfig::getTitle() const
{
    return m_Title;
}


void O11y_RocketchatConfig::setTitle(const utility::string_t& value)
{
    m_Title = value;
    m_TitleIsSet = true;
}

bool O11y_RocketchatConfig::titleIsSet() const
{
    return m_TitleIsSet;
}

void O11y_RocketchatConfig::unsetTitle()
{
    m_TitleIsSet = false;
}
utility::string_t O11y_RocketchatConfig::getTitleLink() const
{
    return m_Title_link;
}


void O11y_RocketchatConfig::setTitleLink(const utility::string_t& value)
{
    m_Title_link = value;
    m_Title_linkIsSet = true;
}

bool O11y_RocketchatConfig::titleLinkIsSet() const
{
    return m_Title_linkIsSet;
}

void O11y_RocketchatConfig::unsetTitle_link()
{
    m_Title_linkIsSet = false;
}
std::shared_ptr<AnyType> O11y_RocketchatConfig::getToken() const
{
    return m_Token.get();
}


void O11y_RocketchatConfig::setToken(const std::shared_ptr<AnyType>& value)
{
    m_Token = value;
}

bool O11y_RocketchatConfig::tokenIsSet() const
{
    return m_Token.has_value();
}

void O11y_RocketchatConfig::unsetToken()
{
    m_Token.reset();
}
utility::string_t O11y_RocketchatConfig::getTokenFile() const
{
    return m_Token_file;
}


void O11y_RocketchatConfig::setTokenFile(const utility::string_t& value)
{
    m_Token_file = value;
    m_Token_fileIsSet = true;
}

bool O11y_RocketchatConfig::tokenFileIsSet() const
{
    return m_Token_fileIsSet;
}

void O11y_RocketchatConfig::unsetToken_file()
{
    m_Token_fileIsSet = false;
}
std::shared_ptr<AnyType> O11y_RocketchatConfig::getTokenId() const
{
    return m_Token_id.get();
}


void O11y_RocketchatConfig::setTokenId(const std::shared_ptr<AnyType>& value)
{
    m_Token_id = value;
}

bool O11y_RocketchatConfig::tokenIdIsSet() const
{
    return m_Token_id.has_value();
}

void O11y_RocketchatConfig::unsetToken_id()
{
    m_Token_id.reset();
}
utility::string_t O11y_RocketchatConfig::getTokenIdFile() const
{
    return m_Token_id_file;
}


void O11y_RocketchatConfig::setTokenIdFile(const utility::string_t& value)
{
    m_Token_id_file = value;
    m_Token_id_fileIsSet = true;
}

bool O11y_RocketchatConfig::tokenIdFileIsSet() const
{
    return m_Token_id_fileIsSet;
}

void O11y_RocketchatConfig::unsetToken_id_file()
{
    m_Token_id_fileIsSet = false;
}

}
}


