/**
 * Hanzo Cloud API
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "hanzo/model/O11y_O11yFrame.h"

namespace hanzo {
namespace model {

O11y_O11yFrame::O11y_O11yFrame()
{
    m_Column = 0;
    m_ColumnIsSet = false;
    m_file = utility::conversions::to_string_t("");
    m_fileIsSet = false;
    m_Function = utility::conversions::to_string_t("");
    m_FunctionIsSet = false;
    m_Line = 0;
    m_LineIsSet = false;
    m_Own = false;
    m_OwnIsSet = false;
}

O11y_O11yFrame::~O11y_O11yFrame()
{
}

void O11y_O11yFrame::validate()
{
    // TODO: implement validation
}

web::json::value O11y_O11yFrame::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ColumnIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("column"))] = ModelBase::toJson(m_Column);
    }
    if(m_fileIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("file"))] = ModelBase::toJson(m_file);
    }
    if(m_FunctionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("function"))] = ModelBase::toJson(m_Function);
    }
    if(m_LineIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("line"))] = ModelBase::toJson(m_Line);
    }
    if(m_OwnIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("own"))] = ModelBase::toJson(m_Own);
    }

    return val;
}

bool O11y_O11yFrame::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("column"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("column")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setColumn;
            ok &= ModelBase::fromJson(fieldValue, refVal_setColumn);
            setColumn(refVal_setColumn);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("file"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("file")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFile;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFile);
            setFile(refVal_setFile);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("function"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("function")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFunction;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFunction);
            setFunction(refVal_setFunction);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("line"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("line")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setLine;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLine);
            setLine(refVal_setLine);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("own"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("own")));
        if(!fieldValue.is_null())
        {
            bool refVal_setOwn;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOwn);
            setOwn(refVal_setOwn);
            
        }
    }
    return ok;
}

void O11y_O11yFrame::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ColumnIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("column")), m_Column));
    }
    if(m_fileIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("file")), m_file));
    }
    if(m_FunctionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("function")), m_Function));
    }
    if(m_LineIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("line")), m_Line));
    }
    if(m_OwnIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("own")), m_Own));
    }
}

bool O11y_O11yFrame::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("column"))))
    {
        int32_t refVal_setColumn;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("column"))), refVal_setColumn );
        setColumn(refVal_setColumn);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("file"))))
    {
        utility::string_t refVal_setFile;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("file"))), refVal_setFile );
        setFile(refVal_setFile);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("function"))))
    {
        utility::string_t refVal_setFunction;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("function"))), refVal_setFunction );
        setFunction(refVal_setFunction);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("line"))))
    {
        int32_t refVal_setLine;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("line"))), refVal_setLine );
        setLine(refVal_setLine);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("own"))))
    {
        bool refVal_setOwn;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("own"))), refVal_setOwn );
        setOwn(refVal_setOwn);
    }
    return ok;
}


int32_t O11y_O11yFrame::getColumn() const
{
    return m_Column;
}


void O11y_O11yFrame::setColumn(int32_t value)
{
    m_Column = value;
    m_ColumnIsSet = true;
}

bool O11y_O11yFrame::columnIsSet() const
{
    return m_ColumnIsSet;
}

void O11y_O11yFrame::unsetColumn()
{
    m_ColumnIsSet = false;
}
utility::string_t O11y_O11yFrame::getFile() const
{
    return m_file;
}


void O11y_O11yFrame::setFile(const utility::string_t& value)
{
    m_file = value;
    m_fileIsSet = true;
}

bool O11y_O11yFrame::fileIsSet() const
{
    return m_fileIsSet;
}

void O11y_O11yFrame::unsetfile()
{
    m_fileIsSet = false;
}
utility::string_t O11y_O11yFrame::getFunction() const
{
    return m_Function;
}


void O11y_O11yFrame::setFunction(const utility::string_t& value)
{
    m_Function = value;
    m_FunctionIsSet = true;
}

bool O11y_O11yFrame::functionIsSet() const
{
    return m_FunctionIsSet;
}

void O11y_O11yFrame::unsetFunction()
{
    m_FunctionIsSet = false;
}
int32_t O11y_O11yFrame::getLine() const
{
    return m_Line;
}


void O11y_O11yFrame::setLine(int32_t value)
{
    m_Line = value;
    m_LineIsSet = true;
}

bool O11y_O11yFrame::lineIsSet() const
{
    return m_LineIsSet;
}

void O11y_O11yFrame::unsetLine()
{
    m_LineIsSet = false;
}
bool O11y_O11yFrame::isOwn() const
{
    return m_Own;
}


void O11y_O11yFrame::setOwn(bool value)
{
    m_Own = value;
    m_OwnIsSet = true;
}

bool O11y_O11yFrame::ownIsSet() const
{
    return m_OwnIsSet;
}

void O11y_O11yFrame::unsetOwn()
{
    m_OwnIsSet = false;
}

}
}


