/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "hanzo/model/O11y_O11yUser.h"

namespace hanzo {
namespace model {

O11y_O11yUser::O11y_O11yUser()
{
    m_CreatedAt = utility::datetime();
    m_CreatedAtIsSet = false;
    m_DisplayName = utility::conversions::to_string_t("");
    m_DisplayNameIsSet = false;
    m_Email = utility::conversions::to_string_t("");
    m_EmailIsSet = false;
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_IsRoot = false;
    m_IsRootIsSet = false;
    m_OrgId = utility::conversions::to_string_t("");
    m_OrgIdIsSet = false;
    m_Status = utility::conversions::to_string_t("");
    m_StatusIsSet = false;
    m_UpdatedAt = utility::datetime();
    m_UpdatedAtIsSet = false;
}

O11y_O11yUser::~O11y_O11yUser()
{
}

void O11y_O11yUser::validate()
{
    // TODO: implement validation
}

web::json::value O11y_O11yUser::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_CreatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdAt"))] = ModelBase::toJson(m_CreatedAt);
    }
    if(m_DisplayNameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("displayName"))] = ModelBase::toJson(m_DisplayName);
    }
    if(m_EmailIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("email"))] = ModelBase::toJson(m_Email);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_IsRootIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("isRoot"))] = ModelBase::toJson(m_IsRoot);
    }
    if(m_OrgIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("orgId"))] = ModelBase::toJson(m_OrgId);
    }
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_UpdatedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updatedAt"))] = ModelBase::toJson(m_UpdatedAt);
    }

    return val;
}

bool O11y_O11yUser::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("displayName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("displayName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDisplayName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDisplayName);
            setDisplayName(refVal_setDisplayName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("email")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmail);
            setEmail(refVal_setEmail);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("isRoot"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("isRoot")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsRoot;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsRoot);
            setIsRoot(refVal_setIsRoot);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("orgId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("orgId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOrgId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOrgId);
            setOrgId(refVal_setOrgId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updatedAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    return ok;
}

void O11y_O11yUser::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_CreatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdAt")), m_CreatedAt));
    }
    if(m_DisplayNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("displayName")), m_DisplayName));
    }
    if(m_EmailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("email")), m_Email));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_IsRootIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("isRoot")), m_IsRoot));
    }
    if(m_OrgIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("orgId")), m_OrgId));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_UpdatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updatedAt")), m_UpdatedAt));
    }
}

bool O11y_O11yUser::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        utility::datetime refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("displayName"))))
    {
        utility::string_t refVal_setDisplayName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("displayName"))), refVal_setDisplayName );
        setDisplayName(refVal_setDisplayName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        utility::string_t refVal_setEmail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("email"))), refVal_setEmail );
        setEmail(refVal_setEmail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("isRoot"))))
    {
        bool refVal_setIsRoot;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("isRoot"))), refVal_setIsRoot );
        setIsRoot(refVal_setIsRoot);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("orgId"))))
    {
        utility::string_t refVal_setOrgId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("orgId"))), refVal_setOrgId );
        setOrgId(refVal_setOrgId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        utility::datetime refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    return ok;
}


utility::datetime O11y_O11yUser::getCreatedAt() const
{
    return m_CreatedAt;
}


void O11y_O11yUser::setCreatedAt(const utility::datetime& value)
{
    m_CreatedAt = value;
    m_CreatedAtIsSet = true;
}

bool O11y_O11yUser::createdAtIsSet() const
{
    return m_CreatedAtIsSet;
}

void O11y_O11yUser::unsetCreatedAt()
{
    m_CreatedAtIsSet = false;
}
utility::string_t O11y_O11yUser::getDisplayName() const
{
    return m_DisplayName;
}


void O11y_O11yUser::setDisplayName(const utility::string_t& value)
{
    m_DisplayName = value;
    m_DisplayNameIsSet = true;
}

bool O11y_O11yUser::displayNameIsSet() const
{
    return m_DisplayNameIsSet;
}

void O11y_O11yUser::unsetDisplayName()
{
    m_DisplayNameIsSet = false;
}
utility::string_t O11y_O11yUser::getEmail() const
{
    return m_Email;
}


void O11y_O11yUser::setEmail(const utility::string_t& value)
{
    m_Email = value;
    m_EmailIsSet = true;
}

bool O11y_O11yUser::emailIsSet() const
{
    return m_EmailIsSet;
}

void O11y_O11yUser::unsetEmail()
{
    m_EmailIsSet = false;
}
utility::string_t O11y_O11yUser::getId() const
{
    return m_Id;
}


void O11y_O11yUser::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool O11y_O11yUser::idIsSet() const
{
    return m_IdIsSet;
}

void O11y_O11yUser::unsetId()
{
    m_IdIsSet = false;
}
bool O11y_O11yUser::isIsRoot() const
{
    return m_IsRoot;
}


void O11y_O11yUser::setIsRoot(bool value)
{
    m_IsRoot = value;
    m_IsRootIsSet = true;
}

bool O11y_O11yUser::isRootIsSet() const
{
    return m_IsRootIsSet;
}

void O11y_O11yUser::unsetIsRoot()
{
    m_IsRootIsSet = false;
}
utility::string_t O11y_O11yUser::getOrgId() const
{
    return m_OrgId;
}


void O11y_O11yUser::setOrgId(const utility::string_t& value)
{
    m_OrgId = value;
    m_OrgIdIsSet = true;
}

bool O11y_O11yUser::orgIdIsSet() const
{
    return m_OrgIdIsSet;
}

void O11y_O11yUser::unsetOrgId()
{
    m_OrgIdIsSet = false;
}
utility::string_t O11y_O11yUser::getStatus() const
{
    return m_Status;
}


void O11y_O11yUser::setStatus(const utility::string_t& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool O11y_O11yUser::statusIsSet() const
{
    return m_StatusIsSet;
}

void O11y_O11yUser::unsetStatus()
{
    m_StatusIsSet = false;
}
utility::datetime O11y_O11yUser::getUpdatedAt() const
{
    return m_UpdatedAt;
}


void O11y_O11yUser::setUpdatedAt(const utility::datetime& value)
{
    m_UpdatedAt = value;
    m_UpdatedAtIsSet = true;
}

bool O11y_O11yUser::updatedAtIsSet() const
{
    return m_UpdatedAtIsSet;
}

void O11y_O11yUser::unsetUpdatedAt()
{
    m_UpdatedAtIsSet = false;
}

}
}


