/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "hanzo/model/Openai_JailBreak.h"

namespace hanzo {
namespace model {

Openai_JailBreak::Openai_JailBreak()
{
    m_Detected = false;
    m_DetectedIsSet = false;
    m_Filtered = false;
    m_FilteredIsSet = false;
}

Openai_JailBreak::~Openai_JailBreak()
{
}

void Openai_JailBreak::validate()
{
    // TODO: implement validation
}

web::json::value Openai_JailBreak::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_DetectedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("detected"))] = ModelBase::toJson(m_Detected);
    }
    if(m_FilteredIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("filtered"))] = ModelBase::toJson(m_Filtered);
    }

    return val;
}

bool Openai_JailBreak::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("detected"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("detected")));
        if(!fieldValue.is_null())
        {
            bool refVal_setDetected;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDetected);
            setDetected(refVal_setDetected);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("filtered"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("filtered")));
        if(!fieldValue.is_null())
        {
            bool refVal_setFiltered;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFiltered);
            setFiltered(refVal_setFiltered);
            
        }
    }
    return ok;
}

void Openai_JailBreak::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_DetectedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("detected")), m_Detected));
    }
    if(m_FilteredIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("filtered")), m_Filtered));
    }
}

bool Openai_JailBreak::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("detected"))))
    {
        bool refVal_setDetected;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("detected"))), refVal_setDetected );
        setDetected(refVal_setDetected);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("filtered"))))
    {
        bool refVal_setFiltered;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("filtered"))), refVal_setFiltered );
        setFiltered(refVal_setFiltered);
    }
    return ok;
}


bool Openai_JailBreak::isDetected() const
{
    return m_Detected;
}


void Openai_JailBreak::setDetected(bool value)
{
    m_Detected = value;
    m_DetectedIsSet = true;
}

bool Openai_JailBreak::detectedIsSet() const
{
    return m_DetectedIsSet;
}

void Openai_JailBreak::unsetDetected()
{
    m_DetectedIsSet = false;
}
bool Openai_JailBreak::isFiltered() const
{
    return m_Filtered;
}


void Openai_JailBreak::setFiltered(bool value)
{
    m_Filtered = value;
    m_FilteredIsSet = true;
}

bool Openai_JailBreak::filteredIsSet() const
{
    return m_FilteredIsSet;
}

void Openai_JailBreak::unsetFiltered()
{
    m_FilteredIsSet = false;
}

}
}


