/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "hanzo/model/RagEmbedResult.h"

namespace hanzo {
namespace model {

RagEmbedResult::RagEmbedResult()
{
    m_Chunks = 0;
    m_ChunksIsSet = false;
    m_File_id = utility::conversions::to_string_t("");
    m_File_idIsSet = false;
    m_Filename = utility::conversions::to_string_t("");
    m_FilenameIsSet = false;
    m_Index_name = utility::conversions::to_string_t("");
    m_Index_nameIsSet = false;
    m_Store = utility::conversions::to_string_t("");
    m_StoreIsSet = false;
}

RagEmbedResult::~RagEmbedResult()
{
}

void RagEmbedResult::validate()
{
    // TODO: implement validation
}

web::json::value RagEmbedResult::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ChunksIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("chunks"))] = ModelBase::toJson(m_Chunks);
    }
    if(m_File_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("file_id"))] = ModelBase::toJson(m_File_id);
    }
    if(m_FilenameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("filename"))] = ModelBase::toJson(m_Filename);
    }
    if(m_Index_nameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("index_name"))] = ModelBase::toJson(m_Index_name);
    }
    if(m_StoreIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("store"))] = ModelBase::toJson(m_Store);
    }

    return val;
}

bool RagEmbedResult::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("chunks"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("chunks")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setChunks;
            ok &= ModelBase::fromJson(fieldValue, refVal_setChunks);
            setChunks(refVal_setChunks);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("file_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("file_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFileId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFileId);
            setFileId(refVal_setFileId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("filename"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("filename")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFilename;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFilename);
            setFilename(refVal_setFilename);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("index_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("index_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setIndexName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIndexName);
            setIndexName(refVal_setIndexName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("store"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("store")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStore;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStore);
            setStore(refVal_setStore);
            
        }
    }
    return ok;
}

void RagEmbedResult::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ChunksIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("chunks")), m_Chunks));
    }
    if(m_File_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("file_id")), m_File_id));
    }
    if(m_FilenameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("filename")), m_Filename));
    }
    if(m_Index_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("index_name")), m_Index_name));
    }
    if(m_StoreIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("store")), m_Store));
    }
}

bool RagEmbedResult::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("chunks"))))
    {
        int32_t refVal_setChunks;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("chunks"))), refVal_setChunks );
        setChunks(refVal_setChunks);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("file_id"))))
    {
        utility::string_t refVal_setFileId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("file_id"))), refVal_setFileId );
        setFileId(refVal_setFileId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("filename"))))
    {
        utility::string_t refVal_setFilename;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("filename"))), refVal_setFilename );
        setFilename(refVal_setFilename);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("index_name"))))
    {
        utility::string_t refVal_setIndexName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("index_name"))), refVal_setIndexName );
        setIndexName(refVal_setIndexName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("store"))))
    {
        utility::string_t refVal_setStore;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("store"))), refVal_setStore );
        setStore(refVal_setStore);
    }
    return ok;
}


int32_t RagEmbedResult::getChunks() const
{
    return m_Chunks;
}


void RagEmbedResult::setChunks(int32_t value)
{
    m_Chunks = value;
    m_ChunksIsSet = true;
}

bool RagEmbedResult::chunksIsSet() const
{
    return m_ChunksIsSet;
}

void RagEmbedResult::unsetChunks()
{
    m_ChunksIsSet = false;
}
utility::string_t RagEmbedResult::getFileId() const
{
    return m_File_id;
}


void RagEmbedResult::setFileId(const utility::string_t& value)
{
    m_File_id = value;
    m_File_idIsSet = true;
}

bool RagEmbedResult::fileIdIsSet() const
{
    return m_File_idIsSet;
}

void RagEmbedResult::unsetFile_id()
{
    m_File_idIsSet = false;
}
utility::string_t RagEmbedResult::getFilename() const
{
    return m_Filename;
}


void RagEmbedResult::setFilename(const utility::string_t& value)
{
    m_Filename = value;
    m_FilenameIsSet = true;
}

bool RagEmbedResult::filenameIsSet() const
{
    return m_FilenameIsSet;
}

void RagEmbedResult::unsetFilename()
{
    m_FilenameIsSet = false;
}
utility::string_t RagEmbedResult::getIndexName() const
{
    return m_Index_name;
}


void RagEmbedResult::setIndexName(const utility::string_t& value)
{
    m_Index_name = value;
    m_Index_nameIsSet = true;
}

bool RagEmbedResult::indexNameIsSet() const
{
    return m_Index_nameIsSet;
}

void RagEmbedResult::unsetIndex_name()
{
    m_Index_nameIsSet = false;
}
utility::string_t RagEmbedResult::getStore() const
{
    return m_Store;
}


void RagEmbedResult::setStore(const utility::string_t& value)
{
    m_Store = value;
    m_StoreIsSet = true;
}

bool RagEmbedResult::storeIsSet() const
{
    return m_StoreIsSet;
}

void RagEmbedResult::unsetStore()
{
    m_StoreIsSet = false;
}

}
}


