/**
 * Hanzo Cloud API
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "hanzo/model/ReferrerRow.h"

namespace hanzo {
namespace model {

ReferrerRow::ReferrerRow()
{
    m_AccruedCents = 0;
    m_AccruedCentsIsSet = false;
    m_Code = utility::conversions::to_string_t("");
    m_CodeIsSet = false;
    m_Org = utility::conversions::to_string_t("");
    m_OrgIsSet = false;
    m_PendingCents = 0;
    m_PendingCentsIsSet = false;
    m_ReferredCount = 0;
    m_ReferredCountIsSet = false;
    m_Status = utility::conversions::to_string_t("");
    m_StatusIsSet = false;
}

ReferrerRow::~ReferrerRow()
{
}

void ReferrerRow::validate()
{
    // TODO: implement validation
}

web::json::value ReferrerRow::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_AccruedCentsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("accruedCents"))] = ModelBase::toJson(m_AccruedCents);
    }
    if(m_CodeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("code"))] = ModelBase::toJson(m_Code);
    }
    if(m_OrgIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("org"))] = ModelBase::toJson(m_Org);
    }
    if(m_PendingCentsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("pendingCents"))] = ModelBase::toJson(m_PendingCents);
    }
    if(m_ReferredCountIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("referredCount"))] = ModelBase::toJson(m_ReferredCount);
    }
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }

    return val;
}

bool ReferrerRow::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("accruedCents"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("accruedCents")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setAccruedCents;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAccruedCents);
            setAccruedCents(refVal_setAccruedCents);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("code")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCode);
            setCode(refVal_setCode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("org"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("org")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOrg;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOrg);
            setOrg(refVal_setOrg);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("pendingCents"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("pendingCents")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPendingCents;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPendingCents);
            setPendingCents(refVal_setPendingCents);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("referredCount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("referredCount")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setReferredCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setReferredCount);
            setReferredCount(refVal_setReferredCount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    return ok;
}

void ReferrerRow::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_AccruedCentsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("accruedCents")), m_AccruedCents));
    }
    if(m_CodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("code")), m_Code));
    }
    if(m_OrgIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("org")), m_Org));
    }
    if(m_PendingCentsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("pendingCents")), m_PendingCents));
    }
    if(m_ReferredCountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("referredCount")), m_ReferredCount));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
}

bool ReferrerRow::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("accruedCents"))))
    {
        int32_t refVal_setAccruedCents;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("accruedCents"))), refVal_setAccruedCents );
        setAccruedCents(refVal_setAccruedCents);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        utility::string_t refVal_setCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("code"))), refVal_setCode );
        setCode(refVal_setCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("org"))))
    {
        utility::string_t refVal_setOrg;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("org"))), refVal_setOrg );
        setOrg(refVal_setOrg);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("pendingCents"))))
    {
        int32_t refVal_setPendingCents;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("pendingCents"))), refVal_setPendingCents );
        setPendingCents(refVal_setPendingCents);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("referredCount"))))
    {
        int32_t refVal_setReferredCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("referredCount"))), refVal_setReferredCount );
        setReferredCount(refVal_setReferredCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    return ok;
}


int32_t ReferrerRow::getAccruedCents() const
{
    return m_AccruedCents;
}


void ReferrerRow::setAccruedCents(int32_t value)
{
    m_AccruedCents = value;
    m_AccruedCentsIsSet = true;
}

bool ReferrerRow::accruedCentsIsSet() const
{
    return m_AccruedCentsIsSet;
}

void ReferrerRow::unsetAccruedCents()
{
    m_AccruedCentsIsSet = false;
}
utility::string_t ReferrerRow::getCode() const
{
    return m_Code;
}


void ReferrerRow::setCode(const utility::string_t& value)
{
    m_Code = value;
    m_CodeIsSet = true;
}

bool ReferrerRow::codeIsSet() const
{
    return m_CodeIsSet;
}

void ReferrerRow::unsetCode()
{
    m_CodeIsSet = false;
}
utility::string_t ReferrerRow::getOrg() const
{
    return m_Org;
}


void ReferrerRow::setOrg(const utility::string_t& value)
{
    m_Org = value;
    m_OrgIsSet = true;
}

bool ReferrerRow::orgIsSet() const
{
    return m_OrgIsSet;
}

void ReferrerRow::unsetOrg()
{
    m_OrgIsSet = false;
}
int32_t ReferrerRow::getPendingCents() const
{
    return m_PendingCents;
}


void ReferrerRow::setPendingCents(int32_t value)
{
    m_PendingCents = value;
    m_PendingCentsIsSet = true;
}

bool ReferrerRow::pendingCentsIsSet() const
{
    return m_PendingCentsIsSet;
}

void ReferrerRow::unsetPendingCents()
{
    m_PendingCentsIsSet = false;
}
int32_t ReferrerRow::getReferredCount() const
{
    return m_ReferredCount;
}


void ReferrerRow::setReferredCount(int32_t value)
{
    m_ReferredCount = value;
    m_ReferredCountIsSet = true;
}

bool ReferrerRow::referredCountIsSet() const
{
    return m_ReferredCountIsSet;
}

void ReferrerRow::unsetReferredCount()
{
    m_ReferredCountIsSet = false;
}
utility::string_t ReferrerRow::getStatus() const
{
    return m_Status;
}


void ReferrerRow::setStatus(const utility::string_t& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool ReferrerRow::statusIsSet() const
{
    return m_StatusIsSet;
}

void ReferrerRow::unsetStatus()
{
    m_StatusIsSet = false;
}

}
}


