/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "hanzo/model/Request.h"

namespace hanzo {
namespace model {

Request::Request()
{
    m_DoctypesIsSet = false;
    m_Index = utility::conversions::to_string_t("");
    m_IndexIsSet = false;
    m_Limit = 0;
    m_LimitIsSet = false;
    m_Mode = utility::conversions::to_string_t("");
    m_ModeIsSet = false;
    m_Offset = 0;
    m_OffsetIsSet = false;
    m_Project = utility::conversions::to_string_t("");
    m_ProjectIsSet = false;
    m_Query = utility::conversions::to_string_t("");
    m_QueryIsSet = false;
}

Request::~Request()
{
}

void Request::validate()
{
    // TODO: implement validation
}

web::json::value Request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_DoctypesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("doctypes"))] = ModelBase::toJson(m_Doctypes);
    }
    if(m_IndexIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("index"))] = ModelBase::toJson(m_Index);
    }
    if(m_LimitIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("limit"))] = ModelBase::toJson(m_Limit);
    }
    if(m_ModeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("mode"))] = ModelBase::toJson(m_Mode);
    }
    if(m_OffsetIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("offset"))] = ModelBase::toJson(m_Offset);
    }
    if(m_ProjectIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("project"))] = ModelBase::toJson(m_Project);
    }
    if(m_QueryIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("query"))] = ModelBase::toJson(m_Query);
    }

    return val;
}

bool Request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("doctypes"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("doctypes")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setDoctypes;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDoctypes);
            setDoctypes(refVal_setDoctypes);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("index"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("index")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setIndex;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIndex);
            setIndex(refVal_setIndex);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("limit"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("limit")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setLimit;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLimit);
            setLimit(refVal_setLimit);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("mode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("mode")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMode);
            setMode(refVal_setMode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("offset"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("offset")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setOffset;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOffset);
            setOffset(refVal_setOffset);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("project"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("project")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProject;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProject);
            setProject(refVal_setProject);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("query"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("query")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setQuery;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQuery);
            setQuery(refVal_setQuery);
            
        }
    }
    return ok;
}

void Request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_DoctypesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("doctypes")), m_Doctypes));
    }
    if(m_IndexIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("index")), m_Index));
    }
    if(m_LimitIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("limit")), m_Limit));
    }
    if(m_ModeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("mode")), m_Mode));
    }
    if(m_OffsetIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("offset")), m_Offset));
    }
    if(m_ProjectIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("project")), m_Project));
    }
    if(m_QueryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("query")), m_Query));
    }
}

bool Request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("doctypes"))))
    {
        std::vector<utility::string_t> refVal_setDoctypes;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("doctypes"))), refVal_setDoctypes );
        setDoctypes(refVal_setDoctypes);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("index"))))
    {
        utility::string_t refVal_setIndex;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("index"))), refVal_setIndex );
        setIndex(refVal_setIndex);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("limit"))))
    {
        int32_t refVal_setLimit;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("limit"))), refVal_setLimit );
        setLimit(refVal_setLimit);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("mode"))))
    {
        utility::string_t refVal_setMode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("mode"))), refVal_setMode );
        setMode(refVal_setMode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("offset"))))
    {
        int32_t refVal_setOffset;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("offset"))), refVal_setOffset );
        setOffset(refVal_setOffset);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("project"))))
    {
        utility::string_t refVal_setProject;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("project"))), refVal_setProject );
        setProject(refVal_setProject);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("query"))))
    {
        utility::string_t refVal_setQuery;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("query"))), refVal_setQuery );
        setQuery(refVal_setQuery);
    }
    return ok;
}


std::vector<utility::string_t> Request::getDoctypes() const
{
    return m_Doctypes;
}


void Request::setDoctypes(const std::vector<utility::string_t>& value)
{
    m_Doctypes = value;
    m_DoctypesIsSet = true;
}

bool Request::doctypesIsSet() const
{
    return m_DoctypesIsSet;
}

void Request::unsetDoctypes()
{
    m_DoctypesIsSet = false;
}
utility::string_t Request::getIndex() const
{
    return m_Index;
}


void Request::setIndex(const utility::string_t& value)
{
    m_Index = value;
    m_IndexIsSet = true;
}

bool Request::indexIsSet() const
{
    return m_IndexIsSet;
}

void Request::unsetIndex()
{
    m_IndexIsSet = false;
}
int32_t Request::getLimit() const
{
    return m_Limit;
}


void Request::setLimit(int32_t value)
{
    m_Limit = value;
    m_LimitIsSet = true;
}

bool Request::limitIsSet() const
{
    return m_LimitIsSet;
}

void Request::unsetLimit()
{
    m_LimitIsSet = false;
}
utility::string_t Request::getMode() const
{
    return m_Mode;
}


void Request::setMode(const utility::string_t& value)
{
    m_Mode = value;
    m_ModeIsSet = true;
}

bool Request::modeIsSet() const
{
    return m_ModeIsSet;
}

void Request::unsetMode()
{
    m_ModeIsSet = false;
}
int32_t Request::getOffset() const
{
    return m_Offset;
}


void Request::setOffset(int32_t value)
{
    m_Offset = value;
    m_OffsetIsSet = true;
}

bool Request::offsetIsSet() const
{
    return m_OffsetIsSet;
}

void Request::unsetOffset()
{
    m_OffsetIsSet = false;
}
utility::string_t Request::getProject() const
{
    return m_Project;
}


void Request::setProject(const utility::string_t& value)
{
    m_Project = value;
    m_ProjectIsSet = true;
}

bool Request::projectIsSet() const
{
    return m_ProjectIsSet;
}

void Request::unsetProject()
{
    m_ProjectIsSet = false;
}
utility::string_t Request::getQuery() const
{
    return m_Query;
}


void Request::setQuery(const utility::string_t& value)
{
    m_Query = value;
    m_QueryIsSet = true;
}

bool Request::queryIsSet() const
{
    return m_QueryIsSet;
}

void Request::unsetQuery()
{
    m_QueryIsSet = false;
}

}
}


