/**
 * Hanzo Cloud API
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "hanzo/model/Ruleset.h"

namespace hanzo {
namespace model {

Ruleset::Ruleset()
{
    m_Rules = 0;
    m_RulesIsSet = false;
    m_Status = utility::conversions::to_string_t("");
    m_StatusIsSet = false;
}

Ruleset::~Ruleset()
{
}

void Ruleset::validate()
{
    // TODO: implement validation
}

web::json::value Ruleset::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_RulesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("rules"))] = ModelBase::toJson(m_Rules);
    }
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }

    return val;
}

bool Ruleset::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("rules"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("rules")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setRules;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRules);
            setRules(refVal_setRules);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    return ok;
}

void Ruleset::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_RulesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("rules")), m_Rules));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
}

bool Ruleset::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("rules"))))
    {
        int32_t refVal_setRules;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("rules"))), refVal_setRules );
        setRules(refVal_setRules);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    return ok;
}


int32_t Ruleset::getRules() const
{
    return m_Rules;
}


void Ruleset::setRules(int32_t value)
{
    m_Rules = value;
    m_RulesIsSet = true;
}

bool Ruleset::rulesIsSet() const
{
    return m_RulesIsSet;
}

void Ruleset::unsetRules()
{
    m_RulesIsSet = false;
}
utility::string_t Ruleset::getStatus() const
{
    return m_Status;
}


void Ruleset::setStatus(const utility::string_t& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool Ruleset::statusIsSet() const
{
    return m_StatusIsSet;
}

void Ruleset::unsetStatus()
{
    m_StatusIsSet = false;
}

}
}


