/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "hanzo/model/RulesOut.h"

namespace hanzo {
namespace model {

RulesOut::RulesOut()
{
    m_RulesIsSet = false;
}

RulesOut::~RulesOut()
{
}

void RulesOut::validate()
{
    // TODO: implement validation
}

web::json::value RulesOut::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_RulesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("rules"))] = ModelBase::toJson(m_Rules);
    }

    return val;
}

bool RulesOut::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("rules"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("rules")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Rule>> refVal_setRules;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRules);
            setRules(refVal_setRules);
            
        }
    }
    return ok;
}

void RulesOut::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_RulesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("rules")), m_Rules));
    }
}

bool RulesOut::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("rules"))))
    {
        std::vector<std::shared_ptr<Rule>> refVal_setRules;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("rules"))), refVal_setRules );
        setRules(refVal_setRules);
    }
    return ok;
}


std::vector<std::shared_ptr<Rule>> RulesOut::getRules() const
{
    return m_Rules;
}


void RulesOut::setRules(const std::vector<std::shared_ptr<Rule>>& value)
{
    m_Rules = value;
    m_RulesIsSet = true;
}

bool RulesOut::rulesIsSet() const
{
    return m_RulesIsSet;
}

void RulesOut::unsetRules()
{
    m_RulesIsSet = false;
}

}
}


