/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "hanzo/model/Search_SearchQueryWithIndex_federationOptions.h"

namespace hanzo {
namespace model {

Search_SearchQueryWithIndex_federationOptions::Search_SearchQueryWithIndex_federationOptions()
{
    m_Weight = 0.0;
    m_WeightIsSet = false;
}

Search_SearchQueryWithIndex_federationOptions::~Search_SearchQueryWithIndex_federationOptions()
{
}

void Search_SearchQueryWithIndex_federationOptions::validate()
{
    // TODO: implement validation
}

web::json::value Search_SearchQueryWithIndex_federationOptions::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_WeightIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("weight"))] = ModelBase::toJson(m_Weight);
    }

    return val;
}

bool Search_SearchQueryWithIndex_federationOptions::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("weight"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("weight")));
        if(!fieldValue.is_null())
        {
            double refVal_setWeight;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWeight);
            setWeight(refVal_setWeight);
            
        }
    }
    return ok;
}

void Search_SearchQueryWithIndex_federationOptions::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_WeightIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("weight")), m_Weight));
    }
}

bool Search_SearchQueryWithIndex_federationOptions::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("weight"))))
    {
        double refVal_setWeight;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("weight"))), refVal_setWeight );
        setWeight(refVal_setWeight);
    }
    return ok;
}


double Search_SearchQueryWithIndex_federationOptions::getWeight() const
{
    return m_Weight;
}


void Search_SearchQueryWithIndex_federationOptions::setWeight(double value)
{
    m_Weight = value;
    m_WeightIsSet = true;
}

bool Search_SearchQueryWithIndex_federationOptions::weightIsSet() const
{
    return m_WeightIsSet;
}

void Search_SearchQueryWithIndex_federationOptions::unsetWeight()
{
    m_WeightIsSet = false;
}

}
}


