/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/*
 * Analytics_getPageviews_200_response_compare.h
 *
 * 
 */

#ifndef HANZO_MODEL_Analytics_getPageviews_200_response_compare_H_
#define HANZO_MODEL_Analytics_getPageviews_200_response_compare_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "hanzo/model/Analytics_PageviewSeries.h"
#include <vector>

namespace hanzo {
namespace model {

class Analytics_PageviewSeries;


class  Analytics_getPageviews_200_response_compare
    : public ModelBase
{
public:
    Analytics_getPageviews_200_response_compare();
    virtual ~Analytics_getPageviews_200_response_compare();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Analytics_getPageviews_200_response_compare members


    std::vector<std::shared_ptr<Analytics_PageviewSeries>> getPageviews() const;
    bool pageviewsIsSet() const;
    void unsetPageviews();
    void setPageviews(const std::vector<std::shared_ptr<Analytics_PageviewSeries>>& value);

    std::vector<std::shared_ptr<Analytics_PageviewSeries>> getSessions() const;
    bool sessionsIsSet() const;
    void unsetSessions();
    void setSessions(const std::vector<std::shared_ptr<Analytics_PageviewSeries>>& value);

    utility::datetime getStartDate() const;
    bool startDateIsSet() const;
    void unsetStartDate();
    void setStartDate(const utility::datetime& value);

    utility::datetime getEndDate() const;
    bool endDateIsSet() const;
    void unsetEndDate();
    void setEndDate(const utility::datetime& value);


protected:
    std::vector<std::shared_ptr<Analytics_PageviewSeries>> m_Pageviews;
    bool m_PageviewsIsSet;

    std::vector<std::shared_ptr<Analytics_PageviewSeries>> m_Sessions;
    bool m_SessionsIsSet;

    utility::datetime m_StartDate;
    bool m_StartDateIsSet;

    utility::datetime m_EndDate;
    bool m_EndDateIsSet;

};


}
}

#endif /* HANZO_MODEL_Analytics_getPageviews_200_response_compare_H_ */
