/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CaptableRoundTotals.h
 *
 * 
 */

#ifndef HANZO_MODEL_CaptableRoundTotals_H_
#define HANZO_MODEL_CaptableRoundTotals_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"


namespace hanzo {
namespace model {



class  CaptableRoundTotals
    : public ModelBase
{
public:
    CaptableRoundTotals();
    virtual ~CaptableRoundTotals();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// CaptableRoundTotals members


    /// <summary>
    /// Count is how many rounds the company has recorded.
    /// </summary>
    int32_t getCount() const;
    bool countIsSet() const;
    void unsetCount();
    void setCount(int32_t value);

    /// <summary>
    /// TotalRaised is the sum of every round&#39;s raised amount.
    /// </summary>
    double getTotalRaised() const;
    bool totalRaisedIsSet() const;
    void unsetTotalRaised();
    void setTotalRaised(double value);


protected:
    int32_t m_Count;
    bool m_CountIsSet;

    double m_TotalRaised;
    bool m_TotalRaisedIsSet;

};


}
}

#endif /* HANZO_MODEL_CaptableRoundTotals_H_ */
