/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/*
 * Cloud_ingestOut.h
 *
 * 
 */

#ifndef HANZO_MODEL_Cloud_ingestOut_H_
#define HANZO_MODEL_Cloud_ingestOut_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace hanzo {
namespace model {



class  Cloud_ingestOut
    : public ModelBase
{
public:
    Cloud_ingestOut();
    virtual ~Cloud_ingestOut();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Cloud_ingestOut members


    /// <summary>
    /// AttemptsIngested is how many attempt versions this call appended.
    /// </summary>
    int32_t getAttemptsIngested() const;
    bool attemptsIngestedIsSet() const;
    void unsetAttempts_ingested();
    void setAttemptsIngested(int32_t value);

    /// <summary>
    /// AttemptsRetained is the full versioned attempt history the store now holds.
    /// </summary>
    int32_t getAttemptsRetained() const;
    bool attemptsRetainedIsSet() const;
    void unsetAttempts_retained();
    void setAttemptsRetained(int32_t value);

    /// <summary>
    /// CanonicalAttempts is the deduped attempt count the store now holds.
    /// </summary>
    int32_t getCanonicalAttempts() const;
    bool canonicalAttemptsIsSet() const;
    void unsetCanonical_attempts();
    void setCanonicalAttempts(int32_t value);

    /// <summary>
    /// CanonicalExperiments is the deduped experiment count the store now holds.
    /// </summary>
    int32_t getCanonicalExperiments() const;
    bool canonicalExperimentsIsSet() const;
    void unsetCanonical_experiments();
    void setCanonicalExperiments(int32_t value);

    /// <summary>
    /// ExperimentsIngested is how many experiment versions this call appended.
    /// </summary>
    int32_t getExperimentsIngested() const;
    bool experimentsIngestedIsSet() const;
    void unsetExperiments_ingested();
    void setExperimentsIngested(int32_t value);

    /// <summary>
    /// ExperimentsRetained is the full versioned experiment history the store now holds.
    /// </summary>
    int32_t getExperimentsRetained() const;
    bool experimentsRetainedIsSet() const;
    void unsetExperiments_retained();
    void setExperimentsRetained(int32_t value);

    /// <summary>
    /// Project is the project the batch was filed under — the SERVER&#39;s value, never the body&#39;s.
    /// </summary>
    utility::string_t getProject() const;
    bool projectIsSet() const;
    void unsetProject();
    void setProject(const utility::string_t& value);

    /// <summary>
    /// RolledUp is false when the OLAP roll-up was skipped; the SQLite write still stands.
    /// </summary>
    bool isRolledUp() const;
    bool rolledUpIsSet() const;
    void unsetRolled_up();
    void setRolledUp(bool value);


protected:
    int32_t m_Attempts_ingested;
    bool m_Attempts_ingestedIsSet;

    int32_t m_Attempts_retained;
    bool m_Attempts_retainedIsSet;

    int32_t m_Canonical_attempts;
    bool m_Canonical_attemptsIsSet;

    int32_t m_Canonical_experiments;
    bool m_Canonical_experimentsIsSet;

    int32_t m_Experiments_ingested;
    bool m_Experiments_ingestedIsSet;

    int32_t m_Experiments_retained;
    bool m_Experiments_retainedIsSet;

    utility::string_t m_Project;
    bool m_ProjectIsSet;

    bool m_Rolled_up;
    bool m_Rolled_upIsSet;

};


}
}

#endif /* HANZO_MODEL_Cloud_ingestOut_H_ */
