/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/*
 * Cloud_NameIn.h
 *
 * 
 */

#ifndef HANZO_MODEL_Cloud_NameIn_H_
#define HANZO_MODEL_Cloud_NameIn_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace hanzo {
namespace model {



class  Cloud_NameIn
    : public ModelBase
{
public:
    Cloud_NameIn();
    virtual ~Cloud_NameIn();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Cloud_NameIn members


    /// <summary>
    /// Name is the app, from the path.
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    /// <summary>
    /// Scope \&quot;host\&quot; applies here only; default \&quot;fleet\&quot; applies everywhere.
    /// </summary>
    utility::string_t getScope() const;
    bool scopeIsSet() const;
    void unsetScope();
    void setScope(const utility::string_t& value);


protected:
    utility::string_t m_Name;
    bool m_NameIsSet;

    utility::string_t m_Scope;
    bool m_ScopeIsSet;

};


}
}

#endif /* HANZO_MODEL_Cloud_NameIn_H_ */
