/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/*
 * Cloud_usageAnalyticsView.h
 *
 * 
 */

#ifndef HANZO_MODEL_Cloud_usageAnalyticsView_H_
#define HANZO_MODEL_Cloud_usageAnalyticsView_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include "hanzo/model/Cloud_ProviderBreakdown.h"
#include <cpprest/details/basic_types.h>
#include "hanzo/model/Cloud_usageScope.h"

namespace hanzo {
namespace model {

class Cloud_ProviderBreakdown;
class Cloud_usageScope;


class  Cloud_usageAnalyticsView
    : public ModelBase
{
public:
    Cloud_usageAnalyticsView();
    virtual ~Cloud_usageAnalyticsView();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Cloud_usageAnalyticsView members


    /// <summary>
    /// End is the window&#39;s exclusive end, RFC3339 UTC.
    /// </summary>
    utility::string_t getEnd() const;
    bool endIsSet() const;
    void unsetEnd();
    void setEnd(const utility::string_t& value);

    /// <summary>
    /// Export is whether the resolved plan allows exporting these rows.
    /// </summary>
    bool isRExport() const;
    bool rExportIsSet() const;
    void unsetr_export();
    void setRExport(bool value);

    /// <summary>
    /// Plan echoes the plan id the entitlement was resolved from.
    /// </summary>
    utility::string_t getPlan() const;
    bool planIsSet() const;
    void unsetPlan();
    void setPlan(const utility::string_t& value);

    /// <summary>
    /// Providers is the per-provider roll-up over the window.
    /// </summary>
    std::shared_ptr<Cloud_ProviderBreakdown> getProviders() const;
    bool providersIsSet() const;
    void unsetProviders();
    void setProviders(const std::shared_ptr<Cloud_ProviderBreakdown>& value);

    /// <summary>
    /// Range is the window label that was served, which is what was asked for.
    /// </summary>
    utility::string_t getRange() const;
    bool rangeIsSet() const;
    void unsetRange();
    void setRange(const utility::string_t& value);

    /// <summary>
    /// RetentionDays is how far back the resolved plan allows reading.
    /// </summary>
    int32_t getRetentionDays() const;
    bool retentionDaysIsSet() const;
    void unsetRetentionDays();
    void setRetentionDays(int32_t value);

    /// <summary>
    /// Scope is the tenant the rows were read under — the validated principal&#39;s org.
    /// </summary>
    std::shared_ptr<Cloud_usageScope> getScope() const;
    bool scopeIsSet() const;
    void unsetScope();
    void setScope(const std::shared_ptr<Cloud_usageScope>& value);

    /// <summary>
    /// Start is the window&#39;s inclusive start, RFC3339 UTC, AFTER the retention clamp — so it may be later than the start that was asked for.
    /// </summary>
    utility::string_t getStart() const;
    bool startIsSet() const;
    void unsetStart();
    void setStart(const utility::string_t& value);


protected:
    utility::string_t m_End;
    bool m_EndIsSet;

    bool m_r_export;
    bool m_r_exportIsSet;

    utility::string_t m_Plan;
    bool m_PlanIsSet;

    std::shared_ptr<Cloud_ProviderBreakdown> m_Providers;
    bool m_ProvidersIsSet;

    utility::string_t m_Range;
    bool m_RangeIsSet;

    int32_t m_RetentionDays;
    bool m_RetentionDaysIsSet;

    std::shared_ptr<Cloud_usageScope> m_Scope;
    bool m_ScopeIsSet;

    utility::string_t m_Start;
    bool m_StartIsSet;

};


}
}

#endif /* HANZO_MODEL_Cloud_usageAnalyticsView_H_ */
