/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/*
 * Cloud_enablementBoard.h
 *
 * 
 */

#ifndef HANZO_MODEL_Cloud_enablementBoard_H_
#define HANZO_MODEL_Cloud_enablementBoard_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>
#include "hanzo/model/Cloud_userEnablementItem.h"

namespace hanzo {
namespace model {

class Cloud_userEnablementItem;


class  Cloud_enablementBoard
    : public ModelBase
{
public:
    Cloud_enablementBoard();
    virtual ~Cloud_enablementBoard();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Cloud_enablementBoard members


    /// <summary>
    /// Betas are the subset of Items the caller&#39;s org may still opt into.
    /// </summary>
    std::vector<std::shared_ptr<Cloud_userEnablementItem>> getBetas() const;
    bool betasIsSet() const;
    void unsetBetas();
    void setBetas(const std::vector<std::shared_ptr<Cloud_userEnablementItem>>& value);

    /// <summary>
    /// Items is every managed item, each resolved for the caller&#39;s org.
    /// </summary>
    std::vector<std::shared_ptr<Cloud_userEnablementItem>> getItems() const;
    bool itemsIsSet() const;
    void unsetItems();
    void setItems(const std::vector<std::shared_ptr<Cloud_userEnablementItem>>& value);

    /// <summary>
    /// Org is the org this view was resolved for; empty for a caller with no validated principal, who sees only the generally-available items.
    /// </summary>
    utility::string_t getOrg() const;
    bool orgIsSet() const;
    void unsetOrg();
    void setOrg(const utility::string_t& value);


protected:
    std::vector<std::shared_ptr<Cloud_userEnablementItem>> m_Betas;
    bool m_BetasIsSet;

    std::vector<std::shared_ptr<Cloud_userEnablementItem>> m_Items;
    bool m_ItemsIsSet;

    utility::string_t m_Org;
    bool m_OrgIsSet;

};


}
}

#endif /* HANZO_MODEL_Cloud_enablementBoard_H_ */
