/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/*
 * Cloud_githubPagesView.h
 *
 * 
 */

#ifndef HANZO_MODEL_Cloud_githubPagesView_H_
#define HANZO_MODEL_Cloud_githubPagesView_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include "hanzo/model/Cloud_githubPagesSource.h"
#include <cpprest/details/basic_types.h>

namespace hanzo {
namespace model {

class Cloud_githubPagesSource;


class  Cloud_githubPagesView
    : public ModelBase
{
public:
    Cloud_githubPagesView();
    virtual ~Cloud_githubPagesView();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Cloud_githubPagesView members


    /// <summary>
    /// BuildType is the builder in use: \&quot;legacy\&quot; (branch source) or \&quot;workflow\&quot;.
    /// </summary>
    utility::string_t getBuildType() const;
    bool buildTypeIsSet() const;
    void unsetBuildType();
    void setBuildType(const utility::string_t& value);

    /// <summary>
    /// CNAME is the custom domain, absent when none is set.
    /// </summary>
    utility::string_t getCname() const;
    bool cnameIsSet() const;
    void unsetCname();
    void setCname(const utility::string_t& value);

    /// <summary>
    /// Custom404 is whether the repo ships its own 404 page.
    /// </summary>
    bool isCustom404() const;
    bool custom404IsSet() const;
    void unsetCustom404();
    void setCustom404(bool value);

    /// <summary>
    /// HTTPSEnforced is GitHub&#39;s enforce-HTTPS bit.
    /// </summary>
    bool isHttpsEnforced() const;
    bool httpsEnforcedIsSet() const;
    void unsetHttpsEnforced();
    void setHttpsEnforced(bool value);

    /// <summary>
    /// Repo is the repository the site belongs to.
    /// </summary>
    utility::string_t getRepo() const;
    bool repoIsSet() const;
    void unsetRepo();
    void setRepo(const utility::string_t& value);

    /// <summary>
    /// Source is the branch + path the site builds from. Absent under \&quot;workflow\&quot;.
    /// </summary>
    std::shared_ptr<Cloud_githubPagesSource> getSource() const;
    bool sourceIsSet() const;
    void unsetSource();
    void setSource(const std::shared_ptr<Cloud_githubPagesSource>& value);

    /// <summary>
    /// Status is GitHub&#39;s build state: \&quot;built\&quot;, \&quot;building\&quot; or \&quot;errored\&quot;. Absent before the first build.
    /// </summary>
    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const utility::string_t& value);

    /// <summary>
    /// URL is the live site (GitHub&#39;s html_url).
    /// </summary>
    utility::string_t getUrl() const;
    bool urlIsSet() const;
    void unsetUrl();
    void setUrl(const utility::string_t& value);


protected:
    utility::string_t m_BuildType;
    bool m_BuildTypeIsSet;

    utility::string_t m_Cname;
    bool m_CnameIsSet;

    bool m_Custom404;
    bool m_Custom404IsSet;

    bool m_HttpsEnforced;
    bool m_HttpsEnforcedIsSet;

    utility::string_t m_Repo;
    bool m_RepoIsSet;

    std::shared_ptr<Cloud_githubPagesSource> m_Source;
    bool m_SourceIsSet;

    utility::string_t m_Status;
    bool m_StatusIsSet;

    utility::string_t m_Url;
    bool m_UrlIsSet;

};


}
}

#endif /* HANZO_MODEL_Cloud_githubPagesView_H_ */
