/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/*
 * Cloud_PnL.h
 *
 * 
 */

#ifndef HANZO_MODEL_Cloud_PnL_H_
#define HANZO_MODEL_Cloud_PnL_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include "hanzo/model/Cloud_PnLLine.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace hanzo {
namespace model {

class Cloud_PnLLine;


class  Cloud_PnL
    : public ModelBase
{
public:
    Cloud_PnL();
    virtual ~Cloud_PnL();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Cloud_PnL members


    std::vector<std::shared_ptr<Cloud_PnLLine>> getExpense() const;
    bool expenseIsSet() const;
    void unsetExpense();
    void setExpense(const std::vector<std::shared_ptr<Cloud_PnLLine>>& value);

    utility::string_t getFrom() const;
    bool fromIsSet() const;
    void unsetFrom();
    void setFrom(const utility::string_t& value);

    std::vector<std::shared_ptr<Cloud_PnLLine>> getIncome() const;
    bool incomeIsSet() const;
    void unsetIncome();
    void setIncome(const std::vector<std::shared_ptr<Cloud_PnLLine>>& value);

    /// <summary>
    /// TotalIncome − TotalExpense
    /// </summary>
    int32_t getNetIncome() const;
    bool netIncomeIsSet() const;
    void unsetNetIncome();
    void setNetIncome(int32_t value);

    utility::string_t getTo() const;
    bool toIsSet() const;
    void unsetTo();
    void setTo(const utility::string_t& value);

    int32_t getTotalExpense() const;
    bool totalExpenseIsSet() const;
    void unsetTotalExpense();
    void setTotalExpense(int32_t value);

    int32_t getTotalIncome() const;
    bool totalIncomeIsSet() const;
    void unsetTotalIncome();
    void setTotalIncome(int32_t value);


protected:
    std::vector<std::shared_ptr<Cloud_PnLLine>> m_Expense;
    bool m_ExpenseIsSet;

    utility::string_t m_From;
    bool m_FromIsSet;

    std::vector<std::shared_ptr<Cloud_PnLLine>> m_Income;
    bool m_IncomeIsSet;

    int32_t m_NetIncome;
    bool m_NetIncomeIsSet;

    utility::string_t m_To;
    bool m_ToIsSet;

    int32_t m_TotalExpense;
    bool m_TotalExpenseIsSet;

    int32_t m_TotalIncome;
    bool m_TotalIncomeIsSet;

};


}
}

#endif /* HANZO_MODEL_Cloud_PnL_H_ */
