/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/*
 * Cloud_waitlistBoostRequest.h
 *
 * 
 */

#ifndef HANZO_MODEL_Cloud_waitlistBoostRequest_H_
#define HANZO_MODEL_Cloud_waitlistBoostRequest_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace hanzo {
namespace model {



class  Cloud_waitlistBoostRequest
    : public ModelBase
{
public:
    Cloud_waitlistBoostRequest();
    virtual ~Cloud_waitlistBoostRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Cloud_waitlistBoostRequest members


    /// <summary>
    /// Email identifies the entry to boost. Either this or RefCode is required.
    /// </summary>
    utility::string_t getEmail() const;
    bool emailIsSet() const;
    void unsetEmail();
    void setEmail(const utility::string_t& value);

    /// <summary>
    /// Points is how many points to award. Must be positive — this seam exists to move someone UP toward the cutoff.
    /// </summary>
    int32_t getPoints() const;
    bool pointsIsSet() const;
    void unsetPoints();
    void setPoints(int32_t value);

    /// <summary>
    /// Reason is the operator&#39;s justification. Not sent to the engine; it is recorded on the audit row, which is the point of asking for it.
    /// </summary>
    utility::string_t getReason() const;
    bool reasonIsSet() const;
    void unsetReason();
    void setReason(const utility::string_t& value);

    /// <summary>
    /// RefCode identifies the entry by its referral code, when the email is unknown.
    /// </summary>
    utility::string_t getRefCode() const;
    bool refCodeIsSet() const;
    void unsetRefCode();
    void setRefCode(const utility::string_t& value);

    /// <summary>
    /// Waitlist is the waitlist slug the grant lands on. Required.
    /// </summary>
    utility::string_t getWaitlist() const;
    bool waitlistIsSet() const;
    void unsetWaitlist();
    void setWaitlist(const utility::string_t& value);


protected:
    utility::string_t m_Email;
    bool m_EmailIsSet;

    int32_t m_Points;
    bool m_PointsIsSet;

    utility::string_t m_Reason;
    bool m_ReasonIsSet;

    utility::string_t m_RefCode;
    bool m_RefCodeIsSet;

    utility::string_t m_Waitlist;
    bool m_WaitlistIsSet;

};


}
}

#endif /* HANZO_MODEL_Cloud_waitlistBoostRequest_H_ */
