/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DataroomLiveness.h
 *
 * 
 */

#ifndef HANZO_MODEL_DataroomLiveness_H_
#define HANZO_MODEL_DataroomLiveness_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace hanzo {
namespace model {



class  DataroomLiveness
    : public ModelBase
{
public:
    DataroomLiveness();
    virtual ~DataroomLiveness();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// DataroomLiveness members


    /// <summary>
    /// Service names the subsystem answering, so a probe response is attributable when several are collected together.
    /// </summary>
    utility::string_t getService() const;
    bool serviceIsSet() const;
    void unsetService();
    void setService(const utility::string_t& value);

    /// <summary>
    /// Status is &#x60;ok&#x60;. This probe has no degraded answer by design: it reports process liveness and nothing that could be false while the process serves.
    /// </summary>
    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const utility::string_t& value);


protected:
    utility::string_t m_Service;
    bool m_ServiceIsSet;

    utility::string_t m_Status;
    bool m_StatusIsSet;

};


}
}

#endif /* HANZO_MODEL_DataroomLiveness_H_ */
