/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DataroomLinkOne.h
 *
 * 
 */

#ifndef HANZO_MODEL_DataroomLinkOne_H_
#define HANZO_MODEL_DataroomLinkOne_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include "hanzo/model/DataroomLink.h"

namespace hanzo {
namespace model {

class DataroomLink;


class  DataroomLinkOne
    : public ModelBase
{
public:
    DataroomLinkOne();
    virtual ~DataroomLinkOne();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// DataroomLinkOne members


    /// <summary>
    /// Link is the link itself, including the id a visitor opens it with.
    /// </summary>
    std::shared_ptr<DataroomLink> getLink() const;
    bool linkIsSet() const;
    void unsetLink();
    void setLink(const std::shared_ptr<DataroomLink>& value);


protected:
    std::shared_ptr<DataroomLink> m_Link;
    bool m_LinkIsSet;

};


}
}

#endif /* HANZO_MODEL_DataroomLinkOne_H_ */
