/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * O11y_O11yFunnelCreateIn.h
 *
 * 
 */

#ifndef HANZO_MODEL_O11y_O11yFunnelCreateIn_H_
#define HANZO_MODEL_O11y_O11yFunnelCreateIn_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace hanzo {
namespace model {



class  O11y_O11yFunnelCreateIn
    : public ModelBase
{
public:
    O11y_O11yFunnelCreateIn();
    virtual ~O11y_O11yFunnelCreateIn();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// O11y_O11yFunnelCreateIn members


    /// <summary>
    /// Name is the funnel&#39;s name.
    /// </summary>
    utility::string_t getFunnelName() const;
    bool funnelNameIsSet() const;
    void unsetFunnel_name();
    void setFunnelName(const utility::string_t& value);

    /// <summary>
    /// Timestamp is when the funnel was created, as a millisecond epoch. Zero takes the runtime&#39;s own clock.
    /// </summary>
    int32_t getTimestamp() const;
    bool timestampIsSet() const;
    void unsetTimestamp();
    void setTimestamp(int32_t value);


protected:
    utility::string_t m_Funnel_name;
    bool m_Funnel_nameIsSet;

    int32_t m_Timestamp;
    bool m_TimestampIsSet;

};


}
}

#endif /* HANZO_MODEL_O11y_O11yFunnelCreateIn_H_ */
