/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * O11y_O11yAggregation.h
 *
 * 
 */

#ifndef HANZO_MODEL_O11y_O11yAggregation_H_
#define HANZO_MODEL_O11y_O11yAggregation_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include "hanzo/model/O11y_O11yAggregationMeta.h"
#include <cpprest/details/basic_types.h>
#include "hanzo/model/O11y_O11yMetricSeries.h"
#include <vector>

namespace hanzo {
namespace model {

class O11y_O11yMetricSeries;
class O11y_O11yAggregationMeta;


class  O11y_O11yAggregation
    : public ModelBase
{
public:
    O11y_O11yAggregation();
    virtual ~O11y_O11yAggregation();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// O11y_O11yAggregation members


    /// <summary>
    /// Alias is the aggregation&#39;s alias.
    /// </summary>
    utility::string_t getAlias() const;
    bool aliasIsSet() const;
    void unsetAlias();
    void setAlias(const utility::string_t& value);

    /// <summary>
    /// AnomalyScores are anomaly overlays.
    /// </summary>
    std::vector<std::shared_ptr<O11y_O11yMetricSeries>> getAnomalyScores() const;
    bool anomalyScoresIsSet() const;
    void unsetAnomalyScores();
    void setAnomalyScores(const std::vector<std::shared_ptr<O11y_O11yMetricSeries>>& value);

    /// <summary>
    /// Index is the aggregation&#39;s position in the query.
    /// </summary>
    int32_t getIndex() const;
    bool indexIsSet() const;
    void unsetIndex();
    void setIndex(int32_t value);

    /// <summary>
    /// LowerBoundSeries are forecast lower bounds.
    /// </summary>
    std::vector<std::shared_ptr<O11y_O11yMetricSeries>> getLowerBoundSeries() const;
    bool lowerBoundSeriesIsSet() const;
    void unsetLowerBoundSeries();
    void setLowerBoundSeries(const std::vector<std::shared_ptr<O11y_O11yMetricSeries>>& value);

    /// <summary>
    /// Meta describes the aggregation.
    /// </summary>
    std::shared_ptr<O11y_O11yAggregationMeta> getMeta() const;
    bool metaIsSet() const;
    void unsetMeta();
    void setMeta(const std::shared_ptr<O11y_O11yAggregationMeta>& value);

    /// <summary>
    /// PredictedSeries are forecast overlays, when the query asked for them.
    /// </summary>
    std::vector<std::shared_ptr<O11y_O11yMetricSeries>> getPredictedSeries() const;
    bool predictedSeriesIsSet() const;
    void unsetPredictedSeries();
    void setPredictedSeries(const std::vector<std::shared_ptr<O11y_O11yMetricSeries>>& value);

    /// <summary>
    /// Series are the aggregated time series.
    /// </summary>
    std::vector<std::shared_ptr<O11y_O11yMetricSeries>> getSeries() const;
    bool seriesIsSet() const;
    void unsetSeries();
    void setSeries(const std::vector<std::shared_ptr<O11y_O11yMetricSeries>>& value);

    /// <summary>
    /// UpperBoundSeries are forecast upper bounds.
    /// </summary>
    std::vector<std::shared_ptr<O11y_O11yMetricSeries>> getUpperBoundSeries() const;
    bool upperBoundSeriesIsSet() const;
    void unsetUpperBoundSeries();
    void setUpperBoundSeries(const std::vector<std::shared_ptr<O11y_O11yMetricSeries>>& value);


protected:
    utility::string_t m_Alias;
    bool m_AliasIsSet;

    std::vector<std::shared_ptr<O11y_O11yMetricSeries>> m_AnomalyScores;
    bool m_AnomalyScoresIsSet;

    int32_t m_Index;
    bool m_IndexIsSet;

    std::vector<std::shared_ptr<O11y_O11yMetricSeries>> m_LowerBoundSeries;
    bool m_LowerBoundSeriesIsSet;

    std::shared_ptr<O11y_O11yAggregationMeta> m_Meta;
    bool m_MetaIsSet;

    std::vector<std::shared_ptr<O11y_O11yMetricSeries>> m_PredictedSeries;
    bool m_PredictedSeriesIsSet;

    std::vector<std::shared_ptr<O11y_O11yMetricSeries>> m_Series;
    bool m_SeriesIsSet;

    std::vector<std::shared_ptr<O11y_O11yMetricSeries>> m_UpperBoundSeries;
    bool m_UpperBoundSeriesIsSet;

};


}
}

#endif /* HANZO_MODEL_O11y_O11yAggregation_H_ */
