/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * O11y_O11yDiscoverIn.h
 *
 * 
 */

#ifndef HANZO_MODEL_O11y_O11yDiscoverIn_H_
#define HANZO_MODEL_O11y_O11yDiscoverIn_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include "hanzo/model/O11y_O11yFilter.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace hanzo {
namespace model {

class O11y_O11yFilter;


class  O11y_O11yDiscoverIn
    : public ModelBase
{
public:
    O11y_O11yDiscoverIn();
    virtual ~O11y_O11yDiscoverIn();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// O11y_O11yDiscoverIn members


    /// <summary>
    /// Aggregations are the measures to compute per group. Empty means a count.
    /// </summary>
    std::vector<utility::string_t> getAggregations() const;
    bool aggregationsIsSet() const;
    void unsetAggregations();
    void setAggregations(const std::vector<utility::string_t>& value);

    /// <summary>
    /// Filters narrow the scan; each is a field, an operator (eq, neq, like) and a value, and they combine with AND.
    /// </summary>
    std::vector<std::shared_ptr<O11y_O11yFilter>> getFilters() const;
    bool filtersIsSet() const;
    void unsetFilters();
    void setFilters(const std::vector<std::shared_ptr<O11y_O11yFilter>>& value);

    /// <summary>
    /// GroupBy are the columns to group the rows by.
    /// </summary>
    std::vector<utility::string_t> getGroupBy() const;
    bool groupByIsSet() const;
    void unsetGroupBy();
    void setGroupBy(const std::vector<utility::string_t>& value);

    /// <summary>
    /// Limit caps how many rows come back.
    /// </summary>
    int32_t getLimit() const;
    bool limitIsSet() const;
    void unsetLimit();
    void setLimit(int32_t value);

    /// <summary>
    /// OrderBy is the column or aggregation to sort the rows on.
    /// </summary>
    utility::string_t getOrderBy() const;
    bool orderByIsSet() const;
    void unsetOrderBy();
    void setOrderBy(const utility::string_t& value);

    /// <summary>
    /// OrderDir is asc or desc.
    /// </summary>
    utility::string_t getOrderDir() const;
    bool orderDirIsSet() const;
    void unsetOrderDir();
    void setOrderDir(const utility::string_t& value);

    /// <summary>
    /// Period is the window to read, relative to now — 1h, 24h, 7d, 14d, 30d.
    /// </summary>
    utility::string_t getPeriod() const;
    bool periodIsSet() const;
    void unsetPeriod();
    void setPeriod(const utility::string_t& value);

    /// <summary>
    /// Project is the project to read, as its id. Required.
    /// </summary>
    utility::string_t getProject() const;
    bool projectIsSet() const;
    void unsetProject();
    void setProject(const utility::string_t& value);


protected:
    std::vector<utility::string_t> m_Aggregations;
    bool m_AggregationsIsSet;

    std::vector<std::shared_ptr<O11y_O11yFilter>> m_Filters;
    bool m_FiltersIsSet;

    std::vector<utility::string_t> m_GroupBy;
    bool m_GroupByIsSet;

    int32_t m_Limit;
    bool m_LimitIsSet;

    utility::string_t m_OrderBy;
    bool m_OrderByIsSet;

    utility::string_t m_OrderDir;
    bool m_OrderDirIsSet;

    utility::string_t m_Period;
    bool m_PeriodIsSet;

    utility::string_t m_Project;
    bool m_ProjectIsSet;

};


}
}

#endif /* HANZO_MODEL_O11y_O11yDiscoverIn_H_ */
