/**
 * Hanzo Cloud API
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OverviewView.h
 *
 * 
 */

#ifndef HANZO_MODEL_OverviewView_H_
#define HANZO_MODEL_OverviewView_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include "hanzo/model/StepView.h"
#include <cpprest/details/basic_types.h>
#include "hanzo/model/ProgressView.h"
#include <vector>
#include "hanzo/model/Funnel.h"

namespace hanzo {
namespace model {

class Funnel;
class ProgressView;
class StepView;


class  OverviewView
    : public ModelBase
{
public:
    OverviewView();
    virtual ~OverviewView();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// OverviewView members


    bool isCustom() const;
    bool customIsSet() const;
    void unsetCustom();
    void setCustom(bool value);

    std::shared_ptr<Funnel> getFunnel() const;
    bool funnelIsSet() const;
    void unsetFunnel();
    void setFunnel(const std::shared_ptr<Funnel>& value);

    std::shared_ptr<ProgressView> getProgress() const;
    bool progressIsSet() const;
    void unsetProgress();
    void setProgress(const std::shared_ptr<ProgressView>& value);

    std::vector<std::shared_ptr<StepView>> getSteps() const;
    bool stepsIsSet() const;
    void unsetSteps();
    void setSteps(const std::vector<std::shared_ptr<StepView>>& value);

    utility::string_t getTitle() const;
    bool titleIsSet() const;
    void unsetTitle();
    void setTitle(const utility::string_t& value);

    utility::string_t getVersion() const;
    bool versionIsSet() const;
    void unsetVersion();
    void setVersion(const utility::string_t& value);


protected:
    bool m_Custom;
    bool m_CustomIsSet;

    std::shared_ptr<Funnel> m_Funnel;
    bool m_FunnelIsSet;

    std::shared_ptr<ProgressView> m_Progress;
    bool m_ProgressIsSet;

    std::vector<std::shared_ptr<StepView>> m_Steps;
    bool m_StepsIsSet;

    utility::string_t m_Title;
    bool m_TitleIsSet;

    utility::string_t m_Version;
    bool m_VersionIsSet;

};


}
}

#endif /* HANZO_MODEL_OverviewView_H_ */
