/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ReleaseBoard.h
 *
 * 
 */

#ifndef HANZO_MODEL_ReleaseBoard_H_
#define HANZO_MODEL_ReleaseBoard_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include "hanzo/model/ReleaseRow.h"
#include <vector>

namespace hanzo {
namespace model {

class ReleaseRow;


class  ReleaseBoard
    : public ModelBase
{
public:
    ReleaseBoard();
    virtual ~ReleaseBoard();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ReleaseBoard members


    /// <summary>
    /// Releases are the deployments that genuinely reached the cluster.
    /// </summary>
    std::vector<std::shared_ptr<ReleaseRow>> getReleases() const;
    bool releasesIsSet() const;
    void unsetReleases();
    void setReleases(const std::vector<std::shared_ptr<ReleaseRow>>& value);


protected:
    std::vector<std::shared_ptr<ReleaseRow>> m_Releases;
    bool m_ReleasesIsSet;

};


}
}

#endif /* HANZO_MODEL_ReleaseBoard_H_ */
