/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/*
 * Search_deleteDocumentsByFilter_request.h
 *
 * 
 */

#ifndef HANZO_MODEL_Search_deleteDocumentsByFilter_request_H_
#define HANZO_MODEL_Search_deleteDocumentsByFilter_request_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include "hanzo/model/Search_deleteDocumentsByFilter_request_filter.h"

namespace hanzo {
namespace model {



class  Search_deleteDocumentsByFilter_request
    : public ModelBase
{
public:
    Search_deleteDocumentsByFilter_request();
    virtual ~Search_deleteDocumentsByFilter_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Search_deleteDocumentsByFilter_request members


    std::shared_ptr<Search_deleteDocumentsByFilter_request_filter> getFilter() const;
    bool filterIsSet() const;
    void unsetFilter();
    void setFilter(const std::shared_ptr<Search_deleteDocumentsByFilter_request_filter>& value);


protected:
    std::shared_ptr<Search_deleteDocumentsByFilter_request_filter> m_Filter;
    bool m_FilterIsSet;

};


}
}

#endif /* HANZO_MODEL_Search_deleteDocumentsByFilter_request_H_ */
