/**
 * Hanzo Cloud API
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ServiceView.h
 *
 * 
 */

#ifndef HANZO_MODEL_ServiceView_H_
#define HANZO_MODEL_ServiceView_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace hanzo {
namespace model {



class  ServiceView
    : public ModelBase
{
public:
    ServiceView();
    virtual ~ServiceView();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ServiceView members


    int32_t getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreatedAt();
    void setCreatedAt(int32_t value);

    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();
    void setDescription(const utility::string_t& value);

    utility::string_t getDisplayName() const;
    bool displayNameIsSet() const;
    void unsetDisplayName();
    void setDisplayName(const utility::string_t& value);

    std::vector<utility::string_t> getHosts() const;
    bool hostsIsSet() const;
    void unsetHosts();
    void setHosts(const std::vector<utility::string_t>& value);

    utility::string_t getService() const;
    bool serviceIsSet() const;
    void unsetService();
    void setService(const utility::string_t& value);

    int32_t getUpdatedAt() const;
    bool updatedAtIsSet() const;
    void unsetUpdatedAt();
    void setUpdatedAt(int32_t value);

    utility::string_t getUpdatedBy() const;
    bool updatedByIsSet() const;
    void unsetUpdatedBy();
    void setUpdatedBy(const utility::string_t& value);

    bool isWaitlistMode() const;
    bool waitlistModeIsSet() const;
    void unsetWaitlistMode();
    void setWaitlistMode(bool value);


protected:
    int32_t m_CreatedAt;
    bool m_CreatedAtIsSet;

    utility::string_t m_Description;
    bool m_DescriptionIsSet;

    utility::string_t m_DisplayName;
    bool m_DisplayNameIsSet;

    std::vector<utility::string_t> m_Hosts;
    bool m_HostsIsSet;

    utility::string_t m_Service;
    bool m_ServiceIsSet;

    int32_t m_UpdatedAt;
    bool m_UpdatedAtIsSet;

    utility::string_t m_UpdatedBy;
    bool m_UpdatedByIsSet;

    bool m_WaitlistMode;
    bool m_WaitlistModeIsSet;

};


}
}

#endif /* HANZO_MODEL_ServiceView_H_ */
