/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Step.h
 *
 * 
 */

#ifndef HANZO_MODEL_Step_H_
#define HANZO_MODEL_Step_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace hanzo {
namespace model {



class  Step
    : public ModelBase
{
public:
    Step();
    virtual ~Step();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Step members


    /// <summary>
    /// Body is the message text. Required. The signed one-click unsubscribe link is appended to it at send time.
    /// </summary>
    utility::string_t getBody() const;
    bool bodyIsSet() const;
    void unsetBody();
    void setBody(const utility::string_t& value);

    /// <summary>
    /// CreatedAt is unix seconds, server-assigned.
    /// </summary>
    int32_t getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreatedAt();
    void setCreatedAt(int32_t value);

    /// <summary>
    /// DelaySeconds is how long after the previous step this one sends (after enrollment, for step 0).
    /// </summary>
    int32_t getDelaySeconds() const;
    bool delaySecondsIsSet() const;
    void unsetDelaySeconds();
    void setDelaySeconds(int32_t value);

    /// <summary>
    /// ID is the server-assigned step id (\&quot;step_\&quot; + 128 random bits).
    /// </summary>
    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(const utility::string_t& value);

    /// <summary>
    /// Idx is the step&#39;s 0-based position, assigned by appending: a new step always lands after the last one.
    /// </summary>
    int32_t getIdx() const;
    bool idxIsSet() const;
    void unsetIdx();
    void setIdx(int32_t value);

    /// <summary>
    /// SequenceID is the sequence this step belongs to.
    /// </summary>
    utility::string_t getSequenceId() const;
    bool sequenceIdIsSet() const;
    void unsetSequenceId();
    void setSequenceId(const utility::string_t& value);

    /// <summary>
    /// Subject is the email subject line, capped at 1024 bytes.
    /// </summary>
    utility::string_t getSubject() const;
    bool subjectIsSet() const;
    void unsetSubject();
    void setSubject(const utility::string_t& value);


protected:
    utility::string_t m_Body;
    bool m_BodyIsSet;

    int32_t m_CreatedAt;
    bool m_CreatedAtIsSet;

    int32_t m_DelaySeconds;
    bool m_DelaySecondsIsSet;

    utility::string_t m_Id;
    bool m_IdIsSet;

    int32_t m_Idx;
    bool m_IdxIsSet;

    utility::string_t m_SequenceId;
    bool m_SequenceIdIsSet;

    utility::string_t m_Subject;
    bool m_SubjectIsSet;

};


}
}

#endif /* HANZO_MODEL_Step_H_ */
