/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Timeseries.h
 *
 * 
 */

#ifndef HANZO_MODEL_Timeseries_H_
#define HANZO_MODEL_Timeseries_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include "hanzo/model/Scope.h"
#include <cpprest/details/basic_types.h>
#include "hanzo/model/UsagePoint.h"
#include <vector>

namespace hanzo {
namespace model {

class Scope;
class UsagePoint;


class  Timeseries
    : public ModelBase
{
public:
    Timeseries();
    virtual ~Timeseries();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Timeseries members


    /// <summary>
    /// End is the window&#39;s exclusive upper bound, RFC3339 UTC.
    /// </summary>
    utility::string_t getEnd() const;
    bool endIsSet() const;
    void unsetEnd();
    void setEnd(const utility::string_t& value);

    /// <summary>
    /// Interval is the bucket width: hour or day.
    /// </summary>
    utility::string_t getInterval() const;
    bool intervalIsSet() const;
    void unsetInterval();
    void setInterval(const utility::string_t& value);

    /// <summary>
    /// Range is the window that was actually applied: 24h, 7d, 30d or custom.
    /// </summary>
    utility::string_t getRange() const;
    bool rangeIsSet() const;
    void unsetRange();
    void setRange(const utility::string_t& value);

    /// <summary>
    /// Scope names the tenant these numbers belong to.
    /// </summary>
    std::shared_ptr<Scope> getScope() const;
    bool scopeIsSet() const;
    void unsetScope();
    void setScope(const std::shared_ptr<Scope>& value);

    /// <summary>
    /// Series is one point per bucket, oldest first, with empty buckets zero-filled.
    /// </summary>
    std::vector<std::shared_ptr<UsagePoint>> getSeries() const;
    bool seriesIsSet() const;
    void unsetSeries();
    void setSeries(const std::vector<std::shared_ptr<UsagePoint>>& value);

    /// <summary>
    /// Source is the warehouse table the series read.
    /// </summary>
    utility::string_t getSource() const;
    bool sourceIsSet() const;
    void unsetSource();
    void setSource(const utility::string_t& value);

    /// <summary>
    /// Start is the window&#39;s inclusive lower bound, RFC3339 UTC.
    /// </summary>
    utility::string_t getStart() const;
    bool startIsSet() const;
    void unsetStart();
    void setStart(const utility::string_t& value);


protected:
    utility::string_t m_End;
    bool m_EndIsSet;

    utility::string_t m_Interval;
    bool m_IntervalIsSet;

    utility::string_t m_Range;
    bool m_RangeIsSet;

    std::shared_ptr<Scope> m_Scope;
    bool m_ScopeIsSet;

    std::vector<std::shared_ptr<UsagePoint>> m_Series;
    bool m_SeriesIsSet;

    utility::string_t m_Source;
    bool m_SourceIsSet;

    utility::string_t m_Start;
    bool m_StartIsSet;

};


}
}

#endif /* HANZO_MODEL_Timeseries_H_ */
