/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UsageSummary.h
 *
 * 
 */

#ifndef HANZO_MODEL_UsageSummary_H_
#define HANZO_MODEL_UsageSummary_H_

#include <boost/optional.hpp>

#include "hanzo/ModelBase.h"

#include "hanzo/model/Accounts.h"
#include "hanzo/model/UsageScope.h"
#include <cpprest/details/basic_types.h>
#include "hanzo/model/Sources.h"
#include "hanzo/model/Spend.h"
#include "hanzo/model/LLM.h"

namespace hanzo {
namespace model {

class Accounts;
class LLM;
class UsageScope;
class Sources;
class Spend;


class  UsageSummary
    : public ModelBase
{
public:
    UsageSummary();
    virtual ~UsageSummary();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// UsageSummary members


    /// <summary>
    /// Accounts is the caller&#39;s own linked provider accounts beside the org&#39;s Hanzo-routed usage, labelled row by row and never summed together.
    /// </summary>
    std::shared_ptr<Accounts> getAccounts() const;
    bool accountsIsSet() const;
    void unsetAccounts();
    void setAccounts(const std::shared_ptr<Accounts>& value);

    /// <summary>
    /// End is the window&#39;s exclusive end, RFC3339 UTC.
    /// </summary>
    utility::string_t getEnd() const;
    bool endIsSet() const;
    void unsetEnd();
    void setEnd(const utility::string_t& value);

    /// <summary>
    /// Interval is the bucket width the spend series is gap-filled at.
    /// </summary>
    utility::string_t getInterval() const;
    bool intervalIsSet() const;
    void unsetInterval();
    void setInterval(const utility::string_t& value);

    /// <summary>
    /// LLM is the org&#39;s Hanzo-routed inference totals from the warehouse.
    /// </summary>
    std::shared_ptr<LLM> getLlm() const;
    bool llmIsSet() const;
    void unsetLlm();
    void setLlm(const std::shared_ptr<LLM>& value);

    /// <summary>
    /// Range is the window label that was served.
    /// </summary>
    utility::string_t getRange() const;
    bool rangeIsSet() const;
    void unsetRange();
    void setRange(const utility::string_t& value);

    /// <summary>
    /// Scope is the tenant and subject the roll-up was answered for.
    /// </summary>
    std::shared_ptr<UsageScope> getScope() const;
    bool scopeIsSet() const;
    void unsetScope();
    void setScope(const std::shared_ptr<UsageScope>& value);

    /// <summary>
    /// Sources says which upstreams actually answered, so a zero can be read as \&quot;no data yet\&quot; rather than as a measurement.
    /// </summary>
    std::shared_ptr<Sources> getSources() const;
    bool sourcesIsSet() const;
    void unsetSources();
    void setSources(const std::shared_ptr<Sources>& value);

    /// <summary>
    /// Spend is the categorized cost roll-up from the billing ledger.
    /// </summary>
    std::shared_ptr<Spend> getSpend() const;
    bool spendIsSet() const;
    void unsetSpend();
    void setSpend(const std::shared_ptr<Spend>& value);

    /// <summary>
    /// Start is the window&#39;s inclusive start, RFC3339 UTC.
    /// </summary>
    utility::string_t getStart() const;
    bool startIsSet() const;
    void unsetStart();
    void setStart(const utility::string_t& value);


protected:
    std::shared_ptr<Accounts> m_Accounts;
    bool m_AccountsIsSet;

    utility::string_t m_End;
    bool m_EndIsSet;

    utility::string_t m_Interval;
    bool m_IntervalIsSet;

    std::shared_ptr<LLM> m_Llm;
    bool m_LlmIsSet;

    utility::string_t m_Range;
    bool m_RangeIsSet;

    std::shared_ptr<UsageScope> m_Scope;
    bool m_ScopeIsSet;

    std::shared_ptr<Sources> m_Sources;
    bool m_SourcesIsSet;

    std::shared_ptr<Spend> m_Spend;
    bool m_SpendIsSet;

    utility::string_t m_Start;
    bool m_StartIsSet;

};


}
}

#endif /* HANZO_MODEL_UsageSummary_H_ */
